### ISSUE TITLE
nodejs fails to install node on CentOS

### ISSUE THREAD

**Issue by victorkane** [geerlingguy/ansible-for-devops#1]
Following directions in nodejs/README.md I'm getting:

````
TASK: [Install Node.js and npm.] **********************************************
failed: [default] => {"changed": false, "failed": true, "rc": 0, "results": []}
msg: **No Package matching 'npm' found available, installed or updated**

FATAL: all hosts have already failed -- aborting
````
Seems to be a problem with EPEL? BTW, the EPEL repo task, and all tasks prior to this one, complete successfully.

At this point the playbook aborts of course.

**Comment by geerlingguy** [comment]
Taking a look. Thanks for reporting!

**Comment by geerlingguy** [comment]
I can't replicate the issue; I built the VM twice without a problem. I'm going to attribute it to EPEL being funny for a day or something.
