### ISSUE TITLE
Have to set gather_facts = false in digitalocean provision.yml playbook to get it to work on first run

### ISSUE THREAD

**Issue by jonathanhle** [geerlingguy/ansible-for-devops#10]
In provision.yml for the digitalocean inventory example, it currently works if you run the playbook twice.  It'll provision the droplet on the first run, but will fail while trying to gather facts during the first run.  On the 2nd run, it'll be able to gather facts, so it'll pass, then keep running through the playbooks tasks.

The task in the 2nd half of the playbook to wait_for ssh to come up doesn't seem to apply before gather_facts is called.  Unfortunately, I didn't find a way to delay gathering_facts with a "wait_for" or anything like that - so I think it'll always fail the first time provision.yml is called.  I believe to get the provision.yml to work with the first time, gather_facts needs to be false in both places.

This works works for me.  Setting gather_facts: true doesn't seem to work for me:
- hosts: do
  remote_user: root
  gather_facts: false

  tasks:
    - name: Wait for port 22 to become available.
      local_action: "wait_for port=22 host={{ inventory_hostname }}"

==> Is there a way to set a gather_facts delay?
![image](https://cloud.githubusercontent.com/assets/3851599/6032147/8291c5d4-abba-11e4-8e5c-cdc668104dac.png)

**Comment by geerlingguy** [comment]
I distinctly remember hitting this problem when developing they playbook, but it went away at some point. I wonder if it might have something to do with the data center you use... I'll try to see if I can find a different way to get this to work, since many steps require some of the gathered facts.

**Comment by geerlingguy** [comment]
In this particular instance, no facts are needed, so I just implemented the change you suggested :)
