### ISSUE TITLE
[section_request] Testing Ansible playbooks and roles with Molecule + ansible-lint

### ISSUE THREAD

**Issue by robsonpeixoto** [geerlingguy/ansible-for-devops#101]

**Comment by geerlingguy** [comment]
Good question. The [Molecule](https://github.com/metacloud/molecule) project has had a lot of uptake, and is definitely somewhat of a standard (even though I don't currently use it, ha!) for Ansible testing... I will consider it.

**Comment by geerlingguy** [comment]
Yes. I will be working on it soon :)

I've been slowly moving some of my roles over to using Molecule instead of my home-grown solution, for example:

  - https://travis-ci.org/geerlingguy/ansible-role-ansible
  - https://travis-ci.org/geerlingguy/ansible-role-apache
  - https://travis-ci.org/geerlingguy/ansible-role-nginx

**Comment by geerlingguy** [comment]
Sheesh, and a few of my roles (like Jenkins, Kibana, and Kubernetes) have soaked up an entire evening. It's slow progress, but I've learned a good deal about Molecule, and how some of my earlier tests were not quite up to my own standards!

**Comment by geerlingguy** [comment]
Here's the promised blog post: [Testing your Ansible roles with Molecule](https://www.jeffgeerling.com/blog/2018/testing-your-ansible-roles-molecule)

**Comment by geerlingguy** [comment]
And here's a blog post on [using Molecule to test Ansible Collections](https://www.jeffgeerling.com/blog/2019/how-add-integration-tests-ansible-collection-molecule). I promise, I'll get some of this content into the book soon :)

**Comment by 7php** [comment]
Perfect @geerlingguy!
Look forward to updates. cheers

**Comment by geerlingguy** [comment]
And a good presentation on Molecule (the basics) from #cfgmgmt2020 https://cfp.cfgmgmtcamp.be/media/molecule_cfgmgmt2020.pdf

**Comment by geerlingguy** [comment]
People seem to keep requesting this quite frequently. I think I'll try to get the testing chapter rewritten post-haste!

**Comment by geerlingguy** [comment]
Working on this... note that I'm thinking of covering this (ansible-lint + molecule) in the 6th episode of Ansible 101.

**Comment by geerlingguy** [comment]
Also wanted to give a shout out to @loganmarchione for [this reddit post](https://www.reddit.com/r/devops/comments/g5ina3/i_started_linting_my_ansible_playbooks_with_drone/) mentioning [How and why you should lint your Ansible playbooks](https://loganmarchione.com/2020/04/how-and-why-you-should-lint-your-ansible-playbooks/).

**Comment by geerlingguy** [comment]
Also [Ansible Linting with GitHub Actions](https://www.ansible.com/blog/ansible-linting-with-github-actions).

**Comment by geerlingguy** [comment]
While working on a full rewrite of the new chapter 12 tonight (I bumped 12/13/14 to 13/14/15 and extracted testing into its own chapter), I ran into an issue with `ansible-lint`: [https://github.com/ansible/ansible-lint/issues/763](https://github.com/ansible/ansible-lint/issues/763)

**Comment by geerlingguy** [comment]
Also opened up an issue in the Molecule repo: [Fix getting-started docs - Dockerfile no longer shipped by default](https://github.com/ansible-community/molecule/pull/2689). I can't resist!

**Comment by geerlingguy** [comment]
Very close to finishing up the majority of this chapter, but I had to finish up prep work for tomorrow's live stream (see #257)—anyone following this issue should check out the live video (https://www.youtube.com/watch?v=FaXVZ60o8L8) or watch it on demand later... I'll cover a little more depth in the book, but the video should be a good preview of what's coming in the next book version!

**Comment by geerlingguy** [comment]
I have the example committed, and most of the chapter rewritten. I'll probably post a new version of the book next week. Moving the last portion of this work—using Molecule in a GitHub Actions workflow—into a separate issue.

**Comment by geerlingguy** [comment]
Split out the GitHub Actions for CI workflows into https://github.com/geerlingguy/ansible-for-devops/issues/264. Closing this issue.

For those interested, this topic is also being covered in my free / live / on-demand Ansible 101 series on YouTube:

  - [Ansible 101 - Episode 7 - Molecule Testing and Linting and Ansible Galaxy](https://www.youtube.com/watch?v=FaXVZ60o8L8) (May 6)
  - [Ansible 101 - Episode 8 - Playbook testing with Molecule and GitHub Actions CI](https://www.youtube.com/watch?v=CYghlf-6Opc&feature=youtu.be) (May 13)
