### ISSUE TITLE
Can't create symlink 

### ISSUE THREAD

**Issue by khoi-thinh** [geerlingguy/ansible-for-devops#102]
I'm following an example about creating symlink and got this error.

[khoi@ansible-01 tmp]$ ansible multi -m file -a "dest=/src/test mode=644 state=directory"
[DEPRECATION WARNING]: DEFAULT_SUDO_EXE option, In favor of Ansible Become, which is a generic framework. See become_exe. , use become instead. This feature will be
removed in version 2.8. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: DEFAULT_ASK_SUDO_PASS option, In favor of Ansible Become, which is a generic framework. See become_ask_pass. , use become instead. This feature
will be removed in version 2.8. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
SUDO password:
ansible-02 | FAILED! => {
    "changed": false,
    "msg": "There was an issue creating /src as requested: [Errno 13] Permission denied: '/src'",
    "path": "/src/test",
    "state": "absent"
}
ansible-03 | FAILED! => {
    "changed": false,
    "msg": "There was an issue creating /src as requested: [Errno 13] Permission denied: '/src'",
    "path": "/src/test",
    "state": "absent"
}
localhost | FAILED! => {
    "changed": false,
    "msg": "There was an issue creating /src as requested: [Errno 13] Permission denied: '/src'",
    "path": "/src/test",
    "state": "absent"
}

**Comment by dglinder** [comment]
The error that Ansible is reporting:

    There was an issue creating /src as requested: [Errno 13] Permission denied: '/src'

is a generic one regarding the permissions your user has on that system.  In short, the Ansible playbook is attempting to make the `/src` directory, but your user lacks the permissions to create that in the root directory.

The version of the file I have shows this example:

    ansible multi -m file -a "dest=/tmp/test mode=644 state=directory"

In most Unix systems the `/tmp` directory exists and lets all users create files and directories there.  Assuming the `/tmp/test` directory doesn't already exist, this example should work for you.

**Comment by khoi-thinh** [comment]
Thank you.
