### ISSUE TITLE
[CHP 4, Add extra repositories] RPM-GPG-KEY-remi URL now https://

### ISSUE THREAD

**Issue by scottdavis99** [geerlingguy/ansible-for-devops#106]
Not sure if Ansible follows http:// -> https:// upgrades, but the new path to RPM-GPG-KEY-remi is 
https://rpms.remirepo.net/RPM-GPG-KEY-remi

**Comment by geerlingguy** [comment]
@scottdavis99 - Thanks for filing this issue; I've updated the remi repo and remi gpg key URLs in chapter 4 and in the code here (just waiting for test to finish then I'll commit and close out this issue).

The fix will be in the next published version of the book. Thanks again!

**Comment by scottdavis99** [comment]
Enjoying the book! Thx for keeping it up-to-date. I can only imagine what a challenge that is, given how quickly the ecosystem changes.
