### ISSUE TITLE
Add section on querying facts

### ISSUE THREAD

**Issue by Synchro** [geerlingguy/ansible-for-devops#107]
Something that's really simple in Chef (because of its database) but seems really difficult in ansible is querying the facts to extract information about hosts other than the one a play is running on.

Say I have a MySQL database server and multiple web servers that need to connect to it. Exactly how many web servers there are may be variable, and so needs to be established at runtime from an inventory group. In a play that's run _only_ on the database server, I want to be able to run commands that open the DB server's firewall to all the web servers, and also to define MySQL users that have access from those sources. The commands for calling ufw and creating mysql users are straightforward, but what's hard is getting the data to pass into them - because the play is run _only_ on the database server, the facts database may not contain any information about the web servers. Because of that, this is not about inventory.

When I do inspect the information from the facts (e.g. when some other play _is_ run on the web servers), it's not usable as-is - it needs considerable filtering, for example if I request all the IP addresses for a server, it also includes all the loopback and link-local addresses (`fe80:...`) which would need to be filtered out, and it's made harder by the fact that interface names are not predictable - most often it's `eth0`, but some of them are `eth1` or `ens3`, or many other values.

I've attempted to work around this by defining a static data structure in group vars that I can then query, but as well as that really going against the grain of dynamic configuration, it's just plain difficult to do it at all - the jinja2 syntax seems more complex than doing the whole thing manually, defeating the point of using ansible at all. [I've asked about this on StackOverflow](https://stackoverflow.com/questions/51782976/ansible-dynamic-lookup-in-a-nested-list) - but the answers have not helped. Something like JSONPath would seem like an appropriate tool for querying facts, but I don't know how I'd use that in ansible.

One approach might be to reverse the situation, and make it that each web server is responsible for modifying the db server to give it access - but that seems inelegant and backwards, and I suspect I'd just have the same problem in the other direction, especially if there is more than one DB server.

That's just one example - ansible is really good at applying things to individual servers or groups of them, but getting info about other servers in the cluster seems really difficult. I can't believe that I'm the only one running into this - it strikes me as a fundamental need for anyone with more than one server, so I'm really surprised this isn't straightforward - so I'd love to see some examples and tutorials about how to do it better.

**Comment by geerlingguy** [comment]
I don't think I can provide a quick answer for you in this issue, but I would highlight that you can use the [`json_query` filter](https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#json-query-filter) that was added in Ansible 2.2 to more easily digest JSON data in Ansible. Note that it requires you to install `jmespath` on your server separately.

There are definitely other hacky ways of filtering through the data, but I'd continue exploring other avenues more (and maybe ask more in #ansible on IRC/Freenode) as I don't have a great answer for you there.
