### ISSUE TITLE
For the "lamp-infrastructure" example, provisioning to AWS, there needs to be a VPC provisioning section. 

### ISSUE THREAD

**Issue by jonathanhle** [geerlingguy/ansible-for-devops#11]
Got an error to setup a VPC with the aws example: 
![image](https://cloud.githubusercontent.com/assets/3851599/6070651/29d3140e-ad43-11e4-9dcd-f66ade5c37d8.png)

**Comment by jonathanhle** [comment]
NM on this guy.  Play book worked well when I left it in us-west-1.  

I was trying it out in us-east-1, my VPC configuration had two groups called "default" which was messing this oneup. Thanks.

**Comment by geerlingguy** [comment]
The best issues are those that fix themselves :)

Glad you could figure it out!
