### ISSUE TITLE
Gluster playbook example ppa issues (Chapter 8)

### ISSUE THREAD

**Issue by dino-github** [geerlingguy/ansible-for-devops#111]
I had to disable the use of the ppa in vars.yml to get glusterfs to install/configure correctly:
glusterfs_ppa_use: false

Looking in the ppa it seems that 14.04 isn't supported anymore, but glusterfs 3.4.x is available in the ubuntu repos. 

So the only extra thing that needs to be done is minor firewall changes outlined in vars.yml for  Gluster 3.4+

Incidentally the playbook example also works  with 18.04

**Comment by geerlingguy** [comment]
Thanks for the report; working on this upstream in https://github.com/geerlingguy/ansible-vagrant-examples/issues/70

**Comment by geerlingguy** [comment]
Upstream issue is fixed; updating the text in the book now.

Thanks again for highlighting this, @dino-github!
