### ISSUE TITLE
Drupal LAMP server illustration for Ubuntu 16.04, the text says 14.04

### ISSUE THREAD

**Issue by deoren** [geerlingguy/ansible-for-devops#113]
The app versions shown in the illustration appear to match a 16.04 installation, but the text says 14.04. I'm guessing this is just a spot that was missed when refreshing the book at some point.

![image](https://user-images.githubusercontent.com/1550338/48305642-30ff7000-e4f4-11e8-863c-3118d2940721.png)

**Comment by geerlingguy** [comment]
Good catch, and I'm glad you're enjoying the book!

I just updated that line in the manuscript, and will update the version on LeanPub shortly. It will be rolled out to the other book editions soon.

I'll also make sure to add a mention crediting you for the fix in the changelog :)

**Comment by deoren** [comment]
> Good catch, and I'm glad you're enjoying the book!

Thank you, and very much so.

> I just updated that line in the manuscript, and will update the version on LeanPub shortly. It will be rolled out to the other book editions soon.

Nice. I saw on leanpub.com where they have a new version available for download. I'm still reading through the September 2018 edition and have been highlighting it extensively (Google Play Books). I'm curious about the changes in the new edition: is there a changelog for the book updates that you provide?

Thanks.
