### ISSUE TITLE
shell example, [CHP 4, Add extra repositories] RPM-GPG-KEY-remi URL now https://

### ISSUE THREAD

**Issue by erikj** [geerlingguy/ansible-for-devops#117]
Not sure if it's a concern since it's in a shell example and this is an **Ansible** book, but:

#106 's `https` updates for Remi's repo were applied to the Ansible code, but not to the shell example:

>
```
# Import Remi GPG key.
 wget http://rpms.famillecollet.com/RPM-GPG-KEY-remi \
-O /etc/pki/rpm-gpg/RPM-GPG-KEY-remi
rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-remi
# Install Remi repo.
rpm -Uvh --quiet \
http://rpms.remirepo.net/enterprise/remi-release-7.rpm
```

> *This version was published on 2018-11-18*

Enjoying and learning a lot from the book, thanks.

**Comment by geerlingguy** [comment]
Good catch! I missed that when updated that part of the text. This fix will be in the next version of the book on LeanPub (published this week hopefully!)
