### ISSUE TITLE
typo on p. 101

### ISSUE THREAD

**Issue by erikj** [geerlingguy/ansible-for-devops#118]
Hello-

> You can also `rekey` a file (change it’s password)...

*it's* should be *its*.

Thanks.

**Comment by geerlingguy** [comment]
Grr, this is probably the number one thing I do subconsciously in my writing... I even have an action which I run any time I publish a major version to find all instances of `it's` and I manually review them; this one must've slipped through the cracks!

Thanks; this fix will be in the next revision.
