### ISSUE TITLE
Mention ansible-inventory CLI utility for inventory debugging

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-for-devops#120]
I saw mention of this at the Jan 8 2019 meetup in St. Louis. I've seen the tool before, and used it once or twice, but it is definitely handy in certain scenarios, and deserves a mention in an inventory-related section of the book (maybe where I set up the custom dynamic inventory?).

**Comment by geerlingguy** [comment]
Docs: https://docs.ansible.com/ansible/latest/cli/ansible-inventory.html

**Comment by nqb** [comment]
> but it is definitely handy in certain scenarios

I can confirm this.

**Comment by geerlingguy** [comment]
Moving this into larger issue about Inventory Plugins: https://github.com/geerlingguy/ansible-for-devops/issues/201
