### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by eCubeH** [geerlingguy/ansible-for-devops#122]
Just starting to read the book (2018-11-18), reading Intro.
- Foreword by Tim Gerla says, "In 2013, Said Ziouani, Michael DeHaan, **and I** launched Ansible, Inc.", while Introduction says, "Ansible, Inc. was founded by Saïd Ziouani (@SaidZiouani10 on Twitter) and Michael DeHaan, and then acquired by Red Hat in 2016."?
- Oh, and the very next paragraph says, "In October **2015**, Red Hat acquired Ansible, Inc.,"

**Comment by geerlingguy** [comment]
Gah, those are pretty obvious issues. I think the technicality surrounding the founding members is a little ambiguous, so I'm going to add Tim to that list in the introduction. Also, I'm fixing the acquisition date—it was most definitely October 2016. This and a few other fixes will be bundled up in an update coming this week!

Thanks for bringing this to my attention!

**Comment by geerlingguy** [comment]
Fix is in the manuscript; thanks again!
