### ISSUE TITLE
Update deployments-rolling example to work with Ubuntu 18.04 and Node.js 10.x

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-for-devops#124]
The demo-nodejs-api seems to have some issues installing and running under the latest LTS release of Node.js (10.x): https://github.com/geerlingguy/demo-nodejs-api

Basically, if you leave a Node.js app alone for more than 6 months or so, half the dependencies will go unmaintained and/or change names entirely (I'm looking at you, jade/pug!).

The example works under Ubuntu 14.04, but I am upgrading all my examples to at least 16.04 (in this case I would like to just go straight to 18.04), and I can't install Node.js 4.x or lower (which is compatible with the current nodejs-api demo app linked above) on Ubuntu 18.04... nor _should_ I.

So for this ticket, I need to do some upstream work in the Node.js API demo app, to get it either rewritten or updated to work on modern Node.js, then test the full process on the deployments-rolling example.

**Comment by geerlingguy** [comment]
Upstream issue: https://github.com/geerlingguy/demo-nodejs-api/issues/1

**Comment by geerlingguy** [comment]
Yay, also got tests passing in Travis CI again, on LTS + current.

**Comment by geerlingguy** [comment]
Testing locally.

**Comment by geerlingguy** [comment]
Build is failing inside the VM when it runs the tests on tag `2.0.0`:

```
vagrant@nodejs1:/opt/demo-nodejs-api$ npm test

> examplenodejsapi@ test /opt/demo-nodejs-api
> mocha test --exit



restify listening at http://[::]:8080
  Hello
    /hello/:name endpoint
      ✓ returns a welcome message based on the name

  Ping
    /ping/:server endpoint
      ✓ tells us when a server is reachable
      1) tells us when a server is reachable

  2 passing (69ms)
  1 failing

  1) Ping
       /ping/:server endpoint
         tells us when a server is reachable:
     Uncaught Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
      at ServerResponse.setHeader (_http_outgoing.js:470:11)
      at ServerResponse.__send (node_modules/restify/lib/response.js:503:18)
      at ServerResponse.send (node_modules/restify/lib/response.js:316:21)
      at /opt/demo-nodejs-api/app.js:20:11
      at Socket.<anonymous> (node_modules/jjg-ping/lib/ping-system.js:82:25)
      at Socket.EventEmitter.emit (domain.js:441:20)
      at addChunk (_stream_readable.js:283:12)
      at readableAddChunk (_stream_readable.js:264:11)
      at Socket.Readable.push (_stream_readable.js:219:10)
      at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

**Comment by geerlingguy** [comment]
Dependency tree via `npm ls` is identical, so it has to be a system difference. Tests are also passing on Node.js 10.x and 11.x on Travis CI: https://travis-ci.org/geerlingguy/demo-nodejs-api

Going to also test locally in the official node.js container.

**Comment by geerlingguy** [comment]
```
$ docker run --rm -it node /bin/bash
# cd /opt
# git clone https://github.com/geerlingguy/demo-nodejs-api.git
# cd demo-nodejs-api
# npm install
# npm test

> examplenodejsapi@ test /opt/demo-nodejs-api
> mocha test --exit



restify listening at http://[::]:8080
  Hello
    /hello/:name endpoint
      ✓ returns a welcome message based on the name (50ms)

  Ping
    /ping/:server endpoint
      1) tells us when a server is reachable

  Ping
    /ping/:server endpoint
      ✓ tells us when a server is unreachable


  2 passing (2s)
  1 failing

  1) Ping
       /ping/:server endpoint
         tells us when a server is reachable:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/opt/demo-nodejs-api/test/ping.js)
  



npm ERR! Test failed.  See above for more details.

```

Drat. Looks like just running `ping www.google.com` is also failing to actually ping inside the container. From the outside, it works fine.

**Comment by geerlingguy** [comment]
So in the Docker container it fails too:

```
# npm test

> examplenodejsapi@ test /opt/demo-nodejs-api
> mocha test --exit



restify listening at http://[::]:8080
  Hello
    /hello/:name endpoint
      ✓ returns a welcome message based on the name

  Ping
    /ping/:server endpoint
      ✓ tells us when a server is reachable (87ms)
      1) tells us when a server is reachable

  2 passing (124ms)
  1 failing

  1) Ping
       /ping/:server endpoint
         tells us when a server is reachable:
     Uncaught Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
      at ServerResponse.setHeader (_http_outgoing.js:482:11)
      at ServerResponse.__send (node_modules/restify/lib/response.js:503:18)
      at ServerResponse.send (node_modules/restify/lib/response.js:316:21)
      at /opt/demo-nodejs-api/app.js:20:11
      at Socket.<anonymous> (node_modules/jjg-ping/lib/ping-system.js:82:25)
      at Socket.EventEmitter.emit (domain.js:439:20)
      at addChunk (_stream_readable.js:288:12)
      at readableAddChunk (_stream_readable.js:269:11)
      at Socket.Readable.push (_stream_readable.js:224:10)
      at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:145:17)



npm ERR! Test failed.  See above for more details.
```

Weird. Something must be different locally :/

**Comment by geerlingguy** [comment]
The plot thickens; if I use `docker run --rm -it node:8 /bin/bash` it works. But locally, it's running Node 11.x... and in Travis it's doing 1.10.x and 1.11.x. What the heck?

**Comment by geerlingguy** [comment]
`docker run --rm -it node:10 /bin/bash` does _not_ work.

**Comment by geerlingguy** [comment]
| `docker run --rm -it node:8 /bin/bash` | ✅ |
| `docker run --rm -it node:9 /bin/bash` | ✅ |
| `docker run --rm -it node:10 /bin/bash` | ✖️ |
| `docker run --rm -it node:11 /bin/bash` | ✅ |

**Comment by geerlingguy** [comment]
How does `node:11` work and `node:latest` not?! According to the Docker Hub docs (https://hub.docker.com/_/node/) they are identical... and the version is the same (`v11.7.0`).

**Comment by geerlingguy** [comment]
Now my mind is exploding—I just manually ran the test again with `node:latest`... and it passed.

And so I ran it on `node:10` and that's passing too.

And so I ran it on `node:9` and that's passing too.

I have a sneaking suspicion.

**Comment by geerlingguy** [comment]
I HATE YOU CHARTER SPECTRUM WITH AN UNDYING PASSION.

So it boils down to this: Charter Spectrum's DNS servers were not giving the correct response for an invalid domain, causing an error in the `Ping` class I'm using as part of the rest API. Apparently in the past few hours they fixed that problem and now I'm getting the correct answer `cannot resolve gqtqM7eWGMeiQD2X: Unknown host`.

So basically, the lesson is never use your ISP's DNS.

**Comment by dglinder** [comment]
So, add step 0:
``Ensure DNS settings are set to a non-brain-damaged server...``

**Comment by geerlingguy** [comment]
@dglinder haha, yes. Exactly.

**Comment by geerlingguy** [comment]
So not only was that an issue... but after solving that I was still getting the error inside the Ubuntu 18.04 environment in Vagrant.

After another few hours debugging (even stepping through with Node's built-in debugger), I finally traced the error back to JJG-Ping... a library I wrote myself. Kudos to https://stackoverflow.com/a/9802084/100134 for the nudge in the right direction—I have to buffer the stdout from the ping call, otherwise the 'data' event can be called more than once in some weird situations, even for a very small data payload.

Opening an upstream issue...

**Comment by geerlingguy** [comment]
Testing a new tagged release. Upstream issue was https://github.com/geerlingguy/JJG-Node-Ping/issues/3

**Comment by geerlingguy** [comment]
Oh what a rabbit hole that was. Sheesh.

**Comment by typ-ex** [comment]
I couldn't get this to work on ubuntu 20.04.  

Node.js API app tests task fails whenever the version changes and naturally gets skipped when the playbook is ran again.

**Comment by typ-ex** [comment]
Seems to be a fault with the ansible-galaxy role of geerlingguy.nodejs

The task of ensuring node.js and npm are installed is skipped.

**Comment by typ-ex** [comment]
Oh.  Maybe beyond what was already done here, it won't work on digitalocean's dns either.
