### ISSUE TITLE
order_of_results

### ISSUE THREAD

**Issue by GeorgiosMastrogiannis** [geerlingguy/ansible-for-devops#127]
Hello,
Under "Discover Ansible’s parallel nature" I read:
Run the same command again, but this time, add the argument f 1 to tell Ansible to use only one fork (basically, to perform the command on each server in sequence): 

Run the same command over and over again, and it will always return results in the same order. 

but when I run it I see:
$ sudo ansible multi -a "hostname" -f 1
192.168.60.6 | CHANGED | rc=0 >>
orc-db.test

192.168.60.4 | CHANGED | rc=0 >>
orc-app1.test

192.168.60.5 | CHANGED | rc=0 >>
orc-app2.test

$ sudo ansible multi -a "hostname" -f 1
192.168.60.4 | CHANGED | rc=0 >>
orc-app1.test

192.168.60.5 | CHANGED | rc=0 >>
orc-app2.test

192.168.60.6 | CHANGED | rc=0 >>
orc-db.test

$ sudo ansible multi -a "hostname" -f 1
192.168.60.4 | CHANGED | rc=0 >>
orc-app1.test

192.168.60.5 | CHANGED | rc=0 >>
orc-app2.test

192.168.60.6 | CHANGED | rc=0 >>
orc-db.test

Any ideas?

Thank you in advance

**Comment by geerlingguy** [comment]
I'm not sure what might've happened, but I ran the test 15 times in a row, then paused 10 seconds, and ran it another 5 times, and every time it went in the order in the inventory file:

```
ansible-for-devops/orchestration $ ansible -i inventory multi -a "hostname" -f 1
192.168.60.4 | CHANGED | rc=0 >>
orc-app1.test

192.168.60.5 | CHANGED | rc=0 >>
orc-app2.test

192.168.60.6 | CHANGED | rc=0 >>
orc-db.test
```

If you run it continuously (e.g. maybe try every 5 seconds or 10 seconds) does it ever do the wrong order again? Or was it just on that first run?
