### ISSUE TITLE
Chapter 2 page 12: “(or vagrant up) the first time”

### ISSUE THREAD

**Issue by charlieok** [geerlingguy/ansible-for-devops#131]
“When you call vagrant provision (or `vagrant up`) the first time, Vagrant passes off the VM to Ansible, and tells Ansible to run a defined Ansible playbook.”

If I understand correctly I think it would make a bit more sense if “the first time” is moved inside the parenthesis:

“When you call vagrant provision (or `vagrant up` the first time), Vagrant passes off the VM to Ansible, and tells Ansible to run a defined Ansible playbook.”

**Comment by geerlingguy** [comment]
Fixed, will be in the next version of the book. Thanks!

**Comment by charlieok** [comment]
whoa, I forgot about this!
