### ISSUE TITLE
Remove Section on Accelerated Mode

### ISSUE THREAD

**Issue by evilhamsterman** [geerlingguy/ansible-for-devops#132]
Accelerated Mode was deprecated in 2.3 and removed in 2.5. It should either be removed from the book or at least noted it is not available in newer versions

**Comment by geerlingguy** [comment]
Good catch! That chapter is due for a little more updating, now that I don't see Ansible 1.x in the wild almost ever; anyone running 2.3 or earlier should have updated by now, and new installs are on 2.7 or 2.8 at least.

I've updated that part of the book, removed the Accelerated mode section, and updated some of the other wording surrounding transport methods.

Thanks for filing the issue, and I will also credit you for helping with the fixes!
