### ISSUE TITLE
typo on p. 154, it's/its

### ISSUE THREAD

**Issue by erikj** [geerlingguy/ansible-for-devops#133]
> DigitalOcean is one of the world’s top five hosting companies, and has grown rapidly since it’s founding in 2011.

Love the book, thanks!

**Comment by erikj** [comment]
Two more typos in this passage:

> Use a properly-configured firewall
>
> If you were building a secure bank vault, you wouldn’t want to **have a many** doors and windows leading into the vault. You’d instead build reinforced concrete walls, and have one or two strong metal doors.
>
> **Similarly, should** close any port not explicitly required to remain open on all your servers—whether in a DMZ in your network or open the the entire Internet.

**Comment by erikj** [comment]
> The shell command that registers the host_ip is an easy way to retrieve the IP while still letting Docker do **it’s** own virtual network management.

**Comment by geerlingguy** [comment]
That darn its/it's. I'm having flashbacks to high school english class, where that was probably the number one issue my teacher would point out :P

I even have a macro to find them all when I do full review every year or so, but they still keep slipping past. Thanks for finding these, and I'll have the fixes attributed to you in the next LeanPub version.
