### ISSUE TITLE
Book version 1.17, page 35: symlink example needs -b as written?

### ISSUE THREAD

**Issue by vedvyas** [geerlingguy/ansible-for-devops#141]
Book version 1.17, page 35:
`ansible multi -m file -a "src=/src/symlink dest=/dest/symlink owner=root group=root state=link"`
(I realize there are related issues, namely #92 and #102. There's a slightly different twist here.)

I ran this with reasonable choices for `src` and `dest` (see below). When it failed, I realized Ansible needed `-b` since the destination owner and group in this particular example are root. 

Something interesting happened while trying to recover from the failure (using Ansible 2.7.10):
1. After running the preceding example on that page, run `ansible multi -m file -a 'src=/tmp/test dest=/tmp/test2 owner=root group=root state=link'`. Fails with: 
> "msg": "chown failed: [Errno 1] Operation not permitted: '/tmp/test2'"

Result: `/tmp/test2` exists and points to `/tmp/test`, but is owned by `vagrant:vagrant` since the chown failed.

2. OK, so re-run the command with `-b`. Result: `/tmp/test` is now owned by `root:root` and `/tmp/test2` is still owned by `vagrant:vagrant`. I'm guessing that Ansible followed the existing symlink while doing its magic. 

Is this expected? I'll take a closer look at the `file` module docs.

**Comment by vedvyas** [comment]
Found this: https://github.com/ansible/ansible/issues/55909

Apparently, this behavior is due to the `follow` parameter, which defaults to `yes` for Ansible >= 2.5. I can confirm that adding `follow=no` to step 2 in the previous comment results in a symlink with correct ownership and does not change the target's ownership.

**Comment by geerlingguy** [comment]
Taking a look at this one as it relates to one of the topics written in #169 as well.

**Comment by geerlingguy** [comment]
I've re-written this example like so:

Here's how to create a symlink (set `state=link`):

    $ ansible multi -m file -a "src=/src/file dest=/dest/symlink state=link"

The `src` is the symlink's target file, and the `dest` is the path where the symlink itself should be.
