### ISSUE TITLE
missing php-imap breaks lamp-server (chapter 6)

### ISSUE THREAD

**Issue by sandipb** [geerlingguy/ansible-for-devops#143]
In chapter 6, _lamp server in nine lines_, `lamp.yml` fails to provision because of missing `php-imap` rpm. This is because the package is in epel which is not enabled.

This seems like a known issue: [ansible-role-php #133](https://github.com/geerlingguy/ansible-role-php/issues/133)

Adding the role `geerlingguy.repo-epel` at the top in `requirements.yml` and `lamp.yml` fixes the issue for me.

**Comment by geerlingguy** [comment]
Thanks! I've updated the text to include the following note within that 9-line LAMP server example:

> On RHEL servers, you should add the role `geerlingguy.repo-epel` to the `roles` list after installing it via `ansible-galaxy`, because some of the required PHP packages are only available in [EPEL](https://fedoraproject.org/wiki/EPEL).

**Comment by ngstigator** [comment]
I've installed repo-epel but still getting the "No package php-imap is available" failure. repolist as below:
```
repo id                               repo name                                                                   status
AppStream                             CentOS-8 - AppStream                                                        5,089
BaseOS                                CentOS-8 - Base                                                             2,843
*epel                                 Extra Packages for Enterprise Linux 8 - x86_64                              3,697
extras                                CentOS-8 - Extras                                                               3
```

**Comment by sandipb** [comment]
Yeah, unfortunately for Centos8 epel, there are no php-imap rpms available. There is a remi repo I found which has php version specific rpms which you might use.

Ref:
- centos7 epel : http://mirrors.syringanetworks.net/fedora-epel/7/x86_64/Packages/p/
- centos8 epel: http://fedora-epel.mirror.lstn.net/8/Everything/x86_64/Packages/p/

**Comment by ngstigator** [comment]
The centos8 epel referenced above doesn't seem to have php-imap neither, or perhaps I'm missing something :-)

**Comment by ngstigator** [comment]
I didn't really need the 'php-imap' package so it was just a matter of commenting out the variable.
```
php_packages:
  - php
  - php-cli
  - php-common
  - php-devel
  - php-fpm
  - php-gd
  #  - php-imap
  - php-ldap
  - php-mbstring
  - php-opcache
  - php-pdo
  - php-pear
  - php-pecl-apcu
  - php-xml
  - php-xmlrpc
```
