### ISSUE TITLE
NodeJS Role example: missing role subdirectory

### ISSUE THREAD

**Issue by geoand** [geerlingguy/ansible-for-devops#15]
Page 98 of the book (version 0.95) mentions that the structure for the nodejs-role example should be:

* app/
  - app.js
  - package.json
* playbook.yml
* roles/
 - nodejs/
    + meta/
       - main.yml
    + tasks/
       - main.yml

From what I can see however, the directory `ansible-for-devops/nodejs-role/` is completely missing the `roles` subdirectory.
Am I missing something obvious here or does the repository simply not contain the subdirectory due to an omission?

**Comment by geerlingguy** [comment]
Sorry it's taken so long—I'm taking a look at this now...

**Comment by geerlingguy** [comment]
Right you are! I have no idea how I missed that when I was working on chapter 6. Thanks for reporting this—and would you mind if I added a note in the 'changelog' thanking you by name (e.g. "Thanks to @geoand!")?

**Comment by geoand** [comment]
Glad to help!

Congrats again for the great book!

I of course have no problem you mentioning my name in the changelog! By all
means!
