### ISSUE TITLE
"The following packages have unmet dependencies:", " kubeadm : Depends: kubernetes-cni (= 0.6.0) but 0.7.5-00 is to be installed"]}

### ISSUE THREAD

**Issue by jendxb** [geerlingguy/ansible-for-devops#150]
Getting better, but still not working:
changed: [node2] => (item={'name': 'kubernetes-cni', 'state': 'present'})
changed: [node1] => (item={'name': 'kubernetes-cni', 'state': 'present'})
changed: [master] => (item={'name': 'kubernetes-cni', 'state': 'present'})

PLAY RECAP *********************************************************************
master                     : ok=24   changed=14   unreachable=0    failed=1    skipped=7    rescued=0    ignored=0
node1                      : ok=24   changed=14   unreachable=0    failed=1    skipped=7    rescued=0    ignored=0
node2                      : ok=24   changed=14   unreachable=0    failed=1    skipped=7    rescued=0    ignored=0

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by geerlingguy** [comment]
@jendxb - After https://github.com/geerlingguy/ansible-for-devops/pull/149 was merged, I believe this is fixed. It was a weird cross-dependency issue, I think, and it could also come back again.

**Comment by geerlingguy** [comment]
See related: https://github.com/kubernetes/kubernetes/issues/75683

**Comment by jendxb** [comment]
Just ran it and it worked 
— Jennifer
