### ISSUE TITLE
DigitalOcean Remove Non-Existant Hosts

### ISSUE THREAD

**Issue by heywoodlh** [geerlingguy/ansible-for-devops#151]
First off, thanks for such an awesome public resource!

On the DigitalOcean dynamic inventory script is there a way out-of-the-box to remove DO droplets that no longer exist? (I.E. they were destroyed)

I don't mind manually removing the hosts that don't exist anymore, but it would be awesome if that was a functionality of the script.

Thanks in advance for any help.

**Comment by geerlingguy** [comment]
If you're speaking of this script (https://raw.githubusercontent.com/ansible/ansible/devel/contrib/inventory/digital_ocean.py), that is part of the Ansible project itself (even though I have a copy of it stored in this repository), and so any changes or improvements to the dynamic inventory script should be filed against Ansible directly.

Thanks!
