### ISSUE TITLE
Ansible Common Roles Question

### ISSUE THREAD

**Issue by joshpadilla** [geerlingguy/ansible-for-devops#16]
I'm not sure if this is the right place to ask a question regarding a topic in the Ansible for DevOps book. If not I'd be happy to ask it in another more appropriate forum.

I'm wondering what the purpose of the "Common" role in Ansible is. I see it referenced often and it is usually a sibling of "webtier" and "monitoring" roles (https://docs.ansible.com/playbooks_best_practices.html). How should I conceptualize the "common" role? Do the webtier and monitoring roles share, pull or import data from the common role? Is there any way to see a detailed example of an already built common role?

**Comment by geerlingguy** [comment]
I think the main idea behind a 'common' role would be a custom role that does the same kind of 'common' setup across all your servers.

For my purposes, I do a few particular thing on *every* server, no matter what:

  - Install and configure NTP to sync time and set correct timezone.
  - Turn on and configure autoupdates
  - Add an administrative user for debugging purposes
  - Add and configure a very basic backup script and cron job

So I'd add all those tasks to a role named `common` and include that role in all my playbooks, no matter what kind of server.

The other roles (e.g. `web`, `monitoring`, etc.) would be completely separate, and would just perform tasks like install a webserver, configure monitoring software... more specific and only on certain servers.
