### ISSUE TITLE
Kubernetes example says load cluster.k8s.test but there is nothing there by default

### ISSUE THREAD

**Issue by jendxb** [geerlingguy/ansible-for-devops#164]
After the cluster successfully was created, http://cluster.k8s.test/ did not show anything, with a "refused" error

**Comment by geerlingguy** [comment]
Ah, I'm guessing you're following the directions in this repository, here: https://github.com/geerlingguy/ansible-for-devops/tree/master/kubernetes

If so, the way they are currently written does not account for actually deploying applications into the Kubernetes cluster which you can test and access. That is covered in detail in the Ansible for DevOps book, chapter 14.

However, I'm updating the README to describe how to deploy the simplest Nginx example into the cluster so you can access it and make sure everything's working correctly. I'll close this issue once I push that fix to the repository.

**Comment by jendxb** [comment]
That’s great!
Thank you 🙏 
Jennifer
