### ISSUE TITLE
`path` in requirements.yml is not working?

### ISSUE THREAD

**Issue by 7php** [geerlingguy/ansible-for-devops#172]
Hi @geerlingguy 
I am trying to load my roles from a private gitlab and hence using `requirements.yml`.
I have been able to do it but I note the following:

1) `path` in `requirements.yml` is not working. 
By not working, I mean it is not saving the role at the path, but instead at the default system path: `~/.ansible/roles`

As a work-around (not sure if that's the way now), I am defining `roles_path` in my custom `ansible.cfg` within my working ansible folder.

2) Also, I note that I need to absolutely have an additional attribute `scm: git` with `requirements.yml` - something which is missing in the book. If that is not included I get the error: "_[WARNING]: - role_name was NOT installed successfully: the file downloaded was not a tar.gz_"

Any feedback on this please?

**Comment by geerlingguy** [comment]
It looks like you're correct; the example in the book worked in the late 1.x era, but some things with `requirements.yml` files changed in 2.0 and the examples became outdated.

I will be fixing them, but a very strange thing is going on; I created a directory, and inside two files:

ansible.cfg

```
[defaults]
roles_path = ./
```

requirements.yml

```
---
# From GitHub, to a given path, with a custom name and version.
- src: https://github.com/geerlingguy/ansible-role-passenger
  name: geerlingguy.passenger
  version: 1.2.0
```

When I run:

    ansible-galaxy install -r requirements.yml

I get:

```
ERROR! No roles found in file: requirements.yml
```

**Comment by geerlingguy** [comment]
With `-vvvv`:

```
$ ansible-galaxy -vvvv install -r requirements.yml 
ansible-galaxy 2.8.5
  config file = /Users/jgeerling/Downloads/ansitest/ansible.cfg
  configured module search path = [u'/Users/jgeerling/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible-galaxy
  python version = 2.7.16 (default, Apr 12 2019, 15:32:40) [GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.3)]
Using /Users/jgeerling/Downloads/ansitest/ansible.cfg as config file
Opened /Users/jgeerling/.ansible_galaxy
ERROR! No roles found in file: requirements.yml
```

**Comment by geerlingguy** [comment]
Nevermind... that file was, in fact, empty. I was messing around with a `requirements.yml` file in some random place on my drive and not the one I was actually testing 😅

**Comment by geerlingguy** [comment]
Updated example going into the book's next revision:

    ---
    # From Ansible Galaxy, latest version.
    - src: geerlingguy.firewall
    
    # From Ansible Galaxy, specifying the version.
    - src: geerlingguy.php
      version: 3.5.1
    
    # From GitHub, with a custom name and version.
    - src: https://github.com/geerlingguy/ansible-role-passenger
      name: passenger
      version: 1.2.0
    
    # From a web server, with a custom name.
    - src: https://www.example.com/ansible/roles/my-role-name.tar.gz
      name: my-role
