### ISSUE TITLE
A few stanzas on "when", "why", and "how" of interaction with Terraform?

### ISSUE THREAD

**Issue by rmohanx** [geerlingguy/ansible-for-devops#175]
Great for synergy in this burgeoning community.

**Comment by geerlingguy** [comment]
Was there a particular section where you wanted to see more detail?

I specifically avoid spending too much time on integration with specific tools like CloudFormation and Terraform, mostly because they can be incredibly daunting for someone new to automation, and I don't know if I'd have the time to go deep enough to say anything more meaningful in _this_ book.

(Note that I'm probably going to have more detail on both TF and CF in my Ansible for Kubernetes, book, however.)

**Comment by rmohanx** [comment]
Hmmm. This point is very well taken.

By the time one might say something truly useful and not commonplace, you'd
already be speaking at such a deep level of integration or application that
your target audience is very limited (and may well have educated themselves
already.)

I should withdraw the suggestion in view of this.

Pivoting here, and just "thinking out loud":

As an extreme Ansible newbie I've been doing a little bit of reading. One
area that doesn't seem much covered in the intro stuff yet would be more
generally useful is a some discussion around linear versus free strategy,
and how to smartly leverage serial vs. parallel processing.

It seems the default Ansible model is serial processing inside an implicit
inventory loop, but one could make an argument that certain use cases
(network devices, IoT fleets, Etc) would benefit from optimizing parallel,
async processing. Just a thought...

Thanks for the book,
All good wishes,
Ross

**Comment by geerlingguy** [comment]
I actually have a TODO in my notes to add a section on linear vs. free, and would probably spend a little more time discussing parallelization/async there too (there is a little mention in a couple places of async tasks, but not much).

Regarding networking, that's one area that I generally can't speak to, so I have avoided it in my book (along with any kind of advanced Windows usage—at least for now).

**Comment by rmohanx** [comment]
Looking forward to it!

Thank you!

**Comment by alabaojo** [comment]
Alaba Ojo <ojalst@gmail.com> schrieb am Fr., 4. Okt. 2019, 12:22:

**Comment by alabaojo** [comment]
Ich. habe

Jeff Geerling <notifications@github.com> schrieb am Mi., 2. Okt. 2019,
23:56:
