### ISSUE TITLE
[1.20] Not corrected order of paragraph: Chapter 4 -> Real-world playbook: CentOS Node.js app server -> p.57

### ISSUE THREAD

**Issue by rusnino** [geerlingguy/ansible-for-devops#177]
I think rpm_key import should be before adding this repository.

> 1. We can install extra yum repositories using the yum module. Just pass in the
URL to the repo .rpm file, and Ansible will take care of the rest.

> 2. rpm_key is a very simple Ansible module that takes and imports an RPM key
from a URL or file, or the key id of a key that is already present, and ensures
the key is either present or absent (the state parameter). We’re importing one
key, for Remi’s repository.

**Comment by geerlingguy** [comment]
Wow, I can't believe I did that; I must've been working on the formatting and flipped those paragraphs. Thanks for filing the issue, and I'll have this fix done in the next version of the book!
