### ISSUE TITLE
[1.20] p. 49, item 6:yntax description does not match playbook

### ISSUE THREAD

**Issue by dirks** [geerlingguy/ansible-for-devops#179]
In the description it says:

```
you use the syntax {var1: value, var2: value} to define each element
```

In the playbook the syntax is
```
- src: httpd.conf
  dest: /etc/httpd/conf/httpd.conf
```

While obviously both is valid to describe a dict, it is confusing to use the two different syntax styles here – at least without explanation.

**Comment by geerlingguy** [comment]
You're correct; I think I did that to avoid writing a code sample in a double-nested list (translation: being lazy and avoiding complex markdown formatting testing). So I've corrected that and this is how it will look in the next version:

<img width="470" alt="Screen Shot 2019-12-02 at 5 03 38 PM" src="https://user-images.githubusercontent.com/481677/70002568-02e93580-1526-11ea-800d-adece9291c0b.png">

Thanks for raising the issue, it will be fixed on all platforms soon!
