### ISSUE TITLE
[1.20] p. 78, unused handler in playbook

### ISSUE THREAD

**Issue by dirks** [geerlingguy/ansible-for-devops#181]
The handler you define for the solr playbook is never called (no notify) in the playbook.

**Comment by geerlingguy** [comment]
You're quite correct; in the initial version of that playbook, I believe I used the handler during the more manual installation process. Nowadays, Solr ships with its own installer, and I only need to make sure the service is started after the installer runs... therefore the unnecessary handler. I've removed it (see above commit) and that will be in the next version of the book.

Note that the handler may be helpful in some people's playbooks, however, especially if they are doing things like core management on-the-fly. But for the purposes of the book, it was just extra code, and [YAGNI](https://martinfowler.com/bliki/Yagni.html).
