### ISSUE TITLE
[1.20] repository solr playbook contains unused template

### ISSUE THREAD

**Issue by dirks** [geerlingguy/ansible-for-devops#182]
There is a template in https://github.com/geerlingguy/ansible-for-devops/tree/1.20/solr/provisioning/templates

Neither in the book nor in the [repo playbook](https://github.com/geerlingguy/ansible-for-devops/blob/1.20/solr/provisioning/playbook.yml) the  template is used.

**Comment by geerlingguy** [comment]
Interesting! Probably an artifact from the time when the example was used for Solr 3.x back when the book was originally being written. I'll take a look on my next book update.

**Comment by geerlingguy** [comment]
Fixed in above commit. Must've been a remnant from the old days.
