### ISSUE TITLE
ansible-playbook : remote user parameter (Chapitre 4 : "Setting user and sudo options with ansible-playbook")

### ISSUE THREAD

**Issue by peurKe** [geerlingguy/ansible-for-devops#185]
This command return an error with the --remote-user parameter :
```
$ ansible-playbook playbook.yml --remote-user=johndoe
Usage: ansible-playbook [options] playbook.yml [playbook2 ...]
ansible-playbook: error: no such option: --remote-user
```

In the ansible-playbook help page, the remote user parameter is **-u** or **--user** :
```
$ ansible-playbook -h | grep -i remote_user
    -u REMOTE_USER, --user=REMOTE_USER
```

**Comment by geerlingguy** [comment]
Yikes, thanks for filing this issue! I believe that flag actually changed at some point in the past few years—but it should be good to go in the LeanPub edition in a few minutes, and this fix will be bundled into the next batch of updates in other stores soon.
