### ISSUE TITLE
old molecule url

### ISSUE THREAD

**Issue by apatard** [geerlingguy/ansible-for-devops#189]
When looking briefly at the new version of the book, I noticed that in chapter 11, the molecule url is the old one. It is pointing to https://github.com/metacloud/molecule but theses days, molecule is at https://github.com/ansible/molecule.
(thanks for the book btw !)

**Comment by geerlingguy** [comment]
Good catch! I will make sure to update the URL, even if I don't get to fully incorporating a Molecule example in the next version of the book (see #101).

**Comment by geerlingguy** [comment]
This has been fixed in my manuscript; it should be updated on LeanPub very soon!

**Comment by ssbarnea** [comment]
Funny aspect is that we moved it again few days ago :)

**Comment by geerlingguy** [comment]
Gah! I shall fix that again :D

**Comment by ssbarnea** [comment]
Also expect other things to break as I will release v3 this month, with few minor but breaking changes, mostly making the tool easier to use.

**Comment by geerlingguy** [comment]
@ssbarnea no problem! This gives me an excuse to procrastinate on writing the final content until next month :D
