### ISSUE TITLE
nodejs: forever is not installed

### ISSUE THREAD

**Issue by lihop** [geerlingguy/ansible-for-devops#19]
Following the nodejs example I get the error:
```
TASK [Check list of running Node.js apps.] *************************************
fatal: [default]: FAILED! => {"changed": false, "cmd": "forever list", "failed": true, "msg": "[Errno 2] No such file or directory", "rc": 2}
```
Further invocations of `vagrant provision` produce the same error and interestingly the "Install Forever (to run our Node.js app)" task is marked as changed every time. I logged into the machine and found out forever wasn't being installed at all.

Changing the "Install Forever" task so that `state=present` rather than `state=latest` fixes the problem.
However, my understanding is that `state=latest` should also ensure the package is installed so maybe this is a bug in the ansible npm module?

I am using Ansible version: 2.0.0.

**Comment by geerlingguy** [comment]
@lihop - Yes, `state=present` should be preferred, and should work fine... it looks like there's a chance the `npm` module has a bug in 2.0.0. Note that it's still pre-release software—you may want to report this bug in the Ansible project's queue.

**Comment by lihop** [comment]
Thanks for confirming @geerlingguy. I've downgraded to ansible 1.9.4 and the playbook runs fine as is. I was using Ansible 2.0.0 because that is the version shown in the "Installing Ansible" section of the book. I didn't realize the software was pre-release, so I will look into making a bug report.

**Comment by lihop** [comment]
Looks like the bug has already been reported here: ansible/ansible-modules-extras#1375

**Comment by geerlingguy** [comment]
Thanks for the update!
