### ISSUE TITLE
Link to AWS Dynamic Inventory is wrong.

### ISSUE THREAD

**Issue by goagex** [geerlingguy/ansible-for-devops#194]
Hi!

Link to AWS Dynamic Inventory is wrong.

In book: https://raw.githubusercontent.com/ansible/ansible/devel/plugins/inventory/ec2.py

Current link: https://raw.githubusercontent.com/ansible/ansible/devel/contrib/inventory/ec2.py

Kind regards //
goagex

**Comment by geerlingguy** [comment]
Thanks! I'll make sure to update the link in the next version of the book.

**Comment by geerlingguy** [comment]
I have updated this in the book's manuscript and will make sure it's in the next batch of changes delivered to LeanPub!
