### ISSUE TITLE
Jinja2 is being renamed to 'Jinja'

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-for-devops#197]
See:

  - https://github.com/ansible/ansible/issues/66163
  - https://github.com/pallets/jinja/pull/1121

In the book, there are multiple references to "Jinja2", which I should update and rename to just "Jinja".

**Comment by geerlingguy** [comment]
One interesting side effect... all the stuff in Ansible (including my book and most of my example playbooks and such) use the `.j2` extension to indicate 'Jinja2' templates... I'm probably going to leave that alone for now, since that's a more seismic change—but it looks like according to a [recent docs change](https://github.com/pallets/jinja/pull/1083/files#diff-0f54a58b39617a700a0b750e7a8bf07eR60-R71), the `.jinja` extension may be the recommended Jinja-specific file extension.

**Comment by geerlingguy** [comment]
Fixed the plain text references, and opened a follow-up for changing file names: https://github.com/geerlingguy/ansible-for-devops/issues/199

**Comment by davidism** [comment]
Just a heads up, since I saw this linked from the Jinja issue: We're no longer planning to rename the imports, they will remain `jinja2`.
