### ISSUE TITLE
Update link in Chapter 9 deployment strategies

### ISSUE THREAD

**Issue by kevinbowen777** [geerlingguy/ansible-for-devops#204]
Page 240: The repo link points to https://github.com/geerlingguy/demo-rails-app when it appears that the repo is already present in the deployments/ directory. Are they different?

General comment: If the book is going to reference the files in this repository, it would be helpful to indicate the specific repo directory names at the beginning of the chapters instead of just referencing the overall repo at the end of the examples provided in the text. It has been mildly confusing, at times, to correlate the exact repo used in the text.

**Comment by geerlingguy** [comment]
@kevinbowen777 - For both of these comments, it's a bit of a tricky line to walk; I try to write the entire book from the perspective of the reader being detached from GitHub / this project. So all examples contain everything needed to run through the whole example using nothing but the book, and generally I only post a link to a relevant example at the _end_ of that example, to reduce the noise.

For someone like you who would like to be able to look at the examples in this repo alongside the text, I have an issue (https://github.com/geerlingguy/ansible-for-devops/issues/140) open that should make the mapping of examples in this repo to text chapters/sections a bit easier.

I'm already doing that by default in my Ansible for Kubernetes repo (see https://github.com/geerlingguy/ansible-for-kubernetes), and I'll try to make sure that list is up to date in this repo too, once I get to the linked issue.

**Comment by geerlingguy** [comment]
Oh also regarding the deployments/ directory—that repo should not be present by default (see https://github.com/geerlingguy/ansible-for-devops/tree/master/deployments).
