### ISSUE TITLE
Chapter 9 - Zero-downtime multi-server deployments

### ISSUE THREAD

**Issue by kevinbowen777** [geerlingguy/ansible-for-devops#205]
On page 254, the reader is pointed to the repo https://github.com/geerlingguy/demo-nodejs-api
 while the README points the reader _back_ to this repo and the deployments-rolling/ directory.

**Comment by geerlingguy** [comment]
So to reduce the confusion I think you're seeing:

  - https://github.com/geerlingguy/demo-nodejs-api — this repository contains the reference app that will be deployed in the book's example, using the playbook in the `deployments-rolling/` directory.
  - [`deployments-rolling/`](https://github.com/geerlingguy/ansible-for-devops/tree/master/deployments-rolling) — this folder contains the Ansible playbook example that will deploy the demo-nodejs-api app (which is maintained separate from this repository).
