### ISSUE TITLE
Facter and Ohai references

### ISSUE THREAD

**Issue by kevinbowen777** [geerlingguy/ansible-for-devops#208]
pg 97 has Footnotes for Facter and Ohai but they are initially mentioned on pg. 89.

For some reason, the Facter link goes to the open issues bugs page https://tickets.puppetlabs.com/browse/FACT rather than a definition of what Facter is or how to install it.

Perhaps it should link to https://puppet.com/docs/facter/3.11/index.html instead of the Facter bug queue which doesn't help the reader.

The Ohai link on pg 97 goes to a documentation page which seems correct.

**Comment by geerlingguy** [comment]
@kevinbowen777 - Thanks for bringing this to my attention; those references were all over the board, and the part in the 'Playbook Variables' was just plain wrong—ansible doesn't need Facter or Ohai installed at all to get the main ansible facts when a playbook is run!

I've cleaned up that section and also updated the link for the Facter docs to https://puppet.com/docs/puppet/latest/facter.html (and the link for Ohai docs to https://docs.chef.io/ohai/). The changes will be in the next batch of updates to the book.
