### ISSUE TITLE
Use of `sudo ansible-galaxy install` vs. `ansible-galaxy install`

### ISSUE THREAD

**Issue by kevinbowen777** [geerlingguy/ansible-for-devops#209]
On page 258, one is instructed to install the requirements.yml  with the command `ansible-galaxy install -r requirements.yml`. 
However, on page 269, the instructions say to run the command `sudo ansible-galaxy install -r requirements.yml`

**Comment by geerlingguy** [comment]
Oops! Good catch, I have fixed that in the text and it will be in the next batch of updates.
