### ISSUE TITLE
Chapter 10 references old Ubuntu repos.

### ISSUE THREAD

**Issue by kevinbowen777** [geerlingguy/ansible-for-devops#210]
In the section Automating updates for Debian-based systems, Page 291:

1 # File: /etc/apt/apt.conf.d/50unattended-upgrades
2 Unattended-Upgrade::Automatic-Reboot "false";
3
4 Unattended-Upgrade::Allowed-Origins {
5 "Ubuntu lucid-security";
6 // "Ubuntu lucid-updates";
7 };

Lucid is Ubuntu's 10.04 release. For 18.04, this should be replaced with bionic.

**Comment by geerlingguy** [comment]
Yikes, you're right. I must've written that example a _very_ long time ago.

The latest version has placeholders so it should be like:

```
# File: /etc/apt/apt.conf.d/50unattended-upgrades
Unattended-Upgrade::Automatic-Reboot "false";

Unattended-Upgrade::DevRelease "false";

Unattended-Upgrade::Allowed-Origins {
        "${distro_id}:${distro_codename}";
        "${distro_id}:${distro_codename}-security";
        "${distro_id}ESM:${distro_codename}";
//      "${distro_id}:${distro_codename}-updates";
//      "${distro_id}:${distro_codename}-proposed";
//      "${distro_id}:${distro_codename}-backports";
};
```

**Comment by geerlingguy** [comment]
This has been fixed in the book (as well as the RHEL section which needed to note that it's `dnf-automatic` in RHEL 8 instead of `yum-cron`). It will be in the next batch of updates. Thanks!
