### ISSUE TITLE
Chapter 11: Update Ansible Tower guide and discuss AWX

### ISSUE THREAD

**Issue by kevinbowen777** [geerlingguy/ansible-for-devops#212]
The instructions for installing Ansible Tower in Chapter 11 on page 303.

Says to run the command `vagrant init tower http://vms.ansible.com/ansible-tower-2.3.1-\
virtualbox.box'

This box is broken and fails to build halting on the following error:

> 
> The following SSH command responded with a non-zero exit status.
> Vagrant assumes that this means the command failed!
> 
> yum install -y centos-release

I managed to find a working Tower box by running `vagrant init ansible/tower` and managed to get an instance installed. But, then I needed to request a license from RedHat. I followed the indicated links and supposedly requested a license. However, I had to wait an hour and only received a link from RedHat to download a tar.tz for Tower. No license was ever provided.

**Comment by geerlingguy** [comment]
@kevinbowen777 - Yeah, I really need to get my Ansible Tower example updated, because it's a bit outdated at this point. I normally run Tower in a Kubernetes cluster now, or run AWX sometimes in a Docker environment using AWX's included Docker Compose, just because it's easier for quickly testing things out.

I'll leave this issue open as a reminder to update chapter 11 soon—it doesn't even mention the open source AWX project right now!

**Comment by geerlingguy** [comment]
For the short term, I'm adding a notice on the Tower section in Chapter 11 that mentions the example is not quite up to date and I'm working on it. That's better than misleading people through half the broken example!

**Comment by geerlingguy** [comment]
Bumped into https://github.com/ansible/awx/issues/7699 while working on this. It seems like I can't get AWX to cleanly install either at devel or 13.0.0 on my Mac, but some people report it installs on other systems okay.

**Comment by geerlingguy** [comment]
I'm also incorporating this tweet (https://twitter.com/geerlingguy/status/906188577612021761?s=20) into the book:

> *What's up with the irate potato?* Apparently it's an inside joke. Sometimes when using AWX you'll see the 'AWX with Wings' logo, which as far as I can tell has its roots as one of the original logos of the 'AnsibleWorks' organization that eventually became Ansible, Inc. and is part of Red Hat today. But other times you'll see the Angry Spud. 'Angry Spud,' 'Rage Tater,' and 'The Starchy Miracle' are some internal nicknames for our potato friend.
>
> Like Ansible's tendency to wrap output in cowsay if you have it installed, some of these strange but fun quirks make using Ansible tools more fun by giving them personality---at least in the author's opinion.

**Comment by geerlingguy** [comment]
This has been updated in the manuscript and will be available in the next book revision. Thanks again for raising the issue!
