### ISSUE TITLE
[1.21] chapter 4 drupal: text and playbook inconsistent

### ISSUE THREAD

**Issue by dirks** [geerlingguy/ansible-for-devops#213]
858e10d1985a916d5a8b5b54cf58a4bcfdb1f817 introduced an inconsistency between text and playbook. The text describes the playbook before this commit:

> The final two tasks set permissions …

**Comment by geerlingguy** [comment]
Oops! Great catch, don't know how I missed that in the last batch of updates. I'll have this fix in the next batch.
