### ISSUE TITLE
ver 1.21: ansible command using -s instead of -b

### ISSUE THREAD

**Issue by hatchmount77** [geerlingguy/ansible-for-devops#216]
On page 231 of the version 1.21 leanpub PDF the command: ansible gluster -i inventory -a "gluster peer status" -s should end in -b as well as the similar commands that follow it. I noticed that it was annotated as fixed in the Eratta version 1.13-1.14 notes #4. Regression issue? 

Love your book!

**Comment by geerlingguy** [comment]
Good catch! Just to make sure I did a regex search on the book's text for `-s[^a-zA-Z]`, and those were the only two occurrences. Thanks for finding this, it'll be fixed (and attributed to you!) in the next version of the book.
