### ISSUE TITLE
Book Errata: Page 8, "ansible example -a "free -m" -u [username]" command

### ISSUE THREAD

**Issue by ew0k** [geerlingguy/ansible-for-devops#217]
### The Problem
On the top of page 8 you give the following command: `ansible example -a "free -m" -u [username]`. The text below it states: 

> "In this example, we quickly see memory usage (in a human readable format) on all the servers (for now, just one) in the example group."

Below is the output of the command in my environment:
![image](https://user-images.githubusercontent.com/22973164/76996746-6c038600-6928-11ea-8ccc-351b7b3482df.png)
To my eye, the output does not appear to be human-readable. 

### The Solution
For the command output to be human-readable, I believe you have the wrong flag and instead the command should be the following: `ansible example -a "free -h" -u [username]`. Below is the output of the above command:
![image](https://user-images.githubusercontent.com/22973164/76996867-a836e680-6928-11ea-9ebd-a6598cb356c6.png)
Also, I'm not sure if you care about this or not, but grammatically "human readable" might need to be changed to "human-readable" (or at least says Grammarly lol). 

### My Setup
I am using version 1.21 of the book and version 2.9.6 of ansible. I have a Ubuntu 18.04 Desktop and Ubuntu 18.04 Server VM setup for testing.

**Comment by geerlingguy** [comment]
Thanks for the detailed issue! You're correct on both counts, and I'll have these fixed up in the next batch of updates for the book.
