### ISSUE TITLE
Chapter 4: Drupal - template file issue causes issues in earlier steps

### ISSUE THREAD

**Issue by searsaw** [geerlingguy/ansible-for-devops#218]
When going through the Drupal example, I copied and pasted the Apache2 virtualhost into the file from the PDF. It removed alot of the spaces and newlines in doing so. So I added them back in, but I missed one in the first line. `<VirtualHost*:80>`. I missed a space after `VirtualHost`. This  caused it to error on this play when trying to restart Apache. Once I fixed it and provisioned it again, it then kept errorring when trying to restart Apache on the play attempting to enable the rewrite module. The only way I could fix it was to destroy the Vagrant host and recreate it. Not the end of the world but something to be aware of.

**Comment by MacFlurry** [comment]
Hi, avoid copy paste from pdf, source code is on @geerlingguy github, so just grab it right there or clone the repo.
PS: don't forget to close this `non` issue :-) 
Regards

**Comment by geerlingguy** [comment]
@searsaw - Thanks for filing the issue! And yeah, copying and pasting from the PDF can trip you up from time to time, and the best way to fix that is to look at the examples directly in this repo, and to do a full `vagrant destroy -f` to wipe out the messed up machine (often that's easier than trying to figure out exactly how to get back into a happy state).
