### ISSUE TITLE
Don't use sudo when installing Ansible via pip

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-for-devops#219]
There are a couple examples in the book where `sudo` is used to install Ansible via Pip. That... shouldn't normally be required, and I don't remember why I had it that way in the early editions. It kind of slipped through my many reviews over the years, but _typically_ you shouldn't need to install Ansible with `sudo`.

**Comment by geerlingguy** [comment]
I've fixed this in chapter 1 and chapter 8, but will leave updating the windows appendix to related issue https://github.com/geerlingguy/ansible-for-devops/issues/291

**Comment by itzikhoch** [comment]
Please see issue #396 I've just added. It might explain the original reason you have recommended to use sudo
