### ISSUE TITLE
Add 'Your first Ansible playbook' example to this repo, update it

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-for-devops#220]
Right now it's just in the book (page 13 of version 2.20), and it currently installs ntp and gets it running on a CentOS 7 VM in VirtualBox, managed by Vagrant.

The playbook should be in this repository (with a mapping from the README), and it should be tested like any other playbook.

It would be better to use a more modern example, maybe replace ntp/ntpd with chrony? Or use something else that is pretty universal.

**Comment by geerlingguy** [comment]
There's also a multi-server orchestration example in Chapter 3 that sets up ntpd that should instead set up chronyd.

**Comment by deepak-malhotra** [comment]
The problem with this example is that .vagrantfile syntax assumes that its a Linux environment. I have virtualbox installed on Windows with Ubuntu 18.04 running in WSL2.  Thats why I am stuck as I get an error when I run "vagrant provision" .   

What options do I have ?  I reckon if somehow I could tell vagrant to use ansible installed in WSL Ubuntu or use Ansible installed in the new VM itself ?

**Comment by geerlingguy** [comment]
@deepak-malhotra - For Windows, you can use Vagrant installed in Windows, and in the Vagrantfile itself, use the `ansible_local` provisioner (instead of `ansible`) in that section; see documentation here: https://www.vagrantup.com/docs/provisioning/ansible_local.html
