### ISSUE TITLE
[1.22] p. 49, point 4.

### ISSUE THREAD

**Issue by mkrawczuk** [geerlingguy/ansible-for-devops#222]
It says
> 4. The fifth line, tasks: , tells Ansible that what follows is a list of tasks to run as
> part of this _playbook_.

Should probably say
> 4. The fifth line, tasks: , tells Ansible that what follows is a list of tasks to run as
> part of this _play_.

Love the book. Keep up the good job!

**Comment by geerlingguy** [comment]
Right you are! This fix will be in the next version of the book.

**Comment by geerlingguy** [comment]
(the next version will be 1.23, out soon!)
