### ISSUE TITLE
[1.22] p.311 Jenkins login not provided

### ISSUE THREAD

**Issue by lustoerk** [geerlingguy/ansible-for-devops#226]
The Jenkins credentials are missing in the section "Create a Jenkins job to run an Ansible Playbook" 
They are admin/admin (as defined in the roles` defaults)

**Comment by geerlingguy** [comment]
Ah, good point. I believe when I initially created that example I _didn't_ have a default admin login (gasp!) on the `geerlingguy.jenkins` role. I've added a note about the login in the text which should help future readers, and will attribute you for the fix. This will be in version 1.23 of the book. Thanks again!
