### ISSUE TITLE
[1.22] p.120 include -> import

### ISSUE THREAD

**Issue by mkrawczuk** [geerlingguy/ansible-for-devops#228]
In chapter 6, 'Imports' section, in the sentence

> Tasks can easily be included in a similar way. In the tasks: section of your playbook,
> you can add import_tasks directives like so:

I find using "included" an unlucky choice of words, since it may introduce some confusion with the `include_tasks` directive that follows. Maybe "added", or even "imported" would be a good alternative.

**Comment by MacFlurry** [comment]
I don't think it's misleading.
look a the synopis of `include_tasks` : 
Synopsis:

> **Includes** a file with a list of tasks to be executed in the current playbook.

They could have used another synonym, but the word include is appropriate.

**Comment by geerlingguy** [comment]
Yeah, this is tricky—I don't know how many hours I've spent fiddling with the text around `include_tasks` vs `import_tasks`, and I confuse even myself a thousand times a month when I'm trying to remember which one behaves which way... In one sense I wish the Ansible team just kept the `static` directive and didn't make it include vs. import.

But as @MacFlurry mentions, the word is not incorrect, and the rewording to say added or imported doesn't read as well—especially after all the previous (and future) talk comparing including files to including vars files and playbooks...

The main difficulty for me is from a software background, the two words `include` and `import` are 99% of the time perfect synonyms, with often the most insignificant of differences. In Ansible there are many situations where they mean nothing different but a few where they are very different... but it's always hard to talk about it.

I'm going to close this as a 'won't do', but I will continue to stew over how to explain includes and imports in a way that doesn't muddy the waters further.
