### ISSUE TITLE
Ansible in WSL filesystem permission issues

### ISSUE THREAD

**Issue by misse** [geerlingguy/ansible-for-devops#234]
Hi,

On the first exercise while running vagrant and ansible within WSL (ubuntu 18.04) I ran into the problem that ansible refused to use vagrant ssh keys, due to them being in the mounted ntfs partition and had too open file permissions:

```

TASK [Gathering Facts] *********************************************************

fatal: [default]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Warning: Permanently added '[127.0.0.1]:2222' (ECDSA) to the list of known hosts.
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
WARNING: UNPROTECTED PRIVATE KEY FILE!          
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

Permissions 0777 for '/mnt/c/Users/Martin Bergman/git/ansible-for-devops/1/.vagrant/machines/default/virtualbox/private_key' are too open.

It is required that your private key files are NOT accessible by others.\r\nThis private key will be ignored.

Load key \"/mnt/c/Users/Martin Bergman/git/ansible-for-devops/1/.vagrant/machines/default/virtualbox/private_key\": bad permissions
vagrant@127.0.0.1: Permission denied (publickey,password). "unreachable": true}

```

I solved it by creating /etc/wsl.conf with the following content:
```
# Enable extra metadata options by default
[automount]
enabled = true
root = /mnt/
options = "metadata,umask=77,fmask=11"
mountFsTab = false
```

and running `Restart-Service -Name "LxssManager"` within an elevated powershell

**Comment by geerlingguy** [comment]
@misse - Thanks for posting this solution here! I know there are a number of people (especially recently) who have been working on using Ansible within WSL and Windows, and I hope this helps them when they search for the same issue.

At some point, likely after WSL 2 is released, I plan on rewriting my 'Appendix A' to figure out a better way to make it seamless running Ansible with Windows (and maybe integrated with Vagrant, too), but until then I'll keep things as is and hope that people can figure out these kinds of solutions (so thanks again for posting, now it's indexed in Google and GitHub Search!).

**Comment by AMoghrabi** [comment]
Thanks a lot @misse, really helpful and I'm glad I came across this as I've been struggling for a couple of days now trying to solve this problem. 

Have a great day.

**Comment by Slowbad** [comment]
@AMoghrabi You can see the configuration options for wsl.conf [here](https://devblogs.microsoft.com/commandline/automatically-configuring-wsl/). The automount section are settings to call `mount` when wsl is started. The options settings is the same as what is passed to the -o flag to that command.

umask lets you define the permission mask for all files and folders that are mounted. fmask is for files. dmask, which isn't present here, is for folders. The numbers aren't the permissions directly but what gets subtracted from 7 to get the permission. So here the umask, 77 or 077, means that the owner gets full permissions and with groups and everyone else getting nothing. This would equivalent equivalent to chmod 700. The fmask, 11 or 011, means files get full permissions and with groups and everyone else getting read and write permissions. I think umask gets applied after fmask however and so everything is effectively wide open to the owner only.

A big thank you to @misse for this. Vagrant's documentation was implying that the permissions issue would be handled but I couldn't get `vagrant ssh` or `vagrant provision` to work without this configuration change.
