### ISSUE TITLE
[1.21] p35 - Create directories and files

### ISSUE THREAD

**Issue by m-kratochvil** [geerlingguy/ansible-for-devops#236]
In paragraph **Create directories and files** it says:

> You can use the file module to create files and directories (like touch)

I believe the file module works only with existing files, it can't be used to create new files.
It works for directories, but not for files.

**Comment by MacFlurry** [comment]
yes you're right @m-kratochvil 
the documentation says: 

> the file will be modified but will NOT be created if it does not exist; see the touch value or the copy or template module if you want that behavior.

Regards,

MacFlurry

**Comment by geerlingguy** [comment]
@m-kratochvil - Technically the `file` module _can_ create new files, using `state=touch`:

> If `touch` (new in 1.4), an empty file will be created if the `path` does not exist, while an existing file or directory will receive updated file access and modification times (similar to the way `touch` works from the command line).

I use it for this purpose from time to time.

Closing this issue as I don't think it's misleading, but please let me know if I'm misinterpreting the report.

**Comment by m-kratochvil** [comment]
> If `touch` (new in 1.4), an empty file will be created if the `path` does not exist, while an existing file or directory will receive updated file access and modification times (similar to the way `touch` works from the command line).

right! I missed that option, thanks for pointing it out..
