### ISSUE TITLE
Ansible 2.0 ready?

### ISSUE THREAD

**Issue by neduma** [geerlingguy/ansible-for-devops#24]
Wondering all the play books updated for 2.0 version?.

**Comment by geerlingguy** [comment]
They have all been updated, yes; a few of the roles may still throw a couple warnings as I'm working through all 70+ that I maintain and making sure they use the proper modules in Ansible 2.0.

I'm going to be doing a more thorough update soon, though, and the examples will be tweaked to be more efficient using new Ansible 2.0 features (like the new `package` module).

If you find any specific issues or warnings, please feel free to open up an issue with the error in question.
