### ISSUE TITLE
geerlingguy.mysql role _ replication config _ server-id identical on master and slave.

### ISSUE THREAD

**Issue by MacFlurry** [geerlingguy/ansible-for-devops#241]
Hello @geerlingguy ,

I hope you're doing well.

running the `lamp-infrastructure`, it failed on replication configuration..
I've investigated a little bit on the db2 slave server, it seems that the value:
`server-id` is **identical** to the master.

actually, looking at your mysql role: I see that there is no distinction between a master `server-id` and a slave `server-id`: maybe I'm wrong when I say that.
```templates/my.cnf.j2
{% if mysql_replication_master %}
# Replication
server-id = {{ mysql_server_id }}
```
So by changing the value of the `server-id` to another value than the master on the `my.cnf` file and restarting the mariadb service, the replication works back.

thanks for your feedback;
MacFlurry 

ansible 2.9.6

**Comment by MacFlurry** [comment]
Wouldn't it be preferable to have a : 
`master.cnf.j2` by default and a `slave.cnf.j2` to load, 
if the replication option is **enabled**, in order to have different `server-id`s?

Regards,
MacFlurry

**Comment by rantanevich** [comment]
Hello.

I've just faced this problem. 
I think if we add `mysql_server_id=1` for master and `mysql_server_id=2` for slave variables in inventory file, it will be a better solution. 

https://github.com/geerlingguy/ansible-for-devops/blob/c78c5d8cc6aee11e9b87ba07a78948cf3cf7230c/lamp-infrastructure/inventories/vagrant/inventory#L11-L13

**Comment by geerlingguy** [comment]
So... this was actually related to a couple different issues, not the least of which was https://github.com/geerlingguy/ansible-role-mysql/issues/401, which was caused a bit ago by my accidental breakage of replication tasks trying to fix up a syntax issue ansible-lint identified 🙄

I also revamped that example quite a bit in #229 so it should work correctly now across vagrant, digitalocean (and soon, once I make sure it's updated in #304, in aws).

I can confirm that using all the defaults in this repository it is correctly setting up replication again. Sorry about that, and thanks for filing the issue!
