### ISSUE TITLE
Permission denied error while installation

### ISSUE THREAD

**Issue by kotireddy555** [geerlingguy/ansible-for-devops#242]
fatal: [192.168.66.66]: FAILED! => {"changed": false, "cmd": "/tmp/solr-8.5.0/solr/bin/install_solr_service.sh /tmp/solr-8.5.0.tgz -i /opt -d /var/solr -u solr -s solr -p 8983", "msg": "[Errno 13] Permission denied", "rc": 13}

**Comment by MacFlurry** [comment]
did you run with `become: yes` in your playbook ?

**Comment by kotireddy555** [comment]
@MacFlurry Thank you for response. Yes i have mentioned , here are the couple of lines of my playbook header.
---
- hosts: solr
  become: true

**Comment by MacFlurry** [comment]
something wrong with your playbook.yml (missing the `/`)
`src: "{{ download_dir }}solr-{{ solr_version }}.tgz"`  
it should be
`src: "{{ download_dir }}/solr-{{ solr_version }}.tgz`

**Comment by kotireddy555** [comment]
@MacFlurry Thank you for finding out. The issue was with package. The only reason didn't clone was to make hands dirty.

**Comment by geerlingguy** [comment]
@MacFlurry Thanks so much for the assistance on this issue :)

Got it resolved before I was even at the computer for the day!

**Comment by MacFlurry** [comment]
> @MacFlurry Thanks so much for the assistance on this issue :)
> 
> Got it resolved before I was even at the computer for the day!

you're welcome
I'll help in any way I can to free you from the time you don't always have...😁🥰
