### ISSUE TITLE
Drupal ansible build error

### ISSUE THREAD

**Issue by itsamorey** [geerlingguy/ansible-for-devops#248]
Get error as follows:
TASK [Install Drupal dependencies with Composer.] ******************************
fatal: [default]: FAILED! => {"msg": "Failed to set permissions on the temporary files Ansible needs to create when becoming an unprivileged user (rc: 1, err: chown: changing ownership of '/var/tmp/ansible-tmp-1587846360.93-31673-102113938312066/': Operation not permitted\nchown: changing ownership of '/var/tmp/ansible-tmp-1587846360.93-31673-102113938312066/AnsiballZ_command.py': Operation not permitted\n}). For information on working around this, see https://docs.ansible.com/ansible/become.html#becoming-an-unprivileged-user"}

**Comment by geerlingguy** [comment]
@itsamorey - Is this possibly related to https://github.com/geerlingguy/ansible-for-devops/issues/200 ?

**Comment by itsamorey** [comment]
Yes.

**Comment by itsamorey** [comment]
Yes, related to #200
