### ISSUE TITLE
cannot find roles in deployment of nodejs

### ISSUE THREAD

**Issue by hly189** [geerlingguy/ansible-for-devops#25]
when I run vagrant for the deployment of nodejs, this error appeared, would you please fix it. 

`ERROR: cannot find role in /Users/lythaihoa2311992/ansible_tutorial/ansible-for-devops/deployments/playbooks/roles/geerlingguy.git or /Users/lythaihoa2311992/ansible_tutorial/ansible-for-devops/deployments/playbooks/geerlingguy.git or /etc/ansible/roles/geerlingguy.git
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.`

**Comment by geerlingguy** [comment]
Did you run `ansible-galaxy install -r requirements.yml` prior to running the playbook? Make sure you follow all the steps in the README so all the dependencies are installed correctly.

**Comment by hly189** [comment]
Oh, i did not pay attention to the requirement. Sorry for the inconvenience.
