### ISSUE TITLE
[1.22] p. viii: erroneous closing parenthesis

### ISSUE THREAD

**Issue by rechvs** [geerlingguy/ansible-for-devops#251]
On p. viii (_Introduction_ chapter, section _Ansible and Red Hat_ ) there seems to be a closing parenthesis too many in the sentence
> Through his work with Puppet Labs and Red Hat (where he worked on Cobbler⁶, a configuration management tool, Func, a tool for communicating commands to remote servers), and some other
projects⁷), he experienced ...

**Comment by geerlingguy** [comment]
Yikes, you're correct. The markdown syntax in that sentence is a bit zany which is how that extra parens slipped in. I'll have this fixed (and credited to you!) in book version 1.23!
