### ISSUE TITLE
Inability to acquire Tower license

### ISSUE THREAD

**Issue by michaelmcdonald** [geerlingguy/ansible-for-devops#253]
Following the steps in your book to acquire and build the Tower VM works fine. I login and am presenting with the screen stating I need to acquire a license. Clicking that link (http://ansible.com/license) takes me to a screen asking me to download "Red Hat Ansible Automation Platform". I download it and it appears to be a playbook. No license key is presented and I'm not sure if it's in the file I extracted from the .tar.gz.

Any pointers?

**Comment by geerlingguy** [comment]
@michaelmcdonald - Sorry about that—please see https://github.com/geerlingguy/ansible-for-devops/issues/212

This is something I need to update in the current version of the book. For now, the quickest way to try out Tower (IMO) is to use the Tower Operator here: https://github.com/geerlingguy/tower-operator
