### ISSUE TITLE
Incorrect playbook name in ELK playbook example in 2020-03-21 ebook

### ISSUE THREAD

**Issue by mandrews4** [geerlingguy/ansible-for-devops#254]
Third paragraph of "ELK Playbook" section in Chapter 8, The sentence before the main playbook on page 212 of the pdf ends with:

.. saved as provisioning/elk/playbook.yml:

The name of the playbook in the sentence should be:

provisioning/elk/main.yml

This change matches what is specified in the Vagrantfile on pdf page 215:

22 logs.vm.provision :ansible do |ansible|
23 ansible.compatibility_mode = "2.0"
24 ansible.playbook = "provisioning/elk/**main.yml**"
25 ansible.inventory_path = "provisioning/elk/inventory"
26 ansible.become = true

as well as the name of the playbook in the book's examples on github.

**Comment by geerlingguy** [comment]
Oops! Sorry about that, you're correct. I'll have this fixed in the book version 1.23, coming soon!
