### ISSUE TITLE
Elk vagrant example in March 30 2020  book as well as github

### ISSUE THREAD

**Issue by mandrews4** [geerlingguy/ansible-for-devops#258]
I'm using vagrant 2.2.6 in a WSL (Windows Services for Linux) Ubuntu environment installed on Windows 10.

Please append a line which is common to your other Vagrantfiles to the Vagrant.configure section:

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "geerlingguy/ubuntu1804"
  config.ssh.insert_key = false
  **config.vm.synced_folder '.', '/vagrant', disabled: true**

Otherwise, the "vagrant up" command fails with a WSL specific error

During ansible provisioning of the geerlingguy/ubuntu1804 vm, installation of elasticsearch (using the geerlinguy.elasticsearch role) fails due to the lack of pip in the vm.

The addition of the geerlingguy.pip role prior to the geerlingguy.elasticsearch line in provisioning/elk/main.yml resolves the issue:

  roles:
    - geerlingguy.java
    - geerlingguy.nginx
    **- geerlingguy.pip**
    - geerlingguy.elasticsearch
    - geerlingguy.elasticsearch-curator
    - geerlingguy.kibana
    - geerlingguy.logstash
    - geerlingguy.filebeat

**Comment by geerlingguy** [comment]
Regarding the pip addition—what was the error you got when it was not present? The elasticsearch role doesn't use Pip in any way AFAICT.

It looks like the curator role _does_ require pip, though: https://github.com/geerlingguy/ansible-role-elasticsearch-curator/blob/7b1364efca9d27caeaea6a476156878d99d9b839/tasks/main.yml#L8-L15

**Comment by geerlingguy** [comment]
I just ran the test (now on Ubuntu 20.04 though), and didn't hit an issue with pip not being present, but since it does seem to be a requirement for the curator role, I see no harm in adding it in, especially since there are systems that will definitely _not_ have it installed.

**Comment by geerlingguy** [comment]
I'm also realizing that 2 GB of memory for the ES/Kibana server is woefully inadequate, so I'll bump that requirement to 4 GB.

**Comment by geerlingguy** [comment]
This will be fixed in the next version of the book. Thanks for posting!
