### ISSUE TITLE
Rails demo vagrant example in March 30 2020 book as well as github

### ISSUE THREAD

**Issue by mandrews4** [geerlingguy/ansible-for-devops#259]
I'm using vagrant 2.2.6 in a WSL (Windows Services for Linux) Ubuntu environment installed on Windows 10.

Please update the book example of the Vagrantfile on page 241 of the pdf to reflect github:

4 Vagrant.configure(2) do |config|
5   config.vm.box = "geerlingguy/ubuntu1804"
6    config.ssh.insert_key = false

and append a line which is common to your other Vagrantfiles to the Vagrant.configure section:

Vagrant.configure(2) do |config|
  config.vm.box = "geerlingguy/ubuntu1804"
  config.ssh.insert_key = false
  **config.vm.synced_folder '.', '/vagrant', disabled: true**

Otherwise, the "vagrant up" command fails with a WSL specific error

Thank you

**Comment by geerlingguy** [comment]
Thanks for the suggestion; I've fixed this in the text and it will be in the next version of the book!
