### ISSUE TITLE
[Chapter 8 - lamp stack] Error copying varnish default.vcl

### ISSUE THREAD

**Issue by butch82** [geerlingguy/ansible-for-devops#27]
Hi, 
no matter what I try, I keep getting this error:

fatal: [192.168.2.2]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"dest": "/etc/varnish/default.vcl", "src": "templates/default.vcl.j2"}, "module_name": "template"}, "msg": "AnsibleUndefinedVariable: 'host' is undefined"}

Can you help ? Thanks

Please note I am following your book at chapter 8.

**Comment by geerlingguy** [comment]
I'll try to take a look soon; also, can you confirm if you're running this on a Vagrant box, or on a different VM, cloud instance, or computer?

**Comment by geerlingguy** [comment]
Strangely, though... I'm not sure why 'host' would be undefined here. Can you also let me know what version of Ansible you're running (`ansible --version`)?

**Comment by butch82** [comment]
Hi, 
yes I'm running local in a vagrant infrastructure.
Versions are:
ansible 2.0.1.0
Vagrant 1.7.4

Bye, thanks

**Comment by geerlingguy** [comment]
Sorry about not getting back sooner—was this resolved?
