### ISSUE TITLE
Error running playbook with DigitalOcean as provider

### ISSUE THREAD

**Issue by rohankrishnadev** [geerlingguy/ansible-for-devops#274]
When I run the playbook for lamp-infrastructure, I get ```name 'basestring' is not defined``` error. I ran the playbook in verbose mode and have pasted the output in this [paste](https://pastebin.ubuntu.com/p/GnKnHg2GnV/) (it's a big wall of text). I haven't tested the playbook with vargant as a provider yet. Bit of googling tells me it is a Python2 / Python3 issue (apparently 'basestring' is no longer available in Python3). I'm guessing it's caused by dopy. I found this [thread](https://github.com/ansible/ansible-modules-core/issues/2509) where you mention ```pip install 'dopy>=0.3.5,<=0.3.5'``` should work, it didn't for me.

My environment is:
Operating system:
```bash
[rkrishnadev@vulcan lamp-infrastructure]$ cat /etc/os-release
NAME=Fedora
VERSION="31 (Server Edition)"
ID=fedora
VERSION_ID=31
VERSION_CODENAME=""
PLATFORM_ID="platform:f31"
PRETTY_NAME="Fedora 31 (Server Edition)"
```

Ansible:
```bash
[rkrishnadev@vulcan lamp-infrastructure]$ ansible --version
ansible 2.9.9
  config file = None
  configured module search path = ['/home/rkrishnadev/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/rkrishnadev/.local/lib/python3.7/site-packages/ansible
  executable location = /home/rkrishnadev/.local/bin/ansible
  python version = 3.7.7 (default, Mar 13 2020, 10:23:39) [GCC 9.2.1 20190827 (Red Hat 9.2.1-1)]
```

Python:
```bash
[rkrishnadev@vulcan lamp-infrastructure]$ python --version
Python 3.7.7
```

Packages installed using Pip (this was prior to ```pip install 'dopy>=0.3.5,<=0.3.5'```):
```bash
[rkrishnadev@vulcan lamp-infrastructure]$ pip list
Package          Version
---------------- ----------
ansible          2.9.9
ansible-lint     4.2.0
argcomplete      1.10.0
argh             0.26.1
certifi          2020.4.5.1
cffi             1.14.0
chardet          3.0.4
cryptography     2.9.2
dbus-python      1.2.8
decorator        4.4.0
distro           1.4.0
dopy             0.3.7
gpg              1.13.1
humanize         0.5.1
idna             2.9
Jinja2           2.11.2
libcomps         0.1.15
MarkupSafe       1.1.1
mitogen          0.2.9
pathspec         0.8.0
pip              19.1.1
pycparser        2.20
pydbus           0.6.0
PyGObject        3.34.0
python-augeas    0.5.0
python-dateutil  2.8.0
PyYAML           5.3.1
requests         2.23.0
rpm              4.15.1
ruamel.yaml      0.16.10
ruamel.yaml.clib 0.2.0
selinux          2.9
sepolicy         1.1
setools          4.2.2
setroubleshoot   1.1
setuptools       41.6.0
six              1.12.0
slip             0.6.4
slip.dbus        0.6.4
sos              3.8
systemd-python   234
urllib3          1.25.9
yamllint         1.23.0
```

**Comment by geerlingguy** [comment]
I believe that these issues should be fixed now after the updates I made as part of #229 — the provisioner was rewritten to use the newer DigitalOcean module, and I've also worked on updating all the book's examples and dynamic inventory script to use the latest upstream versions. The newer versions no longer require `dopy` at all.

**Comment by geerlingguy** [comment]
See, specifically, this commit: https://github.com/geerlingguy/ansible-for-devops/commit/a4e01fb0cd564194cdeb3121292b0b20438faef6
