### ISSUE TITLE
Struggling to access solr after successful play run (chapter4 example)

### ISSUE THREAD

**Issue by rkoosaar** [geerlingguy/ansible-for-devops#276]
Hi Jeff,

Thanks for all the excellent work you have done. I was following your instructions in chapter 4 and I didnt manage to get access to solr after my play finished successfully. I remembered from you other examples that you disabled the firewall in them, so I decided to try that. 
I modified the playbook and added the following lines after the "Install Java" task:

```
  - name: "Disable the firewall (since this is for local dev only)."
    service: name=ufw state=stopped
```

I saved the file and rerun the playbook. It finished again successfully and this time I was able to browse to solr Admin page.

**Comment by geerlingguy** [comment]
Thanks for posting the issue! When you ran this playbook, did you run it against the Vagrant/VirtualBox VM that's included in this book's repository (https://github.com/geerlingguy/ansible-for-devops/tree/master/solr), or against another host somewhere else?

Sometimes servers in the 'real world' do have firewalls configured (e.g. via ufw or firewalld), and if it's an Internet-facing server, it's a good idea to leave it enabled and only open the ports that are required.

For this particular example, it's kind of up to the user to define the firewall settings correctly, and whether you run on AWS, DigitalOcean, GCP, Azure, or some other place, the instructions for firewall configuration can differ (e.g. AWS and security groups may have you covered).

In the case of configuring a public server with `ufw` to make sure Solr is accessible, you can set it up with:

```yaml
- name: Allow access to Solr.
  ufw:
    rule: allow
    port: '8983'
    proto: tcp
```

Note that that rule would allow _anyone_ full access to Solr assuming there's no other software on the server handling access control. It's better for a Solr server to limit access to specific IP addresses or use HTTP authentication or some other mechanism to control access.
