### ISSUE TITLE
Chapter 10: Incorrect file references in unattended-upgrades example.

### ISSUE THREAD

**Issue by glillico** [geerlingguy/ansible-for-devops#277]
Hi,

I have noticed that in “Chapter 10 - Server Security and Ansible”, in the section “Automating updates for Debian-based systems” the task example refers to the template file 10periodic.

```
  with_items:
    - 10periodic
    - 50unattended-upgrades
```

However the explanation about the contents of the template file below the task example refers to 20auto-upgrades.

```
# File: /etc/apt/apt.conf.d/20auto-upgrades
```

Therefore I believe the task example should be modified to use 20auto-upgrades instead of 10periodic.

```
  with_items:
    - 20auto-upgrades
    - 50unattended-upgrades
```
Regards
Graham

**Comment by geerlingguy** [comment]
You're quite right! I'll have this fixed in the next version of the book, and I'll also add those lines of code to this book's repository since they're not in the 'security' example yet.
