### ISSUE TITLE
Chapter 2: Links need to be updated

### ISSUE THREAD

**Issue by vonDowntown** [geerlingguy/ansible-for-devops#278]
Hey,
so i found wrong links in Chapter 2: Using Ansible with Vagrant:
- Network interface management 
- Shared folder management 
- Provisioning
a fix should be removing `/index.html`

**Comment by geerlingguy** [comment]
Thanks! I'll be sure to take a look and get them updated.

**Comment by geerlingguy** [comment]
I've also updated a number of other links that worked, but resulted in a redirect (many were formerly http and are now https). This fix will be in the next revision of the book. Thanks!
