### ISSUE TITLE
[Chapter 8 - lamp stack] Error with galaxy module geerlingguy.repo-epel

### ISSUE THREAD

**Issue by butch82** [geerlingguy/ansible-for-devops#28]
Hi,
I am facing this issue when trying to use your galaxy module for epel repo.
The error is in italian but I'm sure you can understand it aswell:

TASK [geerlingguy.repo-epel : Install EPEL repo.] ******************************
fatal: [192.168.2.2]: FAILED! => {"changed": true, "failed": true, "msg": "Errore: Niente da fare\n", "rc": 1, "results": ["Plugin abilitati:fastestmirror\nImpostazione processo di installazione\nAnalisi di /var/tmp/yum-root-hSO8yJ/epel-release-latest-6.noarch.rpm: epel-release-6-8.noarch\n/var/tmp/yum-root-hSO8yJ/epel-release-latest-6.noarch.rpm: non aggiorna il pacchetto installato.\n"]}

Please note that I face the same error with modules from other people too (from ansible galaxy)
Anyway, if I ssh in the machine I can find the repo installed, so maybe:
- that repo is already present in your vagrant box and the module cant' handle this situation
- the module actually adds the repo and then fails somehow

Thanks, bye

**Comment by geerlingguy** [comment]
Hmm... if something else is already installing the repo, then it's probably best to not include this role at all—or you can add a task that runs prior to this role to delete the repo info on the machine before the role is run (in `pre_tasks`).
