### ISSUE TITLE
chapter 04 solr new_version installation issue - permission denied 

### ISSUE THREAD

**Issue by proirshad** [geerlingguy/ansible-for-devops#282]
{"changed": false, "cmd": "/tmp/solr-8.5.2/solr/bin/install_solr_service.sh /tmp/solr-8.5.2.tgz -i /opt -d /var/solr -u solr -s solr -p 8983", "msg": "[Errno 13] Permission denied", "rc": 13}

**Comment by geerlingguy** [comment]
@proirshad - I just re-tested this example and did not have any issue. I wonder if it's possible you are running this playbook without setting `become: true`? See for example: https://github.com/geerlingguy/ansible-for-devops/blob/master/solr/provisioning/playbook.yml#L3
