### ISSUE TITLE
Vagrantfile in Chapter 9: Zero-downtime... doesn't match repo

### ISSUE THREAD

**Issue by claycooper** [geerlingguy/ansible-for-devops#286]
Specifically line 16 in repo references three VMs and book mentions four.

https://github.com/geerlingguy/ansible-for-devops/blob/master/deployments-balancer/Vagrantfile#L16

**Comment by geerlingguy** [comment]
@claycooper oh my, you're quite right! I have fixed this in the book and it will be updated in the next revision.
