### ISSUE TITLE
Chapter 10, Section "Use a properly-configured firewall..."

### ISSUE THREAD

**Issue by claycooper** [geerlingguy/ansible-for-devops#288]
After the task "Configure default incoming/outgoing rules with ufw." The first sentence says 

> If you run a playbook with the above rules, the log into the machine

and it should be

> If you run a playbook with the above rules, then log into the machine

**Comment by geerlingguy** [comment]
Good catch; I'll make sure to get this fixed in the book's next revision.

**Comment by geerlingguy** [comment]
This has been fixed in the manuscript, and will be in the next book version.
