### ISSUE TITLE
Asides over text

### ISSUE THREAD

**Issue by octavian2204** [geerlingguy/ansible-for-devops#294]
Hi Jeff,

got your amazing book (.epub) and it being read very easy on my phone or PC but currently i have downloaded on my PocketBook (PB740) e-reader and got a unpleasant issue.
All asides icons are huge and are placed over text which makes impossible to read it. I have tried to change fonts, font size, every possible option and all changes except asides size. Attaching photos. 

![IMG_0467](https://user-images.githubusercontent.com/8106031/87879168-bb021a80-c9f1-11ea-9acb-82ecd25879dd.jpg)
![IMG_0468](https://user-images.githubusercontent.com/8106031/87879176-c0f7fb80-c9f1-11ea-8dd0-81927e1202e8.jpg)

I guess it is somehow related to the software you are using. Maybe asides size may/should be adjusted. 
Thank you a lot for your work and book!

**Comment by geerlingguy** [comment]
Interesting bug! Unfortunately, the way asides are formatted is something that's built as part of the LeanPub process, and they have a list of recommended apps and devices they test with here: http://help.leanpub.com/en/articles/3045130-how-can-i-read-a-leanpub-ebook-what-apps-or-devices-do-you-recommend

I would consider sending this information to LeanPub along with the device and/or software you're using, and maybe it's something they'd be able to adjust in the way they produce the book output.
