### ISSUE TITLE
Remove duplicate mysql_user tasks once Ansible 2.10 is stable

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-for-devops#297]
When updating the Drupal/includes examples to use Ubuntu 20.04 (see #295), I found that the latest version of MySQL used in 20.04 hits a bug in the `mysql_user` module that has only been fixed in the `community.general` version of the module (and not in 2.9.x, as it doesn't seem like it will be backported?).

Related issues:

  - https://github.com/geerlingguy/ansible-role-drupal/issues/77
  - https://github.com/ansible-collections/community.general/issues/543

**Comment by zaroth** [comment]
Since I just read the relevant section of the book, noting here that Ansible 2.10 is stable since mid-August.

**Comment by geerlingguy** [comment]
Heh, true.

**Comment by geerlingguy** [comment]
Done!
