### ISSUE TITLE
Should task names be declarative rather than imperative 

### ISSUE THREAD

**Issue by aleksandr-vin** [geerlingguy/ansible-for-devops#30]
Hi, Jeff

I've noticed that you use a [declarative style in task names](https://github.com/geerlingguy/ansible-for-devops/search?utf8=✓&q=ensure) at the beginning of your book, but then the "human-purposed" texts become imperative, why?

Ansible holds for idempotency which one can't be achieved imperatively and proper tasks (not `command` and `shell` ones) tries not to change the state without the need. I agree with you in proper describing of what the task actually do, but maybe it should be done through out the book?

**Comment by geerlingguy** [comment]
@aleksandr-vin - It's basically down to my style not being 100% consistent—I try to always be declarative, but a lot of times when I'm writing a set of tasks (I usually start with the `name`s), I write in whatever way my brain is thinking, and don't consider the exact desired outcome of the task. Most of the time, I go back and clean up the `name`s once I finish a playbook, but as you've found, sometimes I forget this step.

I've added a note in my review steps to try to do this more regularly, and I should hopefully be able to clean up instances where the style is off by the time I publish a 2nd/3rd edition of the book (I just pushed a large update to Kindle, Amazon, and LeanPub with a bunch of Ansible 2.0 and style fixes last week).
