### ISSUE TITLE
facing issue while trying to create a ticket

### ISSUE THREAD

**Issue by KATTULAPALLIPRAVEENKUMARREDDY** [geerlingguy/ansible-for-devops#305]
i am facing authentication issue even after providing accurate crendentials.here is my code. can anyone help me out.

---
- hosts: localhost
  gather_facts: no
  become_user: madhuric
  become: yes
  tasks:
  - name: Create a ticket
    uri:
      url: https://xxxx.service-now.com/api/now/table/incident
      method: POST
      user: xxxxx
      password: xxxxx
      body: {"short_description":"server issue,"assignment_group":"team A"}
      force_basic_auth: yes
      status_code: 201
      body_format: json

**Comment by geerlingguy** [comment]
This looks like a Service Now issue; this book's repository is more for issues relating to the book itself (which doesn't integrate with Service Now.

I would suggest opening an issue in the Ansible community project mailing list on Google Groups, asking on #ansible IRC, or asking in service now - related channels. Thanks!
