### ISSUE TITLE
broken link on Readme.md

### ISSUE THREAD

**Issue by Mexarm** [geerlingguy/ansible-for-devops#310]
this readme has a broken link:

https://github.com/geerlingguy/ansible-for-devops/blob/master/docker/README.md

[Ansible Vagrant Examples - Docker Flask app example](https://github.com/geerlingguy/ansible-vagrant-examples/tree/master/docker)
is broken

**Comment by geerlingguy** [comment]
Ah, right you are! I'll get that fixed up now.
