### ISSUE TITLE
Page 27, incorrect word

### ISSUE THREAD

**Issue by typ-ex** [geerlingguy/ansible-for-devops#318]
Not a technical issue, just a mispelling

![image](https://user-images.githubusercontent.com/19269683/90410602-2fbb8980-e070-11ea-9ee5-66bab6ab7864.png)

**Comment by geerlingguy** [comment]
I must've already fixed this, just didn't notice this issue until now. Sorry about that!

(Or is this actually a bug in ansible-for-kubernetes?)
