### ISSUE TITLE
Dynamic inventory with groups?

### ISSUE THREAD

**Issue by holms** [geerlingguy/ansible-for-devops#32]
Hi :) 

You've showed how to create digital ocean droplets , but add_hosts doesn't generate inventory file. Dynamic inventory file won't have groups which you've specified on digital ocean playbook. So I'm completely puzzled how to create dynamic inventory file, which would move droplets to certains groups. Without this I can't do deployment of certain groups.  Also as without having groups we can't do anything at all with ansible. The only way I've would to accomplish this, is to modify digital_ocean.py dynamic inventory file, so that it would seek for "group=" variable in user-data, thought digital ocean API. User-data would be filled with group variable, when creating droplet.

**Comment by geerlingguy** [comment]
This is something I'd like to add in a revision to the book. For now, the way I'm doing it for Hosted Apache Solr is I have an API endpoint on the site that lists the dynamic inventory as JSON. When I build a new server, I use [uri](http://docs.ansible.com/ansible/uri_module.html) to register the server with the Hosted Apache Solr API, then next time any playbooks are run, that new server is available in the dynamic inventory.

**Comment by holms** [comment]
There's some great news, digital ocean appears to be announced that they added tag support. https://developers.digitalocean.com/documentation/v2/#tags here's a manual :) https://www.digitalocean.com/community/tutorials/how-to-use-droplet-tagging-with-the-digitalocean-api 

How much does it cost to get next book revision? I've already purchased one :)

**Comment by geerlingguy** [comment]
Revisions will be free, forever :)

If you purchase on LeanPub, I try to update the book once every month or two with fixes, and then I update it on Amazon and LeanPub once every 4-6 months or so with larger changes. See http://www.ansiblefordevops.com/errata for all changes.

**Comment by holms** [comment]
Thanks I've bought it in Apple Store

**Comment by geerlingguy** [comment]
@holms - Ah, in that case it may be a couple months before I get a revision up... it's a bit of a pain to post updates to iBooks :(

**Comment by geerlingguy** [comment]
I'm still working on some more revisions—just finished a first step of rewriting the DigitalOcean example to use the v2 API (which allows for extra metadata/notes to be attached, which can be used to build groups dynamically, just like with AWS), and I'll be working on more updates over the next few months... I'm going to close this issue though, as I'm not 100% sure I'll have the time to work on a concrete DO groups example right now, and point anyone interested over to the AWS example that follows (in chapter 7).

Hopefully I'll be able to do the same kind of example for DO, but right now other priorities are holding this up.

**Comment by geerlingguy** [comment]
Also look at this example, which I will soon be updating as well: https://github.com/geerlingguy/ansible-for-devops/blob/master/lamp-infrastructure/provisioners/digitalocean.yml
