### ISSUE TITLE
Page 42-43 example doesn't match explanation

### ISSUE THREAD

**Issue by grendelson** [geerlingguy/ansible-for-devops#330]
In the section "Deploy a version-controlled application" page 42 states the updates script is at "...then running a shell script at
/opt/myapp/scripts/update.sh ."
But the example on the next page says to run:
"Then, run the application’s update.sh shell script:
$ ansible app -b -a "/opt/myapp/update.sh""

This might confuse folks wondering where the missing "scripts" folder went ! :+1 :)

Thanks!

**Comment by geerlingguy** [comment]
Yikes, thanks for spotting this! It's fixed in the latest version of the book.
