### ISSUE TITLE
Error p. 84: The module firewalld was redirected to community.general.firewalld, which could not be loaded

### ISSUE THREAD

**Issue by rpappalax** [geerlingguy/ansible-for-devops#332]
```
$ ansible db -b -m firewalld -a "zone=database state=present permanent=yes
> "
192.168.60.6 | FAILED! => {
    "msg": "The module firewalld was redirected to community.general.firewalld, which could not be loaded."
}

```

**Comment by Technik-J** [comment]
With Ansible 2.10 use `ansible.posix.firewalld` for module name:

```
ansible db -b -m ansible.posix.firewalld -a "zone=database state=present permanent=yes"
```

[Ansible docs for reference.](https://docs.ansible.com/ansible/latest/collections/ansible/posix/firewalld_module.html)

**Comment by stefanfluit** [comment]
Also, I first had to make sure Firewalld was running before that command would work. 

`ansible db -b -m service -a "name=firewalld state=started enabled=yes"`

**Comment by geerlingguy** [comment]
Weird... that redirect _seems_ like it should be going through correctly just calling `firewalld`. Right??

**Comment by geerlingguy** [comment]
Opened a bug report in community.general for this... https://github.com/ansible-collections/community.general/issues/1940

**Comment by geerlingguy** [comment]
Maybe this is the proper place for it: https://github.com/ansible/ansible/pull/73689

**Comment by typ-ex** [comment]
Glad this is here.  Is it safe to assume it needed to be done for any adhoc command that calls for the module firewalld?

**Comment by geerlingguy** [comment]
It shouldn't be needed since the redirect has been fixed.

Someday I'll update book examples to use FQCN's, but that is not this day.
