### ISSUE TITLE
Typo in Chapter 3 about CentOS Vagrant Box File

### ISSUE THREAD

**Issue by abidmunirmalik** [geerlingguy/ansible-for-devops#336]
I think there is an error in "Ansible For DevOps" book on chapter 3, page 20, line 8:

**_http://config.vm.box = "geerlingguy/centos8"_**

But on page 21, it mentioned
**_"all three servers will be running CentOS 7"_**  

I believe the Box file is for CentOS 7 and not CentOS 8.

Abid Malik

**Comment by geerlingguy** [comment]
Another reader also spotted this one—it's just due to my own lack of editing in the final work to get the 2nd edition done. I'll fix this soon and have an updated copy of the manuscript.

**Comment by geerlingguy** [comment]
This is fixed in the latest version of the book.

Though I'm sure I've mixed up something else, somewhere else now :D
