### ISSUE TITLE
CH3 error from ad-hoc command to install Django with pip3

### ISSUE THREAD

**Issue by doug-rosser** [geerlingguy/ansible-for-devops#337]
This is also piggybacked onto another issue at https://github.com/geerlingguy/ansible-for-devops/issues/312

But I'm highlighting here for clarity. In Chapter 3 the listed ad-hoc command

`ansible app -b -m pip -a "name=django<4 state=present"`

Generates as error as follows:

```
$ ansible app -b -m pip -a "name=django<4 state=present"
192.168.60.4 | FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "msg": "Unable to find any of pip2, pip to use.  pip needs to be installed."
}
192.168.60.5 | FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "msg": "Unable to find any of pip2, pip to use.  pip needs to be installed."
}
```

There are a couple possible workarounds, but I used:

`ansible app -b -m pip -a "executable=pip3 name=django<4 state=present"`

**Comment by geerlingguy** [comment]
Thanks for posting this! I'll look into it on my next round of corrections for Ansible for DevOps.

**Comment by tbjorkna** [comment]
I also used the `executable=pip3` to work around this. In addition to that, on the next line you have: to make sure Django is installed and working correctly: `ansible app -a "python -m django --version"` I had to explicitly use python3 instead of python like this: `ansible app -a "python3 -m django --version"` otherwise I got the following error: 

> 192.168.60.4 | FAILED | rc=1 >>
> /usr/bin/python: No module named djangonon-zero return code
> 192.168.60.5 | FAILED | rc=1 >>
> /usr/bin/python: No module named djangonon-zero return code

**Comment by robyaggie** [comment]
> ansible app -b -m pip -a "executable=pip3 name=django<4 state=present"

Thanks for this help, Doug. 

@geerlingguy, just bought the book (and 2 others of yours today) and I'm enjoying them. Can you update the errata to at least point people to these issues? Also, Centos8 reached EOL so I had to update chapter 3 files from here in github to go back to Centos7. But hey, at least I've made it this far and on a Windows host using WSL to boot.

**Comment by geerlingguy** [comment]
@robyaggie - I'll be pushing out a book update tonight. Thanks to all for validating this fix, I'll be adding it in.
