### ISSUE TITLE
Playbooks, YAML, and layout, or is it syntax?

### ISSUE THREAD

**Issue by aixtools** [geerlingguy/ansible-for-devops#339]
re: Current Published Book Version Information
• Current book version: 2.0
• Current Ansible version as of last publication: 2.10
• Current Date as of last publication: August 5, 2020

a. enjoy the book -- but :)

I am struggling with getting the spacing/indents/with '-' as beginning character, without character.

After I found the link to the YAML introduction (in 2nd paragraph Ch. 4) https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html I began to have a clearer understanding of what I was reading.

imho: cut/paste is not the measure of having learned something

```
---
hosts: _target_
```

That much is clear.

But why is it
`  tasks:`
and not

`- tasks:`
or
`  - tasks:`

More generically - when is a YAML list item indented, when (or why) are some prefixed with with a dash-space sequence (`- `).

The YAML documents talk about all these sequences - but the YAML documents do not talk about how ansible expects YAML `objects` (for lack of a better word atm) to be organized.

As to typographical conventions:
* the examples are generally speaking, in mono-text - great
* it would help someone like me if the ansible-keywords were highlighted (e.g., bold) as that helps me see it as something to remember as such, rather than as a 'just some text preceding a colon', because I really get confused.
- lets just take the substring `_vars`: 

a)
`Automatically-loaded group_vars and host_vars . . . . . . . . . 97`
b)
```
Inventory variables . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 169
host_vars . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 170
group_vars . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 172
```
c)
```
vars:
  proxy_vars:
    http_proxy: http://example-proxy:80/
    https_proxy: https://example-proxy:443/
    [etc...]
```
And why is this one (vars: not indented?) and none of them with a prefix? Neither were they in the index.

I could go on looking for the sub-string _var - but I really do not know when it is an ansible keyword, (maybe they all are!), or when it is a convention you use for naming variables - as you did for the environment variable `ENV_VAR`

I have the feeling you just assume I understand all this, or know all of this before I begin.
So much time spent on Vagrant, and so little on YAML basics, and in particular, the YAML specifics re: working with ansible.

Maybe it is all there - somewhere - but not structured the way (I was taught as a technical course writer).

Still using the book, less so the live-streams. Vagrant kind of turned me off - not my environment. So - :) lots of self-discovery, but also frustration with trying to get the syntax right.

Best wishes,
Michael

**Comment by aixtools** [comment]
While I hope I have an answer to part of what was troubling me yesterday - I would still appreciate confirmation or correction in the annotated example I made of your playbook in chapter 4. (I much prefer comments in-line, rather than as extended footnotes).

It took a while for me to pay proper attention to your footnotes, but when a footnote, and what it describes is more than a page away - it is, imho, cumbersome reading.

Hence: my annoted example - did I get it right?

```
# An annotated Playbook
---
# The line above - of exactly three minus ('-') characters
# functions as the begin tag, much like '<?php' does for php
# code blocks
## The following comments precede the Ansible code,
## The blank-line before a comment is to make it easier to recognize
## The start of a new Ansible code element

# Here starts an Ansible play - using the '- hosts: target'
# Ansible starts with specifying the object(s) to be acted on,
# as well as any additional qualities needed by the environment
# such as user privildges
- hosts: all
  become: yes

  # Note: 'become:' above, and 'tasks:' below are elements being defined
  # for the play started by - hosts: all above
  # the play (what gets done to/on the hosts by (optional user specification)
  # are done by named tasks. An individual task starts with the '- ' sequence
  # And it is highly recommended that the first element of the task is
  # it's name:
  tasks:
    # Note: this starts a YAML list. A second task for this play begins in
    # the same hierarchy (column) position as this one
    - name: Copy Configuration Files
      # At this level of indentation we specify ONE action plus the
      # values needed for the action. The action here is an Ansible feature
      # note: this does not begin with '- '
      copy:
        # copy needs source, destination, and file mode
        # these are each specified on a seperate line
        # As this is going to be using a LOOP feature of Ansible
        # the src: and dest: definitions here include Jinya varaibles.
        # Note also the use of double quotes around {{ var_name }}
        src:  "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0644
      # At this level we 'continue the command - now formed as:
      # copy with items - and below we define the individual items
      # with_items: each list element define an item 
      # (so now we need the '- ' prefix for the first element of an item
      with_items:
        - src: httpd.conf
          dest: /etc/httpd/conf/httpd.conf
        - src: httpd-vhosts.conf
          dest: /etc/httpd/conf/httpd-vhosts.conf

    # And now the second task - note the change in identation - and that we start
    # with a descriptive name
    # Less verbose below - the same logic applies in the second task
    # Describe with name, perform a single Action
    - name: Make sure Apache is started now and at boot
      service:
        name: httpd
        state: started
        enabled: true
# Back at this level - you could start a new PLAY, or, optionally, terminate the YAML
# with '...'
...

```
In the hope this helps understand how some (not all) students learn - and what inhibits 'ease of learning'.

**Comment by geerlingguy** [comment]
Thanks for the thoughts here—I do note that some Ansible projects online teach in a way where there's one massive YAML file with tons of inline comments.

The major issue in book format is that the larger the YAML file gets, the harder it is for me to explain it in any kind of coherent way, so I generally try to have YAML, then explanation, then YAML, rather than commented single files.
