### ISSUE TITLE
ansible-galaxy {role|collection} install geerlingguy.apache - what is the difference?

### ISSUE THREAD

**Issue by aixtools** [geerlingguy/ansible-for-devops#340]
Just a question about command syntax.

In chapter 4 you say we are talking about 'roles' and 'collections' get covered in the next chapter.

Yet, when I go to https://galaxy.ansible.com/geerlingguy/apache - while this link is included under 'roles' the Installation is documented as:

![image](https://user-images.githubusercontent.com/10852597/95252060-bc86f600-081c-11eb-91e1-26f60251461e.png)

So, not the word 'role' as you have in chapter 6.

Am I correct in assuming that 'role' is default, whereas 'collection' must be specified?

**Comment by geerlingguy** [comment]
Yes, that is correct. And since this behavior is new in 2.10 and may also have some minor differences in 2.11, I'm going to keep the text the same way in the book for the time being, especially since many people are still using Ansible 2.8 and 2.9, where that command is the best option for roles.

**Comment by aixtools** [comment]
My bad that I packaged and use 2.10 (on AIX).

My good: that I'll never have to relearn :)

Many thanks for the clarification - probably applies in many locations.
