### ISSUE TITLE
ch3 - epub - broken URL "official documentation of the User module"

### ISSUE THREAD

**Issue by digitalodin** [geerlingguy/ansible-for-devops#346]
chapter 3
.epub version
link text in book:  "official documentation of the User module"
linked URL: https://docs.ansible.com/ansible/latest/user_module.html
error on site: Oops! The version of the Ansible documentation you were looking at doesn’t contain that page.
suggested correct URL: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/user_module.html

**Comment by MalcolmAnderson** [comment]
Just ran into this too.

**Comment by geerlingguy** [comment]
Sorry about that, I have fixed this separately as there were a few other issue reports for it. Oops!
