### ISSUE TITLE
Wrong use of "it's" as possessive

### ISSUE THREAD

**Issue by David-Gil** [geerlingguy/ansible-for-devops#347]
Page 115

• Using host and port and drained for the state parameter, check if a given port
has drained all **it’s** active connections.

It should be "all its active connections."

Page 158

But in this case, we’re using a test plugin, not a regular module or role, so we need
to refer to the module in a special way, using **it’s** ‘Fully Qualified Collection Name’
(FQCN), which in this test plugin’s case would be local.colors.blue.

Page 382

• For a typical webserver, we need port 22 for SSH access, port 80 for unencrypted
HTTP access (Let’s Encrypt needs this to operate using **it’s** default verification
mechanism), and port 443 for encrypted HTTPS access.

Page 410

If you see “MySQL Connection: PASS”, congratulations, everything worked! If it
shows ‘FAIL’, you might need to give the MySQL a little extra time to finish **it’s**
initialization, since it has to build **it’s** environment on first launch. If the page
doesn’t show up at all, you might want to compare your code with the Docker Flask
example188 on GitHub.

**Comment by geerlingguy** [comment]
Yikes! I'll work on fixing those in the next revision of the book. Thanks!

**Comment by David-Gil** [comment]
Thank you for the amazing book you've written!! I'm rewriting and restructuring all my roles and playbooks based on it. I'm really happy.

**Comment by geerlingguy** [comment]
@David-Gil - It makes me happy to help you, too :)

**Comment by geerlingguy** [comment]
This should be fixed in the next version of the book. Thanks again!
