### ISSUE TITLE
chapt 3, incorrect vagrant status results after doing vagrant up

### ISSUE THREAD

**Issue by gskluzacek** [geerlingguy/ansible-for-devops#353]
In chapter 3 I've followed the setup as described (except I modified centos8 to cent07 in the Vagrantfile). After vagrant up completes and I do a vagrant status it list 2 "instances" of the app2 vm?

```
Gregs-iMac:multi_vms gskluzacek$ vagrant status
Current machine states:

app1                      running (virtualbox)
app2                      running (virtualbox)
app2                      running (virtualbox)

This environment represents multiple VMs. The VMs are all listed
above with their current state. For more information about a specific
VM, run `vagrant status NAME`.
```

however, when I do vagrant global-status I do see the expected results.

```
Gregs-iMac:multi_vms gskluzacek$ vagrant global-status
id       name   provider   state   directory                                       
-----------------------------------------------------------------------------------
c43505a  app1   virtualbox running /Users/gskluzacek/Documents/ansbl_prj/multi_vms 
db48f79  app2   virtualbox running /Users/gskluzacek/Documents/ansbl_prj/multi_vms 
119ef6f  db     virtualbox running /Users/gskluzacek/Documents/ansbl_prj/multi_vms 
 
The above shows information about all known Vagrant environments
on this machine. This data is cached and may not be completely
up-to-date (use "vagrant global-status --prune" to prune invalid
entries). To interact with any of the machines, you can go to that
directory and run Vagrant, or you can use the ID directly with
Vagrant commands from any directory. For example:
"vagrant destroy 1a2b3c4d"
```

VirtualBox UI also shows the correct vm names
<img width="529" alt="image" src="https://user-images.githubusercontent.com/15515/98483059-28b59a80-21cb-11eb-911e-cc0d7555290a.png">

I'm using macOS 14.10.6
python 3.9.0
Vagrant 2.2.13
VirtualBox 6.1.16
ansible 2.10.3
  config file = None
  configured module search path = ['/Users/gskluzacek/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ansible
  executable location = /Library/Frameworks/Python.framework/Versions/3.9/bin/ansible
  python version = 3.9.0 (v3.9.0:9cf6752276, Oct  5 2020, 11:29:23) [Clang 6.0 (clang-600.0.57)]

additionally...

Gregs-iMac:multi_vms gskluzacek$ vagrant ssh db

if I try to ssh to the db host, I get the following which is for the app2 host

Last login: Sun Nov  8 20:44:15 2020 from 10.0.2.2
[vagrant@orc-app2 ~]$ hostname -A
orc-app2.test orc-app2.test 
[vagrant@orc-app2 ~]$ hostname -I
10.0.2.15 192.168.60.5 
[vagrant@orc-app2 ~]$ 

but if ssh to the id given for the db host from global-status, I connect to the expected host.

Gregs-iMac:multi_vms gskluzacek$ vagrant ssh 119ef6f
Last login: Sun Nov  8 20:37:47 2020 from 192.168.60.1
[vagrant@orc-db ~]$ hostname -A
orc-db.test orc-db.test 
[vagrant@orc-db ~]$ hostname -I
10.0.2.15 192.168.60.6 

even more...

when I do vagrant halt, only the 2 app VMs shutdown.

```
Gregs-iMac:multi_vms gskluzacek$ vagrant halt
==> app2: Attempting graceful shutdown of VM...
==> app1: Attempting graceful shutdown of VM...

Gregs-iMac:multi_vms gskluzacek$ vagrant global-status
id       name   provider   state    directory                                       
------------------------------------------------------------------------------------
c43505a  app1   virtualbox poweroff /Users/gskluzacek/Documents/ansbl_prj/multi_vms 
db48f79  app2   virtualbox poweroff /Users/gskluzacek/Documents/ansbl_prj/multi_vms 
119ef6f  db     virtualbox running  /Users/gskluzacek/Documents/ansbl_prj/multi_vms 
```

here are the various config files from my project directory (added .txt so they could be uploaded). I had copied and pasted the content of the config files from the chapter three git-hub repo here.

[ansible.cfg.txt](https://github.com/geerlingguy/ansible-for-devops/files/5507162/ansible.cfg.txt)
```
[defaults]
inventory = hosts.ini
```
[hosts.ini.txt](https://github.com/geerlingguy/ansible-for-devops/files/5507163/hosts.ini.txt)
```
# Application servers
[app]
192.168.60.4
192.168.60.5

# Database server
[db]
192.168.60.6

# Group 'multi' with all servers
[multi:children]
app
db

# Variables that will be applied to all servers
[multi:vars]
ansible_user=vagrant
ansible_ssh_private_key_file=~/.vagrant.d/insecure_private_key
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
```
[Vagrantfile.txt](https://github.com/geerlingguy/ansible-for-devops/files/5507164/Vagrantfile.txt)
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # General Vagrant VM configuration.
  config.vm.box = "geerlingguy/centos7"
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider :virtualbox do |v|
    v.memory = 512
    v.linked_clone = true
  end

  # Application server 1.
  config.vm.define "app1" do |app|
    app.vm.hostname = "orc-app1.test"
    app.vm.network :private_network, ip: "192.168.60.4"
  end

  # Application server 2.
  config.vm.define "app2" do |app|
    app.vm.hostname = "orc-app2.test"
    app.vm.network :private_network, ip: "192.168.60.5"
  end

  # Database server.
  config.vm.define "db" do |db|
    db.vm.hostname = "orc-db.test"
    db.vm.network :private_network, ip: "192.168.60.6"
  end
end
```

**Comment by gskluzacek** [comment]
So, I did a vagrant destroy, it had some issues and an error was thrown, but I managed to clean up and get to a state where everything was good.

I did another vagrant up, and everything came up correctly this time, even though I didn't update any of the config files

**Comment by geerlingguy** [comment]
@gskluzacek - Heh... sometimes that's just the way Vagrant + VirtualBox works. Today I had to create and destroy a VM 3 times before I could get it to be happy. No clue why, I've done it a hundred times before, today one of the two things probably just has a case of the Mondays.
