### ISSUE TITLE
CH1 - docker image ErrImagePull

### ISSUE THREAD

**Issue by kentahikaru** [geerlingguy/ansible-for-devops#356]
Hello ,
i follow instructions in chapter 1 to deploy hello-go app, but it seems minikube can't pull the image.

I did:
minikube start
eval $(minikube docker-env)
docker build -t hello-go .
... now "docker image list" looks like in book, hello-go + some k8s images

But
kubectl create deployment hello-go --image=hello-go
results in:
kubectl get pod
NAME                       READY   STATUS         RESTARTS   AGE
hello-go-b6dbd5d87-rxpf7   0/1     ErrImagePull   0          6s

kubectl get pod -o wide
NAME                       READY   STATUS             RESTARTS   AGE   IP           NODE       NOMINATED NODE   READINESS GATES
hello-go-b6dbd5d87-rxpf7   0/1     ImagePullBackOff   0          20m   172.17.0.3   minikube   <none>           <none>

book version: 0.4

minikube version
minikube version: v1.14.0
commit: b09ee50ec047410326a85435f4d99026f9c4f5c4-dirty

Do i need to do something more for minikube to pull image ?
Thanks

**Comment by wargfn** [comment]
Hey Kent, if you do a **kubectl describe pod hello-go** and check the Image: line. Can you download that to your machine? Secondly, is that Image: line correct architecture for your machine?

In the Hello-go example, I am using Raspberry PIs using a 32Bit Raspbian OS. Which meant that I had to manually compile the hello-go application into the arm32 architecture. My version I pushed here -> https://hub.docker.com/repository/docker/wargfndev/rpi-hello-go.

To see if your having issues such as architecture miss match, **kubectl logs pod hello-go**. I am betting that between these two commands {describe} and {logs}, you will be able to figure out exactly what is going on.

**Comment by kentahikaru** [comment]
Aah, never mind, the next steps are described in the book.
I got startled.

**Comment by geerlingguy** [comment]
Heh, this is also the wrong repo—the A4K book is over at https://github.com/geerlingguy/ansible-for-kubernetes

**Comment by kentahikaru** [comment]
> Heh, this is also the wrong repo—the A4K book is over at https://github.com/geerlingguy/ansible-for-kubernetes

Aah, sorry about that.
That's what happens when you start to read your two new books at the same time.

**Comment by geerlingguy** [comment]
@kentahikaru - no problem at all! Glad you're getting some value out of them :)
