### ISSUE TITLE
chronyd replacing ntpd

### ISSUE THREAD

**Issue by richarddoty** [geerlingguy/ansible-for-devops#357]
It looks like the book is in the process of changing from ntpd to chronyd in the examples.  One occurrence of ntpd on p.29 and two occurrences of ntpd on p.33 should be changed to chronyd

This is in 2nd edition, 2020-08095

**Comment by geerlingguy** [comment]
Thanks for pointing that out—I'll be looking into that in the next revision.

**Comment by pragmatiker** [comment]
I may add on p. 34 the two commands also still refrence ntpd:
ansible app -b -a "service ntpd restart" --limit "*.4"
ansible app -b -a "service ntpd restart" --limit ~".*\.4"

**Comment by geerlingguy** [comment]
I've finally gotten through and fixed all the references now. Thanks!
