### ISSUE TITLE
forever list fails : [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by jotihojr** [geerlingguy/ansible-for-devops#358]
Had the same problem as described in #85. I solved it by adding `/usr/local/bin` to sudo's `secure_path` in the `geerlingguy/centos8` box.

```
[vagrant@nodejs ~]$ sudo -l
Matching Defaults entries for vagrant on nodejs:
    !visiblepw, always_set_home, match_group_by_gid, always_query_group_plugin,
    env_reset, env_keep="COLORS DISPLAY HOSTNAME HISTSIZE KDEDIR LS_COLORS",
    env_keep+="MAIL PS1 PS2 QTDIR USERNAME LANG LC_ADDRESS LC_CTYPE",
    env_keep+="LC_COLLATE LC_IDENTIFICATION LC_MEASUREMENT LC_MESSAGES",
    env_keep+="LC_MONETARY LC_NAME LC_NUMERIC LC_PAPER LC_TELEPHONE", env_keep+="LC_TIME
    LC_ALL LANGUAGE LINGUAS _XKB_CHARSET XAUTHORITY",
    secure_path=/sbin\:/bin\:/usr/sbin\:/usr/bin\:/usr/local/bin

User vagrant may run the following commands on nodejs:
    (ALL) ALL
    (ALL) NOPASSWD: ALL
```

**Comment by mrkbabu** [comment]
Had the same problem as describe in #85. I solved it by using geerlingguy/centos7 box instead of geerlingguy/centos8. I was following the youtube video Ansible 101 - Episode 6 - Ansible Vault and Roles. In the video Jeff was using centos8 but mentions it will work for centos7 as well. After comparing the code with github, I decided to use centos7 and it worked.

**Comment by mkondratev** [comment]
Other way:
```
  environment:
    PATH: "/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:"
```

**Comment by arikb** [comment]
I solved it using the laziest way - I changed ```forever``` in the playbook to ```/usr/local/bin/forever```

**Comment by geerlingguy** [comment]
Heh, that works too :D

**Comment by geerlingguy** [comment]
For now I've updated the book example to use `rockylinux8` and the full path to `forever` since it's not in root's `$PATH`. I also updated the examples in this repo. Thanks for posting, and sorry for the trouble!
