### ISSUE TITLE
Chapter 4: Ubuntu LAMP server with Drupal

### ISSUE THREAD

**Issue by cortes-** [geerlingguy/ansible-for-devops#367]
After executing the playbook the Apache default start page opens, but not Drupal.

I solved this by adding the `DirectoryIndex index.php` parameter to the `VirtualHost `template.

Result file:

```
<VirtualHost *:80>
  ServerAdmin webmaster@localhost
  ServerName {{ domain }}.test
  ServerAlias www.{{ domain }}.test
  DocumentRoot {{ drupal_core_path }}/web
  DirectoryIndex index.php
  <Directory "{{ drupal_core_path }}/web">
    Options FollowSymLinks Indexes
    AllowOverride All
  </Directory>
</VirtualHost>
```

**Comment by geerlingguy** [comment]
That shouldn't be necessary—it seems to work locally without it, but I'm wondering if maybe for some reason Apache wasn't restarted the first time, or maybe you're running it on a server where you already had an instance of Apache running?

Can you provide full steps to reproduce following one of the book's examples? If so, I would reopen and retest to verify.
