### ISSUE TITLE
lamp-infrastructure: missing firewall referrenced in main.yml

### ISSUE THREAD

**Issue by EdZilla** [geerlingguy/ansible-for-devops#37]
https://github.com/geerlingguy/ansible-for-devops/blob/master/lamp-infrastructure/playbooks/varnish/main.yml
Error is: 
The error appears to have been in '...ansible-for-devops/lamp-infrastructure/playbooks/varnish/main.yml': line 9, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
    - geerlingguy.firewall
      ^ here

**Comment by EdZilla** [comment]
I missed it here too: 
Run ansible-galaxy install -r requirements.yml to install require Ansible roles.
embarrassed.

**Comment by geerlingguy** [comment]
@EdZilla - It happens to the best of us! No problem at all.
