### ISSUE TITLE
I'm unable to open my Node.js application from my local machine

### ISSUE THREAD

**Issue by luisusquianomoreno** [geerlingguy/ansible-for-devops#378]
Hi, I have cloned this project: Simple Node.js Development VM
but when I do 'vagrant up' to deploy this virtual machine, I cannot open this application from my browser
What is unclear for me is the part of the inventory file. 
"Edit your hosts file, adding the line 192.168.55.55 nodejs.test so you can connect to the VM."
by the way, the link [to modify host file is broken](http://www.rackspace.com/knowledge_center/article/how-do-i-modify-my-hosts-file)

I thought that I just had to do 'vagrant up' to see my app from my browser on my local machine
Edit: the only way to see the app is through: http://192.168.55.55 but I can't do it by http://hostname as it say in the book

**Comment by geerlingguy** [comment]
You would still need to modify your hosts file to be able to use the hostname (unless you have something like Vagrant Hostsupdater installed as well).

I've been trying to make sure to update all the links to 'how to update the hosts file'... I'll do another pass to make sure the links are updated now.

**Comment by geerlingguy** [comment]
Those links are all updated now, sorry about that!
