### ISSUE TITLE
missing role 'geerlingguy.firewall

### ISSUE THREAD

**Issue by EdZilla** [geerlingguy/ansible-for-devops#38]
this is the same as issue #37, but a different project
https://github.com/geerlingguy/ansible-for-devops/tree/master/jenkins

upon vagrant up, error is : 
ERROR! the role 'geerlingguy.firewall' was not found
ansible-for-devops/jenkins/provision.yml': line 12, column 7,

**Comment by geerlingguy** [comment]
@EdZilla - Which example did you run where this happened? Some of the examples require an `ansible-galaxy install -r requirements.yml` step to install the required roles.

**Comment by EdZilla** [comment]
Which example? See the github project reference in the original post. 
https://github.com/geerlingguy/ansible-for-devops/blob/master/jenkins/README.md
i was going by the project readme. The readme says nothing about ansible-galaxy install...

**Comment by EdZilla** [comment]
oops
Correctiion! 
Run ansible-galaxy install -r requirements.yml to install require Ansible roles.
I'll try again...
