### ISSUE TITLE
Chapter 9 load balancer ubuntu 20.04

### ISSUE THREAD

**Issue by typ-ex** [geerlingguy/ansible-for-devops#380]
Running the load balancing playbook results in no response when doing the curl loop.  Works for 18.04 though.

**Comment by typ-ex** [comment]
Turns out from ubuntu 18.04 to 20.04, Cookie is now set-cookie.  Will suggest grep change elsewhere.

**Comment by geerlingguy** [comment]
Interesting change! I'll have to get that re-tested and updated for the latest version of the book. I thought I had re-tested that example but apparently not.

**Comment by typ-ex** [comment]
Retested again as I'm messing around with Jenkins.  cookie would also work.  Case sensitive.

**Comment by geerlingguy** [comment]
I've decided to update the example to use case-insensitive grep: `grep -i cookie` — should work no matter what now!
