### ISSUE TITLE
solr virtualbox Connection Refused

### ISSUE THREAD

**Issue by JaimePolo** [geerlingguy/ansible-for-devops#381]
Hi Jeff,

Following chapter 4, on the solr playbook, initially the VM built and everything was fine as far as provisioning the VM with ansible (solr wasn't reachable though) and because of that I decided to rebuild the VM.

I ran vagrant destroy and then vagrant up again, the problem this time is Vagrant keeps saying: 
"default: Warning: Connection refused. Retrying..."
Until it times out.

this is the VM ifconfig:
![image](https://user-images.githubusercontent.com/13440682/106081958-d3ad6480-60e7-11eb-8b43-4ad6fba45928.png)

this is virtualbox network config for the VM:
![image](https://user-images.githubusercontent.com/13440682/106082014-f0e23300-60e7-11eb-96a9-6c01dfe5977c.png)
![image](https://user-images.githubusercontent.com/13440682/106082041-fb043180-60e7-11eb-833a-5b2507649e09.png)

and this is the network manager configuration:
![image](https://user-images.githubusercontent.com/13440682/106082077-0c4d3e00-60e8-11eb-95c2-396ecb484d82.png)

I've tried several different settings including "Bridge Adapter", "Host Only" and so on, but to no avail.

Any ideas?

**Comment by JaimePolo** [comment]
Update: the problem is with Ansible trying to connect to the box with the Vagrant setup. After running ansible separately it was able to run the playbook.

This is the code I used to ran the playbook:
`ansible-playbook -i provisioning/hosts provisioning/playbook.yml -u vagrant --private-key=/mnt/c/Users/JPolo/.vagrant.d/insecure_private_key `

**Comment by typ-ex** [comment]
Vagrant playbook might have had the private key located somewhere else.

**Comment by richard-gunderson** [comment]
I was unable to use JaimePolo method to execute the playbook.  Adding  -u vagrant --private-key=/my/path/to/insecure_private_key did not work. Kept throwing errors with my .known_hosts file. (I'm executing Ansible from a Linux Mint 19.3 VM.)

Also, I'm stuck at the task "Create a MySQL database for Drupal.".  This is the error I get...
TASK [Create a MySQL database for Drupal.] **************************************************************************************************************
fatal: [drupal.test]: FAILED! => {"changed": false, "msg": "unable to connect to database, check login_user and login_password are correct or /root/.my.cnf has the credentials. Exception message: (1698, \"Access denied for user 'root'@'localhost'\")"}

The root user without any password by default has access to the MySQL server. I even created a /root/.my.cnf  file but it still won't work. I don't know what the default user and password are.

Oh, by the way -- I had to add a dependency that was left out of task "Install Apache, MySQL, PHP, and other dependencies."      -   include the package "- python3-pymysql"  to the list of dependencies.

**Comment by typ-ex** [comment]
The creds for the database is hardcoded as the domain set in the vars file and the password is 1234

**Comment by richard-gunderson** [comment]
Still fails, using 'drupal' as the user

TASK [Create a MySQL database for Drupal.] **************************************************************************************************************
fatal: [drupal.test]: FAILED! => {"changed": false, "msg": "unable to connect to database, check login_user and login_password are correct or /root/.my.cnf has the credentials. Exception message: (1045, \"Access denied for user 'drupal'@'localhost' (using password: YES)\")"}

My .my.cnf  file on the target machine:
[client]
user = drupal
password = 1234


And my vars.yml file is:
---
# The path where Drupal will be downloaded and installed.
drupal_core_path: "/var/www/drupal"

# The resulting domain will be [domain].test (with .test appended).
domain: "drupal"

# Your Drupal site name.
drupal_site_name: "Drupal Test"


Is there a specific geerlingguy vagrant box I should use? I've tried ubuntu1804  and ubuntu2004.

**Comment by typ-ex** [comment]
Do you have your files on github?

**Comment by richard-gunderson** [comment]
No.

**Comment by typ-ex** [comment]
If you can link your want to copy and paste your playbook on here, I can look for where it might have gone wrong.

**Comment by richard-gunderson** [comment]
I don't know how to use GitHub. What I can do is paste my playbook here ...

---
- hosts: drupal.test
  become: yes

  vars_files:
    - vars.yml

  pre_tasks:
    - name: Update apt cache if needed.
      apt: update_cache=yes cache_valid_time=3600

  handlers:
    - name: restart apache
      service: name=apache2 state=restarted

  tasks:
    - name: Get software for apt repository management.
      apt:
        state: present
        name:
          - python3-apt
          - python3-pycurl

    - name: Add ondrej repository for later versions of PHP.
      apt_repository: repo='ppa:ondrej/php' update_cache=yes

    - name: "Install Apache, MySQL, PHP, and other dependencies."
      apt:
        state: present
        name:
          - acl
          - git
          - curl
          - unzip
          - sendmail
          - apache2
          - php7.4-common
          - php7.4-cli
          - php7.4-dev
          - php7.4-gd
          - php7.4-curl
          - php7.4-json
          - php7.4-opcache
          - php7.4-xml
          - php7.4-mbstring
          - php7.4-pdo
          - php7.4-mysql
          - php-apcu
          - libpcre3-dev
          - libapache2-mod-php7.4
          - python3-mysqldb
          - python3-pymysql
#          - python3-pip
#          - python-pip
#          - python-pymysql
          - mysql-server
    
    - name: Disable the firewall (since this is for local dev only).
      service: name=ufw state=stopped

    - name: "Start Apache, MySQL, and PHP."
      service: "name={{ item }} state=started enabled=yes"
      with_items:
        - apache2
        - mysql

    - name: Enable Apache rewrite module (required for Drupal).
      apache2_module: name=rewrite state=present
      notify: restart apache

    - name: Add Apache virtualhost for Drupal.
      template:
        src: "templates/drupal.test.conf.jinja"
        dest: "/etc/apache2/sites-available/{{ domain }}.test.conf"
        owner: root
        group: root
        mode: 0644
      notify: restart apache

    - name: Enable the Drupal site.
      command: >
        a2ensite {{ domain }}.test
        creates=/etc/apache2/sites-enabled/{{ domain }}.test.conf
      notify: restart apache

    - name: Disable the default site.
      command: >
        a2dissite 000-default
        removes=/etc/apache2/sites-enabled/000-default.conf
      notify: restart apache

    - name: Adjust OpCache memory setting.
      lineinfile:
        dest: "/etc/php/7.4/apache2/conf.d/10-opcache.ini"
        regexp: "^opcache.memory_consumption"
        line: "opcache.memory_consumption = 96"
        state: present
      notify: restart apache

    - name: Create a MySQL database for Drupal.
      mysql_db: "name={{ domain }} state=present"

    - name: Create a MySQL user for Drupal.
      mysql_user:
        name: "{{ domain }}"
        password: "1234"
        priv: "{{ domain }}.*:ALL"
        host: localhost
        state: present

    - name: Download Composer installer.
      get_url:
        url: https://getcomposer.org/installer
        dest: /tmp/composer-installer.php
        mode: 0755

    - name: Run Composer installer.
      command: >
        php composer-installer.php
        chdir=/tmp
        creates=/usr/local/bin/composer

    - name: Move Composer into globally-accessible location.
      command: >
        mv /tmp/composer.phar /usr/local/bin/composer
        creates=/usr/local/bin/composer

    - name: Ensure Drupal directory exists.
      file:
        path: "{{ drupal_core_path }}"
        state: directory
        owner: www-data
        group: www-data

    - name: Check if Drupal project already exists.
      stat:
        path: "{{ drupal_core_path }}/composer.json"
        register: drupal_composer_jsonChapter 4 - Ansible Playbooks

    - name: Create Drupal project.
      composer:
        command: create-project
        arguments: drupal/recommended-project "{{ drupal_core_path }}"
        working_dir: "{{ drupal_core_path }}"
        no_dev: true
      become_user: www-data
      when: not drupal_composer_json.stat.exists

    - name: Add drush to the Drupal site with Composer.
      composer:
        command: require
        arguments: drush/drush:10.*
        working_dir: "{{ drupal_core_path }}"
      become_user: www-data
      when: not drupal_composer_json.stat.exists

    - name: Install Drupal.
      command: >
        vendor/bin/drush si -y --site-name="{{ drupal_site_name }}"
        --account-name=admin
        --account-pass=admin
        --db-url=mysql://{{ domain }}:1234@localhost/{{ domain }}
        --root={{ drupal_core_path }}/web
        chdir={{ drupal_core_path }}
        creates={{ drupal_core_path }}/web/sites/default/settings.php
      notify: restart apache
      become_user: www-data

**Comment by typ-ex** [comment]
>   * name: Create a MySQL database for Drupal.
>     mysql_db: "name={{ domain }} state=present"

Should be "db={{ domain }} state=present"

**Comment by richard-gunderson** [comment]
I had that originally. I changed it to see if it would work. It didn't. "db" is an alias for "name" according to:

https://docs.ansible.com/ansible/2.8/modules/mysql_db_module.html

**Comment by typ-ex** [comment]
Does the playbook report any changes when installing the dependencies?  

Next thing I have is that there could be a formatting issue.

**Comment by richard-gunderson** [comment]
Unsure I understand what you're asking. The first time I run the playbook on a fresh VM, yes there are changes. If I run it after that... no changes. Again not sure I understand your question.

**Comment by typ-ex** [comment]
I'm saying that if the playbook looks exactly as you copied and pasted it, I think there are issues in how the playbook is spaced.

> name: Create a MySQL user for Drupal.
> mysql_user:
> name: "{{ domain }}"
> password: "1234"
> priv: "{{ domain }}.*:ALL"
> host: localhost
> state: present

Should look something like

name: Create a MySQL user for Drupal.
mysql_user:
  name: "{{ domain }}"
  password: "1234"
  priv: "{{ domain }}.*:ALL"
  host: localhost
  state: present

I just re ran the playbook myself and ended up with 24 ok and 20 changes.

**Comment by richard-gunderson** [comment]
Okay, but the the module that's failing for me is mysql_db. Also, like I said I don't know how to properly "paste" code into GitHub. If I use the "insert code" button, it makes the formatting even more messed up.

I just modified that task a little bit. And ran the playbook using the options:  -vvv --step --start-at-task='Create a MySQL database for Drupal;

I modified that task a little bit... here is what I changed it to:
    - name: Create a MySQL database for Drupal.
      mysql_db: "db={{ domain }} login_user={{ domain }} login_password=1234 state=present"

Here is the error part that was printed...

> fatal: [drupal.test]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "ca_cert": null,
            "check_hostname": null,
            "check_implicit_admin": false,
            "client_cert": null,
            "client_key": null,
            "collation": "",
            "config_file": "/root/.my.cnf",
            "config_overrides_defaults": false,
            "connect_timeout": 30,
            "db": "drupal",
            "dump_extra_args": null,
            "encoding": "",
            "force": false,
            "hex_blob": false,
            "ignore_tables": [],
            "login_host": "localhost",
            "login_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "login_port": 3306,
            "login_unix_socket": null,
            "login_user": "drupal",
            "master_data": 0,
            "name": [
                "drupal"
            ],
            "quick": true,
            "restrict_config_file": false,
            "single_transaction": false,
            "skip_lock_tables": false,
            "state": "present",
            "target": null,
            "unsafe_login_password": false,
            "use_shell": false
        }
    },
    "msg": "unable to find /root/.my.cnf. Exception message: (1045, \"Access denied for user 'drupal'@'localhost' (using password: YES)\")"


Clearly this is a mysql problem, not an ansible problem. My version of mysql keeps complaining. In this case it's saying the file /root/.my.cnf is missing. (Which is correct, I built a fresh VM and didn't create that file.)

Perhaps this could be resolved if you just told me what a correct .my.cnf  should looke like. I don't know anything about MySQL.

**Comment by typ-ex** [comment]
Unfortunately, I'm not very good at SQL either.  

May I see the results of the playbook ran with the verbose flag without you hardcoding the user/pass in that play?

**Comment by richard-gunderson** [comment]
Reverted the task to orignal (as published...)

Results:

> fatal: [drupal.test]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "ca_cert": null,
            "check_hostname": null,
            "check_implicit_admin": false,
            "client_cert": null,
            "client_key": null,
            "collation": "",
            "config_file": "/root/.my.cnf",
            "config_overrides_defaults": false,
            "connect_timeout": 30,
            "db": "drupal",
            "dump_extra_args": null,
            "encoding": "",
            "force": false,
            "hex_blob": false,
            "ignore_tables": [],
            "login_host": "localhost",
            "login_password": null,
            "login_port": 3306,
            "login_unix_socket": null,
            "login_user": null,
            "master_data": 0,
            "name": [
                "drupal"
            ],
            "quick": true,
            "restrict_config_file": false,
            "single_transaction": false,
            "skip_lock_tables": false,
            "state": "present",
            "target": null,
            "unsafe_login_password": false,
            "use_shell": false
        }
    },
    "msg": "unable to find /root/.my.cnf. Exception message: (1698, \"Access denied for user 'root'@'localhost'\")"

**Comment by typ-ex** [comment]
Thank you.  On this task

> name: Add Apache virtualhost for Drupal.
> template:
> src: "templates/drupal.test.conf.jinja"
> dest: "/etc/apache2/sites-available/{{ domain }}.test.conf"
> owner: root
> group: root
> mode: 0644
> notify: restart apache

Do you have the file titled as "drupal.test.conf.jinja"?  The book has the file originally named "drupal.test.conf.j2"

**Comment by richard-gunderson** [comment]
Oh, right. I was looking at other posts (errata) on this GitHub topic. I came across a post by Jeff Geerling himself ("Update all .j2 file extension usages to .jinja" #199)

The text editor I use (Sublime 3) didn't recognize .js and treats it like a plain ansi text file. So after reading his proposal to change the file extention I changed it myself to see if Sublime 3 recognized it. Turns out it does not. I just forgot to change the extension back to .js.

My ansible code was working (for that task) before I made that change.

**Comment by typ-ex** [comment]
I'll look into the file should look like, and update this post.  From the error message it looks like the file is there but the permissions aren't correct. I was hoping the file in the file explorer didn't match the playbook.  Shame.

**Comment by richard-gunderson** [comment]
Last night when I first started commenting on this topic, the file was there. But this morning I did a 'vagrant destroy' before I re-built the VM. In this new VM, the file is not there.

The error message " _unable to find /root/.my.cnf_ " Is correct. It's not there. I can add it, but like I said I don't know what it's **supposed** to look like. The file I had there last night looked like this...

> [client]
user = drupal
password = 1234

Have no idea if that's correct, or what its supposed to be. Regardless, if everyone can run this playbook then clearly I'm doing something wrong. The book is about learning Ansible. I feel I understand this Ansible code and can move on.

**Comment by typ-ex** [comment]
If you can move on with peace of mind, we can drop it then.  

I only think it's missing because the details of the error message said access to it was denied and didn't mention anything about not existing.  
Also the VM isn't letting me access the root directory and sudo cd apparently isn't a thing.  I'm going to work on that, but here are my results in the meantime

changed: [35.171.160.252] => {
    "changed": true,
    "db": "drupal",
    "db_list": [
        "drupal"
    ],
    "executed_commands": [
        "CREATE DATABASE `drupal`"
    ],
    "invocation": {
        "module_args": {
            "ca_cert": null,
            "check_hostname": null,
            "check_implicit_admin": false,
            "client_cert": null,
            "client_key": null,
            "collation": "",
            "config_file": "/root/.my.cnf",
            "config_overrides_defaults": false,
            "connect_timeout": 30,
            "db": "drupal",
            "dump_extra_args": null,
            "encoding": "",
            "force": false,
            "hex_blob": false,
            "ignore_tables": [],
            "login_host": "localhost",
            "login_password": null,
            "login_port": 3306,
            "login_unix_socket": null,
            "login_user": null,
            "master_data": 0,
            "name": [
                "drupal"
            ],
            "quick": true,
            "restrict_config_file": false,
            "single_transaction": false,
            "skip_lock_tables": false,
            "state": "present",
            "target": null,
            "unsafe_login_password": false,
            "use_shell": false
        }
    }
}

**Comment by richard-gunderson** [comment]
I'm willing to drop this, but...

So as a test, I SSH'ed into the VM. I executed this command:

> sudo mysql

And it worked. Then I tried

> sudo mysql --user=root

That also worked. And creating the database worked too..

> create database drupal;

I wish there was a way to see the actual commands executed on the server by Ansible.

**Comment by richard-gunderson** [comment]
I got it to work. Forget everything I posted on here.

This is one of those days I wish I could delete everything I posted to the internet in the past 24 hrs.

**Comment by typ-ex** [comment]
Glad you did.  Curious about what happened, but not necessary for you to post.

**Comment by geerlingguy** [comment]
Heh, seeing as this seems to be resolved, I'll go ahead and close out this issue.
