### ISSUE TITLE
FYI: Wrong link on page 108

### ISSUE THREAD

**Issue by xd999e** [geerlingguy/ansible-for-devops#383]
Hey Jeff,

FYI: The link on page 108:

`http://docs.ansible.com/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable`

is not working to reference to Ansible’s Variable Precedence.

This should be the correct link:
`https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#ansible-variable-precedence`

**Comment by rxexgx** [comment]
Well get the message on nearly every link:
`You are reading an older version of the Ansible documentation. Use the version selection to the left if you want the latest stable released version.`

**Comment by geerlingguy** [comment]
@rxexgx - Thanks for the note; I will try to get the links updated for the next revision. Ansible's docs site has changed a lot especially in the last year so it's no surprise some of these links are starting to fail :(
