### ISSUE TITLE
CentOS 7/8

### ISSUE THREAD

**Issue by mattl** [geerlingguy/ansible-for-devops#384]
Chapter 2 sees the creation of a CentOS 7 box. Chapter 8 sees the creation of several CentOS 8 boxes.

Page 21 refers to these boxes as CentOS 7 boxes.

I suspect we'll see this change to Rocky Linux before too long, but just putting it here anyway.

**Comment by fndmossmann** [comment]
Also, the Vagrantfile on Page 21 uses CentOS 8:
`config.vm.box = "geerlingguy/centos8"`

And on the first paragraph after the Vagranfile (Page 22), it says we'll be using CentOS 7:
```
This Vagrantfile defines the three servers we want to manage, and gives each one a
unique hostname, machine name (for VirtualBox), and IP address. For simplicity’s
sake, all three servers will be running CentOS 7.
```

**Comment by geerlingguy** [comment]
D'oh, gotta get those references updated!

**Comment by fndmossmann** [comment]
My guess is that the book actually uses CentOS 8.
I was using CentOS 7 (because of the Vagrantfile config) and was running into issues regarding pip versions.

It was requested to install python3-pip:
`$ ansible app -b -m yum -a "name=python3-pip state=present"`

But CentOS 7 has Python 2.7 as the default interpreter
`"ansible_python_version": "2.7.5",`

So, when installing Django:
`$ ansible app -b -m pip -a "name=django<4 state=present"`

It doesn't find pip3:
```
    "changed": false,
    "msg": "Unable to find any of pip2, pip to use.  pip needs to be installed."
```

I'll be running CentOS 8 from now on, as it uses Python 3 by default.

**Comment by charleshbaker** [comment]
> Also, the Vagrantfile on Page 21 uses CentOS 8:
> `config.vm.box = "geerlingguy/centos8"`
> 
> And on the first paragraph after the Vagranfile (Page 22), it says we'll be using CentOS 7:
> 
> ```
> This Vagrantfile defines the three servers we want to manage, and gives each one a
> unique hostname, machine name (for VirtualBox), and IP address. For simplicity’s
> sake, all three servers will be running CentOS 7.
> ```

I saw same issue. Hadn't yet made my way here and tweeted to @geerlingguy about it.

**Comment by charleshbaker** [comment]
> My guess is that the book actually uses CentOS 8.
> I was using CentOS 7 (because of the Vagrantfile config) and was running into issues regarding pip versions.
> 
> It was requested to install python3-pip:
> `$ ansible app -b -m yum -a "name=python3-pip state=present"`
> 
> But CentOS 7 has Python 2.7 as the default interpreter
> `"ansible_python_version": "2.7.5",`
> 
> So, when installing Django:
> `$ ansible app -b -m pip -a "name=django<4 state=present"`
> 
> It doesn't find pip3:
> 
> ```
>     "changed": false,
>     "msg": "Unable to find any of pip2, pip to use.  pip needs to be installed."
> ```
> 
> I'll be running CentOS 8 from now on, as it uses Python 3 by default.

In order to keep using CentOS7 I put a variable in the inventory:

[app:vars]
ansible_python_interpreter=/usr/bin/python3

That might cause problems later...so I guess I'll rebuild my boxes w/ CentOS8 and get rid of the variable.

**Comment by InterceptorF** [comment]
Well this issue just shot me in the a$$ - I can't understand how to get around it.

**Comment by geerlingguy** [comment]
Heh... This is all fixed up in the latest version of the book, hopefully to come tonight!
