### ISSUE TITLE
Molecule: Need to install molecule-docker driver

### ISSUE THREAD

**Issue by all64bits** [geerlingguy/ansible-for-devops#397]
I tried setting up a Molecule environment on my machine to try out your example, but when I run `molecule test` I get a pre-validation error as per [this issue](https://github.com/ansible-community/molecule/issues/2891); so you need to also do `pip3 install molecule-docker`.

I would try submitting a PR for this, but I've never done a PR before & want to make sure I do it right! Don't have much spare time at the moment but will try coming back to it later

**Comment by geerlingguy** [comment]
See https://github.com/geerlingguy/ansible-for-devops/blob/master/.github/workflows/molecule-ci.yml#L30 — note that the latest book I believe is up to date, so do you know what version of the book you're currently reading?

**Comment by all64bits** [comment]
Sorry, I should have specified: I'm not actually following the book, but rather I was interested in learning about Molecule & went straight to the Molecule section of your examples repo, and followed the installation notes in the [README.md](https://github.com/geerlingguy/ansible-for-devops/blob/master/molecule/README.md), which is where I hit the issue

**Comment by geerlingguy** [comment]
Ah... so that README needs the update :D

**Comment by all64bits** [comment]
Correct. I should try including all of the details next time!
