### ISSUE TITLE
Typo in ch 9 > Mac Provisioning with Ansible and Homebrew > first paragraph

### ISSUE THREAD

**Issue by jlmuir** [geerlingguy/ansible-for-devops#399]
In Chapter 9 - Ansible Cookbooks > Mac Provisioning with Ansible and Homebrew > first paragraph, "to you" should be "do you" in the following sentence:

> How much time to you spend automating configuration and testing of applications and infrastructure at your day job ...?

**Comment by geerlingguy** [comment]
Thanks! I'll try to get this fixed in the next revision!

**Comment by geerlingguy** [comment]
This will be fixed in the next version of the book. Thanks!
