### ISSUE TITLE
[error found, solution offered] Different APC error aborts vagrant up on drupal playbook

### ISSUE THREAD

**Issue by victorkane** [geerlingguy/ansible-for-devops#4]
Sorry, still getting error after refreshing code, slightly different error but on the same lines:

TASK: [Enable upload progress via APC.] ***************************************
failed: [default] => {"failed": true, "rc": 257}
msg: Destination /etc/php5/conf.d/20-apc.ini does not exist !

FATAL: all hosts have already failed -- aborting

**Comment by geerlingguy** [comment]
Fixed over in #6 - thanks!
