### ISSUE TITLE
Chapter 3 p31. ERROR! this task 'firewalld' has extra params, ....

### ISSUE THREAD

**Issue by luasntd** [geerlingguy/ansible-for-devops#401]
when i write the cli :
`<ansible db -b -m firewalld -a "zone = database state = present permanent= yes">`
Result:
`<ERROR! this task 'firewalld' has extra params, which is only allowed in the following modules: ansible.legacy.import_role, include_tasks, shell, set_fact, ansible.builtin.include_vars, ansible.builtin.set_fact, ansible.legacy.include_role, add_host, include_vars, ansible.builtin.include_tasks, ansible.legacy.raw, ansible.legacy.include, ansible.builtin.import_tasks, ansible.builtin.script, ansible.builtin.win_shell, ansible.builtin.include, ansible.builtin.meta, ansible.legacy.script, ansible.legacy.include_vars, command, ansible.legacy.group_by, ansible.legacy.add_host, ansible.legacy.win_command, raw, ansible.builtin.import_role, include, ansible.builtin.win_command, ansible.legacy.import_tasks, include_role, ansible.builtin.shell, ansible.legacy.set_fact, ansible.builtin.include_role, ansible.builtin.add_host, ansible.legacy.shell, ansible.legacy.win_shell, ansible.builtin.group_by, script, win_shell, win_command, ansible.legacy.command, meta, ansible.legacy.meta, ansible.builtin.raw, ansible.builtin.command, import_tasks, ansible.windows.win_shell, ansible.legacy.include_tasks, group_by, ansible.windows.win_command, import_role>`
pls help me!

**Comment by nstallons** [comment]
Remove your spaces before and after "="

For example:
$ ansible db -b -m firewalld -a "zone=database state=present permanent=yes"

**Comment by geerlingguy** [comment]
@nstallons is correct—you need to use no spaces around the `=` when using ad hoc commands with inline parameters, exactly following the book's formatting.
