### ISSUE TITLE
Chapter 4 vagrant provision gets UNREACHABLE ... Permission denied

### ISSUE THREAD

**Issue by glennoph** [geerlingguy/ansible-for-devops#406]
I was trying to install solr via vagrant.  The vagrant provision got this message: 

TASK [Gathering Facts] *********************************************************
fatal: [solr]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Warning: Permanently added '192.168.60.7' (ECDSA) to the list of known hosts.\r\nvagrant@192.168.60.7: Permission denied (publickey,password).", "unreachable": true}

Any suggestions to fix this?

**Comment by geerlingguy** [comment]
@glennoph - It seems like maybe you don't have the ability to connect to the solr VM via SSH for some reason. What kind of computer are you on? Can you run `vagrant ssh` and log in that way?

Does searching for similar issues like https://github.com/hashicorp/vagrant/issues/10280 help?

**Comment by glennoph** [comment]
Thanks for the reply.
I updated the Vagrantfile to include: 

  config.vm.box = "geerlingguy/ubuntu2004"
  config.ssh.insert_key = true # was false
  config.vm.synced_folder '.', '/home/vagrant/src'  ## this was commented

I ran halt and vagrant up and got the following messages 

> 
> ==> solr: Mounting shared folders...
>     solr: /home/vagrant/src => /home/glenn/src/github.com/glennoph/ansible-devops/ch04-playbook
> Vagrant was unable to mount VirtualBox shared folders. This is usually
> because the filesystem "vboxsf" is not available. This filesystem is
> made available via the VirtualBox Guest Additions and kernel module.
> Please verify that these guest additions are properly installed in the
> guest. This is not a bug in Vagrant and is usually caused by a faulty
> Vagrant box. For context, the command attempted was:
> 
> mount -t vboxsf -o uid=900,gid=900 home_vagrant_src /home/vagrant/src
> 
> The error output from the command was:
> 
> : Invalid argument

vagrant ssh works but there are no files in  /home/vagrant/src

Suggestions?

**Comment by geerlingguy** [comment]
@glennoph - Are you running the latest version (6.1.22) of VirtualBox?

**Comment by glennoph** [comment]
I updated VirtualBox before i started, Version 6.1.22 r144080 (Qt5.12.8)
I also updated vagrant, Vagrant 2.2.14

the code is in https://github.com/glennoph/ansible-devops/tree/main/ch04-playbook

**Comment by glennoph** [comment]
I installed the extension pack 
Oracle VM VirtualBox Extension Pack
was installed successfully.

Now the synced folder is in the vm and the command
vagrant provision is working.

**Comment by geerlingguy** [comment]
Interesting! Typically that extension pack isn't required, though I guess for some reason it was in your case :(

Closing for now, but if others run into the same issue, please let me know and we can try to figure out why it happened!
