### ISSUE TITLE
Link not up to date anymore ⌛ - p.34 in the book

### ISSUE THREAD

**Issue by CodingIsLove** [geerlingguy/ansible-for-devops#408]
Hi there ✋
It seems, that the link to the ansible user_module documentation is not up to date anymore. When clicking on the link I get a 404 message.  I think that the up-to-date link would be: https://docs.ansible.com/ansible/2.9/user_guide/modules_intro.html

**Comment by geerlingguy** [comment]
Thanks! I'll have to get this updated in the next version of the book.

**Comment by patrckb** [comment]
That link is good if you're running Red Hat. 

> You are reading the latest community version of the Ansible documentation. Red Hat subscribers, select 2.9 in the version selection to the left for the most recent Red Hat release.

Otherwise...
> Starting in Ansible 2.10, modules are grouped in collections. For an idea of how many collections Ansible includes, take a look at the [Collection Index](https://docs.ansible.com/ansible/latest/collections/index.html#list-of-collections).

**Comment by geerlingguy** [comment]
This has been fixed in the latest version of the manuscript. Thanks!
