### ISSUE TITLE
ansible dynamic inventory for linode

### ISSUE THREAD

**Issue by prasathsekar** [geerlingguy/ansible-for-devops#409]
Any ansible dynamic inventory available for linode ?

**Comment by geerlingguy** [comment]
@prasathsekar - Not in the book, no—but there is a generic Linode [plugin](https://docs.ansible.com/ansible/latest/collections/community/general/linode_inventory.html) for dynamic inventory that can be used like any other.

**Comment by prasathsekar** [comment]
Do you have any example playbook by using generic Linode plugin for dynamic inventory

**Comment by geerlingguy** [comment]
No, you'll need to reference the Linode plugin's documentation and you can ask on Ansible's libera.chat IRC channel or elsewhere. I use DigitalOcean for most of my production infrastructure, and don't use Linode's dynamic inventory for the Linodes I run.
