### ISSUE TITLE
add support for libvirt/kvm provider on Vagrant boxes used in Book samples

### ISSUE THREAD

**Issue by rafaeltuelho** [geerlingguy/ansible-for-devops#41]
Please, add support for libvirt provider for people who do not want to use Virtualbox on Linux hosts.

**Comment by geerlingguy** [comment]
I've had a few requests for this... I'm looking into it, but want to make sure I can support this usage well and not just give it lip-service.

**Comment by geerlingguy** [comment]
Just linking to https://github.com/geerlingguy/drupal-vm/issues/649

**Comment by geerlingguy** [comment]
I've closed that downstream issue; right now I just don't have the resources to build other versions of the base boxes, and I'm also slowly moving towards using some other virtualization options for my testing and scaffolding, so I'm going to close this ticket and for now recommend using other base boxes that d support libvirt (there are usually a couple options when searching https://app.vagrantup.com/boxes/search?provider=libvirt).
