### ISSUE TITLE
Paperback buyers: get access to PDF version

### ISSUE THREAD

**Issue by k-stz** [geerlingguy/ansible-for-devops#419]
Hello Jeff, 

thanks for the book and the content you made around it, love it! :+1: 

I have a service improvement proposal: 
- for buyers of the paperback version: provide access to the PDF of the book (via code?)

Reason in my case:
- I had to get the paperback version for corporate reasons
- comfort of using electronic version

greetings from Germany :)

**Comment by geerlingguy** [comment]
Informally, if someone emails me the paperback receipt, I'll generate a code for them to get it on LeanPub free.

Additionally, the Kindle version I believe bumps down to $2 USD if you buy the paperback from Amazon.
