### ISSUE TITLE
Second Edition, Page 89, Chapter 5 -- typo

### ISSUE THREAD

**Issue by clevengr** [geerlingguy/ansible-for-devops#436]
The last paragraph on page on page 89 says "We use source `~/.bash_profile in line 4...` ".  However, that line is actually line 3 in the preceding listing.

**Comment by geerlingguy** [comment]
It should actually be line `8` now (the 2nd task in the group), but you are correct! I've updated this in the manuscript and will hopefully have a book update out soon.
