### ISSUE TITLE
Second Edition, page 273 (Chapter 10)

### ISSUE THREAD

**Issue by clevengr** [geerlingguy/ansible-for-devops#438]
The next-to-last sentence on page 273 says "Let's create the [main.yml] playbook and include the above `provisioning.yml` playbook...".
However, the name given to 'the above file' on the previous page (first paragraph) is `provision.yml`, not `provisioning.yml`.

**Comment by geerlingguy** [comment]
Thanks for finding these little grammar issues :)

**Comment by clevengr** [comment]
You're welcome :)   I enjoyed the book tremendously -- so much so that I
bought a second copy and sent it to a colleague :)

john

**Comment by geerlingguy** [comment]
This will be fixed in the next version of the book. Thanks!
