### ISSUE TITLE
Second Edition, page 315 (Chapter 11)

### ISSUE THREAD

**Issue by clevengr** [geerlingguy/ansible-for-devops#439]
The "tip" (or "key") aside at the top of page 315 says "You can use `validate` option with Ansible's `copy`, `linefile`, `blockinfile`, and `template` modules."
I think `linefile` was intended to be `lineinfile`, as I can't find any `linefile` module in ansible...

I would also suggest there's a missing `the` in front of the word `validate`, but maybe that's just a personal style thing...

**Comment by geerlingguy** [comment]
Good catches!

**Comment by geerlingguy** [comment]
This is fixed in the latest version of the book manuscript. Thanks!
