### ISSUE TITLE
not able to start Vagrant VMs in CH3

### ISSUE THREAD

**Issue by pleegor** [geerlingguy/ansible-for-devops#44]
Hi, 

I am using Vagrant file from chapter3 and I am not able to start VMs. 
OS X Sierra
Vagrant 1.8.7
This is the error I am getting:
https://gist.github.com/pleegor/1a5411763a905f4afaf37a6bd6280fce#file-gistfile1-txt

I also tried to run vagrant add <username/box> and I am not to download this box as well. 

Any help is appreciated.

**Comment by pleegor** [comment]
This is fixed! All you need to do is:
`rm -rf /opt/vagrant/embedded/bin/curl`

https://github.com/mitchellh/vagrant/issues/7970

**Comment by geerlingguy** [comment]
@pleegor - Glad you found that fix! It's affecting a lot of people right now, unfortunately. Hopefully they'll release 1.8.8 soon!
