### ISSUE TITLE
start over 

### ISSUE THREAD

**Issue by InterceptorF** [geerlingguy/ansible-for-devops#440]
For those like me that got stuck because of the centos7 debacle ( I am not savvy with vagrant at all so its taken some time to figure this out) I am hoping this gets you back on track.
Starting over at page 10 - commands need changed from:
 vagrant box add geerlingguy/centos7
to
 vagrant box add geerlingguy/centos8

Then rm Vagrantfile if you started with centos7 ( the init below will tell you to do so...)  
Change:
vagrant init  geerlingguy/centos7
to 
vagrant init  geerlingguy/centos8

Then if you were using centos7 you need to run commands:
vagrant destroy.
vagrant up 
vagrant ssh
[vagrant@localhost] $ cat /etc/*release
Verify you have centos8 running.
If you do not use the 'vagrant destroy' command above, the vm will still be using centos7.
[vagrant@localhost] $ exit

**Comment by geerlingguy** [comment]
Please see https://github.com/geerlingguy/ansible-for-devops/issues/384 — I will likely need to make some changes to use a more stable base image (and clean up references throughout the book so they work with the latest of whatever OS I choose, maybe Rocky Linux 8).
