### ISSUE TITLE
Second Edition, Chapter 4: Misleading term

### ISSUE THREAD

**Issue by chinovader** [geerlingguy/ansible-for-devops#442]
Throughout the section **Launch a Node.js app**, pages 64-65, the term `play` is being used instead of `task`.

"In the first play..." should be "In the first task..." and so on.

**Comment by geerlingguy** [comment]
Yikes! Not sure how that's made it through for all these years... I've fixed it in my local copy of the book, and the change will make its way to the next version on LeanPub soon!

Thanks for pointing this out.
