### ISSUE TITLE
Second Edition: an extra example requested (page 96)

### ISSUE THREAD

**Issue by aixtools** [geerlingguy/ansible-for-devops#443]
* On page 96 you show a debug task - displaying the variable `ansible_eth0`
* Later you show how to access an attribute of this variable:
```
{{ ansible_eth0.ipv4.address }}
{{ ansible_eth0['ipv4']['address'] }}
```
* I have a similar variable - with an element like:
{{ ansible_eth0.ipv6 }}

However, I have not figured out how to access ipv6 `address` of "fe80::..."

- In the debug information `ipv4` is { "address": "value", "netmask": "value", ... }
- but `ipv6` first element is `[ { "address": "value", ... } ], "macaddress": "value", ... 

I keep struggling over the additional `[ ...]` bracketing - and would really appreciate a concise explanation of this syntax.

Update: I want to make much more use of `ansible_facts` and use readily available information such as:
```
        "en0": {
            "device": "en0",
            "flags": [
                "UP",
                "BROADCAST",
                "NOTRAILERS",
                "RUNNING",
                "SIMPLEX",
                "MULTICAST",
                "GROUPRT",
                "64BIT",
                "CHECKSUM_OFFLOAD(ACTIVE)",
                "LARGESEND",
                "CHAIN"
            ],
            "ipv4": [
                {
                    "address": "192.168.129.64",
                    "broadcast": "192.168.129.255",
                    "netmask": "255.255.255.0",
                    "network": "192.168.129.0"
                },
                {
                    "address": "192.168.127.64",
                    "broadcast": "192.168.127.255",
                    "netmask": "255.255.255.0",
                    "network": "192.168.127.0"
                },
                {
                    "address": "10.1.0.77",
                    "broadcast": "10.1.1.255",
                    "netmask": "255.255.254.0",
                    "network": "10.1.0.0"
                }
            ],
            "ipv6": [
                {
                    "address": "fe80::fff1:feff:fea3:c744",
                    "prefix": "64"
                }
            ],
```
- I'd rather not have to take a course on Python programming to understand how to quickly work through dict(s) containing lists of dicts (containing dicts containing lists of dicts - or is it lists containing dicts of lists, etc..

**Comment by dglinder** [comment]
The additional `[...]` bracketing is because there are multiple IP addresses for the IPv6 section, but only a single IPv4 address is assigned to your NIC.

To refrence it, you need to tell Ansible which element to use like this:

      - name: "Show ipv6 address info for element 0"
        debug:
          var: ansible_ens33.ipv6.0.address

For my system, I have "ens33" for my NIC so the information is here:

        "ansible_ens33": {
            "active": true,
            "device": "ens33",
            "features": {
                "busy_poll": "off [fixed]",
                "fcoe_mtu": "off [fixed]"
            "ipv4": {
                "address": "192.168.1.11",
                "broadcast": "192.168.1.255",
                "netmask": "255.255.255.0",
                "network": "192.168.1.0"
            },
            "ipv6": [
                {
                    "address": "::0.101.1.35",
                    "prefix": "64",
                    "scope": "global"
                },
                {
                    "address": "fe80::9163:306b:459b:49ce",
                    "prefix": "64",
                    "scope": "link"
                }
            ],
        },

(Note, many lines omitted for brevity.)

When I run these tasks:

```
  tasks:
  - name: "Show ipv4 info"
    debug:
      var: ansible_ens33.ipv4

  - name: "Show ipv6 info"
    debug:
      var: ansible_ens33.ipv6

  - name: "Show ipv4 address info"
    debug:
      var: ansible_ens33.ipv4.address

  - name: "Show ipv6 address info for element 0"
    debug:
      var: ansible_ens33.ipv6.0.address
```

I get this output:

```
TASK [Show ipv4 info] **********************************************************
ok: [ansvm1] => {
    "ansible_ens33.ipv4": {
        "address": "192.168.1.11",
        "broadcast": "192.168.1.255",
        "netmask": "255.255.255.0",
        "network": "192.168.1.0"
    }
}

TASK [Show ipv6 info] **********************************************************
ok: [ansvm1] => {
    "ansible_ens33.ipv6": [
        {
            "address": "::0.101.1.35",
            "prefix": "64",
            "scope": "global"
        },
        {
            "address": "fe80::9163:306b:459b:49ce",
            "prefix": "64",
            "scope": "link"
        }
    ]
}

TASK [Show ipv4 address info] **************************************************
ok: [ansvm1] => {
    "ansible_ens33.ipv4.address": "192.168.1.11"
}

TASK [Show ipv6 address info for element 0] ************************************
ok: [ansvm1] => {
    "ansible_ens33.ipv6.0.address": "::0.101.1.35"
}

```

I have a gripe with Ansible in that the IP information is in a dictionary in one and a dictionary in a list for another.  I wish there was some consistency even if it meant that my `ipv4` section only had a single element and I had to use the `ipv4.0.address` notation all the time.  If I want to treat systems that have multiple IP addresses the same as those with a single IP address (per NIC), I have to take special care to pull out the proper information.  (But then, the "IACC" side of me says "You shouldn't be querying the system - you should have a record of what that system has/needs and set it accordingly."  My struggle betwee and declarative styles.)

**Comment by geerlingguy** [comment]
Agreed with @dglinder that this can be annoying (and I often end up with long chains of accesses with hardcoded list ID numbers in them... which I don't particularly enjoy). But since this is more of an Ansible support question and _slightly_ less related to the contents of the book, I'd recommend posting any more follow-ups into the Ansible subreddit, the Ansible Project mailing list, or one of Ansible's Matrix/IRC channels.

**Comment by aixtools** [comment]
I just thought, as it is a **common** syntax `switch`: _AND_ for someone new, easy to overlook (the added '[')

{ "itembit": "value" , ... "itembit_n": "value }
compared with:
[ { "itembit": "value" , ... "itembit_n": "value } ]

_And_ since you explain one syntax I thought it might be just as _enlightening_ to at least mention this.

And, yes, I had figured out the numeric (.X.) syntax, but the unsatisfactory bit with that is that I cannot be certain the numeric entry I want is _.0._ or _.N._.

In closing, I had kept the syntax example to IP addresses - but the issue I was struggling with had to do with storage and seeing how many free blocks were in a volume group - that is quite dynamic.

But an argument for scanning IP addresses is to confirm that the settings are as they should be, nothing additional, etc..

Again, it is your choice to ignore the difference. But I see it as a missed opportunity - or as confusion - why bother with the one, if ignoring the other.

FYI: I had not had a reason to look at the book in over a year. I recalled you did some examples and had had hopes. Now it seems, ripe for oblivion.

**Comment by aixtools** [comment]
> Agreed with @dglinder that this can be annoying (and I often end up with long chains of accesses with hardcoded list ID numbers in them... which I don't particularly enjoy). But since this is more of an Ansible support question and _slightly_ less related to the contents of the book, I'd recommend posting any more follow-ups into the Ansible subreddit, the Ansible Project mailing list, or one of Ansible's Matrix/IRC channels.

p.s. - adding this advice as a footnote - where to go if struggling with short introduction - is also a good addition.
p.p.s. or a _hyperlink_, _crossref_, whatever you want to call it - to appropriate material in your best-practices appendix.

In particular, the hyperlink makes you book more usable - imho.

- feedback: of the three "goto" locations mentioned above - only the ansible project is mentioned - as a footnote in the introduction - before any content even gets mentioned.
- personal preference: I actually went to ansible project, but regretted it as it still sends me email - even though I have unsubscribed several times. reddit (which is not mentioned at all in your book) is much better in not sending unsolicited comments, same for IRC - only when you are there.

- Your book was useful, but I see I am on my own now.
- Best wishes for your next edition.

**Comment by geerlingguy** [comment]
@aixtools - I may consider expanding more on the basics of extracting variables from ansible_facts and the like, but please don't take the closure of this issue personally, it's just that the topic of debugging + grabbing values from various places in Ansible's fact-gathering mess already takes me way more time than it should too...

**Comment by aixtools** [comment]
- (I) Don't take it personally.
- you are an author - and extremely experienced
- my humble goal is to give a peek into the novice's mind - and where it gets frustrating.
