### ISSUE TITLE
Second Edition, Chapter 3 external monitoring

### ISSUE THREAD

**Issue by fosstube** [geerlingguy/ansible-for-devops#445]
> you should probably also use an external monitoring solution like Pingdom or Server Check.in

Turns out servercheck.in has shut down, but they recommend a few alternatives on their website. 

- Uptime Robot - Free, Pro, and Enterprise plans
- Cronitor - Hacker (free), Business, and Enterprise plans
- Better Uptime - Basic (free), Freelancer, Small Team, and Business plans
- StatusCake - Free, Superior, and Business plans

**Comment by geerlingguy** [comment]
Ah, right you are! I'll try to get this fixed soon.

**Comment by geerlingguy** [comment]
This is fixed in the book's manuscript. I hope to have it in a book update very soon!
