### ISSUE TITLE
Chapter 4 - Drupal LAMP - php-apcu package instead of php7.4-apcu

### ISSUE THREAD

**Issue by MrPOC** [geerlingguy/ansible-for-devops#447]
In Chapter 4, on page 67, while writing the playbook config to install the Drupal LAMP setup in the playbook there is one mistake that leads to the playbook failing.

One of the listed package that needs to be installed is php-apcu. But as we added the ondrej/php PPA repo, it installs the latest PHP version as a requirement (currently is 8.1). This leads to having 2 php config (PHP 7.4 and PHP latest) installed on the playbook target with the default one being the "PHP latest" setup (php command becomes php 8.1 in my setup).

Unfortunately, as this undesired PHP version does not have the required PHP modules installed, it leads to another task, much later in the playbook (Create Drupal project), to fail (as composer is invoked with the default php executable with missing modules so it fails).

This is easily fixed by replacing php-apcu by php7.4-apcu in the listed packages to be installed by apt in the "Install Apache, MySQL, PHP, and other dependencies." task.

**Comment by geerlingguy** [comment]
Yeah... I've had to change that example a few times, and should probably get it updated for PHP 8.1 soon. I think the first version of the book was still back on PHP 5.6!

**Comment by MrPOC** [comment]
Yeah PHP versions move fast and those kind of problems happened to me not much long ago (asking apt to instead the generic php-* package instead of php<version>-* variant and having those update to the latest major PHP version at an unwanted time 😅)

**Comment by geerlingguy** [comment]
This has been fixed in this repo, and I have a fix set to go in the next book revision. Thanks!

**Comment by MrPOC** [comment]
Well thank you for your amazing book and lives on Ansible, it's so much fun to learn new tools with your content !
