### ISSUE TITLE
Chapter 7, Page 149 - Assertions tests with assert module fails

### ISSUE THREAD

**Issue by MrPOC** [geerlingguy/ansible-for-devops#456]
On page 149, in chapter 7, the first and second playbook presented are failing due to invalid Jinja syntax.
When trying to compare the my_color_choice with the string literal 'blue' (and '#0000ff' in the second playbook) you can't just write
`my_color_choice is 'blue'`
You could either replace the "is" with "==" or write `my_color_choice is eq 'blue'` or `my_color_choice is equalto 'blue'`
Hope it helps !

**Comment by geerlingguy** [comment]
Right you are! I've fixed this in the latest version of the book.
