### ISSUE TITLE
Second edition: Chapter 9 p. 224

### ISSUE THREAD

**Issue by duchaineo1** [geerlingguy/ansible-for-devops#457]
Hi, hope you're well.  

I've run into some issues in chapter 9 regarding digitalocean provisioning, it looks like the digitalocean api changed since publication, the JSON object returned after droplet creation is quite different from what the playbook expects see the [documentation](https://docs.digitalocean.com/reference/api/api-reference/#operation/create_droplet).  

The api also returns v4 ip address type in a random order. Sometimes the private ip address is first, sometimes second in the array. Since [this line](https://github.com/geerlingguy/ansible-for-devops/blob/386738f8a707adaac3bc6ecfc53310ba8eac7f1a/lamp-infrastructure/provisioners/digitalocean.yml#L33) in the provisioning script always takes the first  (and does not have the correct format anyway )

#### How to reproduce

I cloned [the project repository](git@github.com:geerlingguy/ansible-for-devops.git) and installed the requirements. Then ran `ansible-playbook provision.yml`

#### How To remedy

I changed the line mentionned above to add some logic, using the correct JSON object format: 
```Ansible
name: >-
  {{ item.1.data.droplet.networks.v4[0].ip_address if(item.1.data.droplet.networks.v4[0].type == 'public') 
  else item.1.data.droplet.networks.v4[1].ip_address }}
```
Once this change implemented the whole process went on without any errors. I assume it could also be resolved by setting private_networking to false but I have not tested it myself so far.

**Comment by geerlingguy** [comment]
I'm guessing this change was fixed with the 1.14 version—and if not, please open a new issue and I'll take a look again. Trying to get through a few older issues that would take a bit of extra time to re-verify.
