### ISSUE TITLE
Chapter 9, lamp-infrastructure example : Manual Apache restart needed to enable PHP support

### ISSUE THREAD

**Issue by MrPOC** [geerlingguy/ansible-for-devops#458]
I had to manually restart the Apache web server via an Ansible ad-hoc command after successfully running the configure.yml playbook for the first time (which was after several unsuccessful attempts due to typos and Vagrant on WSL2 not playing nice with any host-only network interface other than the default one). I must precise this is when running on the Vagrant VMs locally, but may be happening with the cloud providers, haven't tested it yet
So maybe it was due to the multiple failures in the middle of the playbook, or maybe something is not set up correctly in the upstream roles (geerlingguy.php, geerlingguy.apache) ? I don't know...

**Comment by dglinder** [comment]
> [...] (which was after several unsuccessful attempts due to typos and Vagrant on WSL2 not playing nice with any host-only network interface other than the default one).

This is the key part of why the restart didn't happen.

Your earlier runs probably did some work (i.e. "changes" to a configuration file, etc.) that would have set the Ansible notification to restart the Apache service, but a failure after the change but before the Apache restart would have stopped the action at the failure point.  (Ansible correctly assumes it's better to stop doing tasks - restarts included - when a failure is noticed.)

After the failure was corrected, the later runs didn't need to "change" anything (the configuration file was already correct from the earlier run), so the handler wasn't called and Apache wasn't restarted.

In your case, you were apparently executing and debugging a bit, so the system was in a weird state.  If you started from a fresh system with the "typos and Vagrant on WSL2" issues corrected, I'd bet the playbook would have restarted Apache as expected.

**Comment by dglinder** [comment]
(I suggest closing this as a non-issue.)

**Comment by MrPOC** [comment]
Yep, I retested now with the issues fixed and it worked like a charm.
Thank you for your answer and sorry for the inconvenience, this was a non-issue.
