### ISSUE TITLE
Chapter 9, lamp-infrastructure: 256MB may be too little RAM for the webservers

### ISSUE THREAD

**Issue by MrPOC** [geerlingguy/ansible-for-devops#460]
When running the lamp-infrastructure example with the Vagrant VMs, I had issues with the Vagrant shell provision task (sudo yum update -y) on the www1 VM (but not on www2 for some reason). But the playbook would fail on www2 when installing php-memcached.
Both issues were resolved by commenting the lines that would set the memory of these 2 VMs to 256MB, so maybe it's a bit too short to run CentOS 7 and perform the tasks that we want to do ? Although I didn't have those issues yesterday, which is strange...

**Comment by geerlingguy** [comment]
Right you are! I'm updating the manuscript and this will be in the next version of the book (I went to 512M, just to make sure there's headroom but also to preserve the RAM on some people's computers where they don't have a ton... some people still run ancient laptops :P
