### ISSUE TITLE
Chapter 9, lamp-infrastructure : Local Vagrant config has no MySQL master replication set up

### ISSUE THREAD

**Issue by MrPOC** [geerlingguy/ansible-for-devops#461]
In Chapter 9, when running the lamp-infrastructure on Vagrant VMs, there is no MySQL server set as "master" because we never define the mysql_replication_role variable. You can fix this by setting them in the inventory file, next to the hosts IP address in lamp_db group, but maybe there is a more proper way of doing this.
Here is what I did in my inventory file:
```ini
# [...] previous groups defined here
[lamp_db]
192.168.2.5 mysql_replication_role=master
192.168.2.6 mysql_replication_role=slave
# [...] other groups defined here
```

**Comment by geerlingguy** [comment]
Ah, thanks. I'll have to get that fixed!

**Comment by geerlingguy** [comment]
This is fixed in the manuscript and will be in the next update to the book. Thanks!

**Comment by MrPOC** [comment]
Thank you very much ! 
P.S. : When you have the time (I get that you're very busy, no problem) could you look at the issues others and I posted in the last couple days ? Thanks for your valuable time !
