### ISSUE TITLE
Chapter 3: Centos EOL

### ISSUE THREAD

**Issue by DiscoInfernoz** [geerlingguy/ansible-for-devops#462]
Following along in the chapter, using the adhoc command to install "chrony", I receive the following error for each server:

`[DEPRECATION WARNING]: Distribution centos 8.4.2105 on host 192.168.60.6 should use /usr/libexec/platform-python, but
 is using /usr/bin/python for backward compatibility with prior Ansible releases. A future Ansible release will 
default to using the discovered platform python for this host. See 
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information. This 
feature will be removed in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False 
in ansible.cfg.
192.168.60.6 | FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "msg": "Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist",
    "rc": 1,
    "results": []
`
It looks like this CENTOS version stopped getting support from RH at the end of 2021. 
Is there a way to fix this or should I start the vagrant configuration over with a newer version of CENTOS. (not sure how to do this)

**Comment by DiscoInfernoz** [comment]
I was able to continue with the rest of the chapter by changing the image pulled in the Vgrant file to the following:

https://app.vagrantup.com/centos/boxes/7

**Comment by DiscoInfernoz** [comment]
I suppose this is closed?

**Comment by geerlingguy** [comment]
See related: https://github.com/geerlingguy/ansible-for-devops/issues/453
