### ISSUE TITLE
Chapter 5 Page 99

### ISSUE THREAD

**Issue by HonkinWaffles** [geerlingguy/ansible-for-devops#463]
They hyperlink for "Magic Variables, and How To Access Information About Other Hosts" leads to a 404 on the ansible site.

URL: http://docs.ansible.com/playbooks_variables.html#magic-variables-and-how-to-access-information-about-other-hosts

**Comment by geerlingguy** [comment]
I'll have to get that updated. New link seems to be: https://docs.ansible.com/ansible/latest/user_guide/playbooks_vars_facts.html

**Comment by geerlingguy** [comment]
This has been fixed in the manuscript and will be in the next book update. Thanks!
