### ISSUE TITLE
Open Source Ansible for DevOps' manuscript

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-for-devops#473]
As I've met my 300-sponsor-goal on [GitHub Sponsors](https://github.com/sponsors/geerlingguy), I'm going to work on getting the manuscript of this book added to this repository, and _ideally_ also add some CI automation that publishes the book to the book's website, maybe at https://www.ansibleforkubernetes.com/book or something like that.

**Comment by geerlingguy** [comment]
As this is a text manuscript, and not necessarily _software_, I'm considering using either a CC license (is that even open source?), or maybe GPL v3... have to look into licensing a work like this.

I'll still be selling copies through LeanPub, Amazon, iBooks, etc. of course, but I'm considering setting the LeanPub version to either a lower price or free, while allowing people to pay still if they desire. I'll probably add a blurb in the preface, as well as a sponsorship note on the book's website, to highlight ways to sustain the book's continued development.

**Comment by JasonLG1979** [comment]
IMHO a CC license even if it's not technically Open Source(?[IANAL]) still lives up to the spirit of the promise.

**Comment by JasonLG1979** [comment]
Again IMHO [Attribution-NonCommercial 4.0 International](http://creativecommons.org/licenses/by-nc/4.0/) is at least very roughly equivalent to the GPL v3.

**Comment by geerlingguy** [comment]
FYI, this was done: https://github.com/geerlingguy/ansible-for-devops-manuscript
