### ISSUE TITLE
Keeping Galaxy and custom roles in ./roles

### ISSUE THREAD

**Issue by GarrisonD** [geerlingguy/ansible-for-devops#475]
Hi again 🙂 

I have been applying your recommendation about keeping roles not globally (`~/.ansible/roles`) but locally (`./roles`):

<img width="994" alt="Screenshot 2022-05-06 at 23 04 16" src="https://user-images.githubusercontent.com/13675895/167209576-e80cdbb3-bef5-4d8d-9968-46456f8ea845.png">

In the `./roles` directory I end up having:

- Galaxy roles (e. g. `geerlingguy.security`) that I want to be ignored by Git
- my custom roles (e.g. `tmux`, `netdata`) that I want to be tracked by Git

Adding Galaxy roles to .gitignore doesn't smell well 🙁

How do you tackle it?

**Comment by geerlingguy** [comment]
@GarrisonD - I usually add the roles to my gitignore (and since most that I use are geerlingguy the line is like `roles/geerlingguy.*`). For some projects I actually keep the roles in git, so I don't have to pull them down except when updating them. (Nice since Galaxy can be flaky sometimes).

**Comment by GarrisonD** [comment]
Oh, I totally forgot about wildcards in .gitignore 🤦 

I did as you said with a slight modification. I prefixed custom roles with `my.` and my .gitignore looks like:

```
roles/*
!roles/my.*
```

This way I won't have to get back to it again if some role named not like `geerlingguy.*` gets to the scene.

Thanks!
