### ISSUE TITLE
replace Vagrant by Terraform

### ISSUE THREAD

**Issue by Nurmukhamed** [geerlingguy/ansible-for-devops#476]
Hello Jeff.
Thank you for great book. 

I found that Vagrant is outdated and depricated. Also Vagrant requiring Virtualbox.

I'm use Ubuntu 20.04 with libvirt, kvm, terraform. 
If I share chapter examples with working terraform codes, would you to add them to new version of book?

**Comment by geerlingguy** [comment]
Please see: https://github.com/geerlingguy/ansible-for-devops/issues/404
