### ISSUE TITLE
Resource Not Found

### ISSUE THREAD

**Issue by jmiremba** [geerlingguy/ansible-for-devops#48]
When you do a "vagrant up", it fails with this:

> varnish: Downloading: https://atlas.hashicorp.com/geerlingguy/boxes/centos6/versions/1.1.4/providers/virtualbox.box
> An error occurred while downloading the remote file. The error
> message, if any, is reproduced below. Please fix this error and try
> again.
> The requested URL returned error: 404 Not Found

**Comment by geerlingguy** [comment]
Sorry about that! It should be fixed now. Please try again; the file on my box server was named incorrectly, but now it's correct.
