### ISSUE TITLE
Installing Drupal, last task

### ISSUE THREAD

**Issue by jhergeth** [geerlingguy/ansible-for-devops#488]
Hello Jeff,
this is not an issue but a question.
The last Task in the drupal playbook is to install drupal:
```
`- name: Install Drupal.
     command: >
     vendor/bin/drush si -y --site-name="{{ drupal_site_name }}"
      --account-name=admin
      --account-pass=admin
     --db-url=mysql://{{ domain }}:1234@localhost/{{ domain }}
     --root={{ drupal_core_path }}/web
      chdir={{ drupal_core_path }}
      creates={{ drupal_core_path }}/web/sites/default/settings.php
      notify: restart apache
      become_user: www-data
```

Shouldn't there be a when clause to make sure the task is idempotent?
In my opinion Ansible is not able to check if its neccessary to run this task.
In my understanding this task will be executed everytime the playbook is started ,independent from the fact, that the "drupal_site_name" may already exsist.

Or does drush handle this?

With regards
Joachim

p.s.: thanks for your great work!`

OK, forget about it. The creates= parameter......... sorry for the spam.

**Comment by jhergeth** [comment]
RTFM.......

**Comment by autogy** [comment]
I am getting below error 
TASK [Install Drupal.] *********************************************************
fatal: [default]: FAILED! => {"changed": false, "cmd": "vendor/bin/drush si -y '--site-name=Drupal Test' --account-name=admin --account-pass=admin '--db-url=mysql://drupal:********@localhost/drupal' --root=/var/www/drupal/web", "msg": "[Errno 2] No such file or directory: b'vendor/bin/drush'", "rc": 2, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
