### ISSUE TITLE
typo on page 384 -- heirarchy should be hierarchy

### ISSUE THREAD

**Issue by daniel-robitaille** [geerlingguy/ansible-for-devops#491]
Chapter 14.  Page 384  in the Let’s Encrypt with Ansible section.   Should be "hierarchy" instead of "heirarchy"

**Comment by geerlingguy** [comment]
Thanks for reporting this! I'll work on fixing it up in the next edition.

**Comment by geerlingguy** [comment]
Fixed, and will be on LeanPub soon!
