### ISSUE TITLE
The box 'geerlingguy/centos7' could not be found

### ISSUE THREAD

**Issue by Scizray** [geerlingguy/ansible-for-devops#494]
Hello I'm getting this error in vagrant version 2.3.0

Command I used:

vagrant init geerlingguy/centos7
vagrant up

```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'geerlingguy/centos7' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
The box 'geerlingguy/centos7' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Vagrant Cloud, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://vagrantcloud.com/geerlingguy/centos7"]
Error: schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
```

**Comment by geerlingguy** [comment]
Strange... the box is still there: https://app.vagrantup.com/geerlingguy/boxes/centos7

**Comment by geerlingguy** [comment]
I may try to rebuild the base boxes today and see if that helps.

**Comment by ossie-git** [comment]
As an alternative, you can use the **generic** repo which has most distros + supports most providers. Here's the link to the **centos7** one: https://app.vagrantup.com/generic/boxes/centos7

**Comment by riyazd19** [comment]
> As an alternative, you can use the **generic** repo which has most distros + supports most providers. Here's the link to the **centos7** one: https://app.vagrantup.com/generic/boxes/centos7

naa bro not working 
![image](https://user-images.githubusercontent.com/91775182/200606971-57afbeba-e044-40ec-8e72-cdf947a48227.png)

**Comment by rclilly** [comment]
Both of these boxes work for me. In one foldler I did `vagrant init geerlingguy/centos7` and then `vagrant up`. In another folder I did `vagrant init generic/centos7`, and then `vagrant up`. Both of them worked just fine. I'm on Windows 10 with Git Bash and VirtualBox 7.0. It also worked under Ubuntu on WSL 2. I'm located in the U.S., in case that makes a difference.

**Comment by Scizray** [comment]
> > As an alternative, you can use the **generic** repo which has most distros + supports most providers. Here's the link to the **centos7** one: https://app.vagrantup.com/generic/boxes/centos7
> 
> naa bro not working ![image](https://user-images.githubusercontent.com/91775182/200606971-57afbeba-e044-40ec-8e72-cdf947a48227.png)
This issue is related to certificate check.

`config.vm.box_download_insecure = true`

Add this in vagrantfile and it will work.

**Comment by DdeathCoder** [comment]
Heyy  @Scizray  are you logged in in vagrant ??

**Comment by Scizray** [comment]
> Heyy @Scizray are you logged in in vagrant ??

Yes, VM is up and running and I'm able to SSH into it.

**Comment by DdeathCoder** [comment]
So why the issue is open ?

**Comment by Scizray** [comment]
> So why the issue is open ?

I had forgotten about this and then someone posted about same issue, so kept open for awhile.

**Comment by KejiOyetunde** [comment]
I am also experiencing same issue... I was able to load the file but at the point of turning it up. i am getting same error
"default: Box 'geerlingguy/centos7' could not be found. Attempting to find and install..."
