### ISSUE TITLE
Chapter 2: yaml documentation link goes 404

### ISSUE THREAD

**Issue by cateee** [geerlingguy/ansible-for-devops#500]
On page 13, link 45: https://yaml.org/start.html is not working anymore. And I have no replacement link (I think now the links are versioned).

**Comment by geerlingguy** [comment]
Probably have to go to https://yaml.org/spec/1.2.2/ for now :/

Wish they redirected that link!

**Comment by geerlingguy** [comment]
Fixed and will be in the next release!
