### ISSUE TITLE
Chapter 1: incorrect name of package software-properties-common

### ISSUE THREAD

**Issue by mbart13** [geerlingguy/ansible-for-devops#505]
Hi Jeff,

In Chapter 1 on page 5 when you provide instructions to install Ansible on Debian/Ubuntu, in informational aside you mention package "python-software-properties", which I couldn't find. I think you are referring to "software-properties-common".

**Comment by geerlingguy** [comment]
Ha, good catch! I must've written that blurb back when Ubuntu 12.04 was the latest release. I've updated the manuscript and will update the published book in the next round of changes that I push out. Thanks!
