### ISSUE TITLE
Molecule commands in Chapter 13 are not working

### ISSUE THREAD

**Issue by elexwiz** [geerlingguy/ansible-for-devops#507]
The molecule command `molecule init role myrole` does not work. Molecule now requires a name using dot notation, e.g., `molecule init role my.test`. Additionally, it seems that using the word "role" in the name of role is prohibited. I tried numerous times to name the role `my.role`, but it failed every time. As soon as I changed the name to `my.test`, the role was created successfully.

I reached out to Jeff via Patreon and he asked me to submit this ticket.

**Comment by geerlingguy** [comment]
Thanks for reporting this! I'll definitely have to change the text to address this change in Molecule.

**Comment by geerlingguy** [comment]
I've fixed this in the book, but uncovered a fun little bug in Molecule along the way: https://github.com/ansible-community/molecule/issues/3935

Closing this issue, though—I think the new syntax `molecule init role my.test` should work fine.
