### ISSUE TITLE
lamp-infrastructure fails on varnish due to timeout

### ISSUE THREAD

**Issue by pgerhardt** [geerlingguy/ansible-for-devops#51]
Fails to install varnish with commands:

git clone https://github.com/geerlingguy/ansible-for-devops.git
cd ansible-for-devops/lamp-infrastructure
sudo ansible-galaxy install -r requirements.yml
vagrant up 
 
when running the lamp-infrastructure on macOS 10.12 with Ansible 2.2.0.0 and vagrant 1.9.1 with "vagrant up" Ansible fails to install Rails:

`TASK [geerlingguy.varnish : Install Varnish.] **********************************
fatal: [192.168.2.2]: FAILED! => {"changed": true, "failed": true, "msg": "https://repo.varnish-cache.org/redhat/varnish-4.1/el6/x86_64/varnish/varnish-4.1.4-1.el6.x86_64.rpm: [Errno 12] Timeout on https://repo.varnish-cache.org/redhat/varnish-4.1/el6/x86_64/varnish/varnish-4.1.4-1.el6.x86_64.rpm: (28, 'Operation too slow. Less than 1 bytes/sec transfered the last 30 seconds')\nTrying other mirror.\n\n\nError Downloading Packages:\n  varnish-4.1.4-1.el6.x86_64: failure: varnish/varnish-4.1.4-1.el6.x86_64.rpm from varnish-4.1: [Errno 256] No more mirrors to try.\n\n", "rc": 1, "results": ["Loaded plugins: fastestmirror\nSetting up Install Process\nLoading mirror speeds from cached hostfile\n * epel: mirror.steadfast.net\nResolving Dependencies\n--> Running transaction check\n---> Package varnish.x86_64 0:4.1.4-1.el6 will be installed\n--> Processing Dependency: jemalloc for package: varnish-4.1.4-1.el6.x86_64\n--> Processing Dependency: libjemalloc.so.1()(64bit) for package: varnish-4.1.4-1.el6.x86_64\n--> Running transaction check\n---> Package jemalloc.x86_64 0:3.6.0-1.el6 will be installed\n--> Finished Dependency Resolution\n\nDependencies Resolved\n\n================================================================================\n Package          Arch           Version              Repository           Size\n================================================================================\nInstalling:\n varnish          x86_64         4.1.4-1.el6          varnish-4.1         1.7 M\nInstalling for dependencies:\n jemalloc         x86_64         3.6.0-1.el6          epel                100 k\n\nTransaction Summary\n================================================================================\nInstall       2 Package(s)\n\nTotal download size: 1.8 M\nInstalled size: 6.6 M\nDownloading Packages:\n"]}`

Looks like:  https://repo.varnish-cache.org/redhat/varnish-4.1/el6/x86_64/varnish/varnish-4.1.4-1.el6.x86_64.rpm is inaccessible and there's no mirrors for it to find an alt. Maybe this is just transient?

**Comment by pgerhardt** [comment]
....and after being offline all day it's suddenly back.

**Comment by geerlingguy** [comment]
@pgerhardt - Thanks for following up! Yeah, the Varnish repos are maintained by Varnish directly, and from time to time they seem to go unreachable for a little bit.
