### ISSUE TITLE
Vagrant alternatives? Docker? Blocked by M1/M2 issues

### ISSUE THREAD

**Issue by blue928** [geerlingguy/ansible-for-devops#510]
Hi Jeff,

Great book, but I'm completely blocked from using it. Can't use Vagrant in the legacy / air-gapped Intel environment I'm working in, and every other system I have is M1/M2. 

I noticed you too were struggling with this: https://github.com/geerlingguy/ansible-for-devops/issues/404 Did you ever find a way around it?

I can use docker / podman. Basically, looking for the equivalent 'docker-compose.yml' versions of all your Vagrant scripts from Ch03 on. Have you been working on anything like that or can you suggest alternatives?

Thanks,

Blue

**Comment by geerlingguy** [comment]
See #404 - One option is Tart, though it's not currently as easily automatable as Vagrant + VirtualBox (though efforts are being made).

The one challenge to the Docker approach is there's no networking support to make it behave like real VMs/machines with dedicated IP addresses, so the networking model breaks a bit (compared to Docker-style/container deployments).

But we'll see. All the discussion should end up in #404 though.
