### ISSUE TITLE
Chapter 3 - Discrepancy between Book and GitHub Code

### ISSUE THREAD

**Issue by TrisBits** [geerlingguy/ansible-for-devops#520]
When working through the examples in Chapter 3, I copied the example code from GitHub for Chapter 3 (https://github.com/geerlingguy/ansible-for-devops/tree/master/orchestration).

I noticed that the IP addresses for the VMs don't match between the code on GitHub and the book.

Book:  192.168.60.4, 192.168.60.5, 192.168.60.6
GitHub:  192.168.56.4, 192.168.60.5, 192.168.56.6

This caused a minor hiccup when running the example from the book:  
ansible app -b -a "service chronyd restart" --limit "192.168.60.4"

Also wanted to say thank you for the excellent book, I've been enjoying it a lot.

**Comment by TrisBits** [comment]
Submitted a PR (#521) for this.

**Comment by geerlingguy** [comment]
I actually updated those IP addresses just recently due to some changes in Vagrant, requiring the new IP ranges. I haven't had time to publish an updated version of the book manuscript yet, but will hopefully do so early this year.
