### ISSUE TITLE
drupal playbook error

### ISSUE THREAD

**Issue by autogy** [geerlingguy/ansible-for-devops#524]
when i ran drupal playbook  gettin error at install drupal step

`- name: Install Drupal.
     command: >
     vendor/bin/drush si -y --site-name="{{ drupal_site_name }}"
      --account-name=admin
      --account-pass=admin
     --db-url=mysql://{{ domain }}:1234@localhost/{{ domain }}
     --root={{ drupal_core_path }}/web
      chdir={{ drupal_core_path }}
      creates={{ drupal_core_path }}/web/sites/default/settings.php
      notify: restart apache
      become_user: www-data

I am getting below error

TASK [Install Drupal.] *********************************************************
fatal: [default]: FAILED! => {"changed": false, "cmd": "vendor/bin/drush si -y '--site-name=Drupal Test' --account-name=admin --account-pass=admin '--db-url=mysql://drupal:********@localhost/drupal' --root=/var/www/drupal/web", "msg": "[Errno 2] No such file or directory: b'vendor/bin/drush'", "rc": 2, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}

**Comment by ronsmits** [comment]
According to the output the file `vendor/bin/drush` does not exist. are you sure the path is correct?

**Comment by autogy** [comment]
> According to the output the file `vendor/bin/drush` does not exist. are you sure the path is correct?

I am not sure. I am new to Ansible, was following instruction mentioned in github and "ansible-for-devops" by Jeff Geerling. Tried debugging on my own, could  not find a solution.

**Comment by voegelas** [comment]
Did you try to install PHP 7.4 and Drush 10? PHP 7.4 reached its end of life last year and is no longer supported by Drupal. See #526 for a fix that updates PHP to version 8.2 and Drush to version 11.

**Comment by Trugamr** [comment]
> Did you try to install PHP 7.4 and Drush 10? PHP 7.4 reached its end of life last year and is no longer supported by Drupal. See #526 for a fix that updates PHP to version 8.2 and Drush to version 11.

Thanks this fixed it for me!

**Comment by geerlingguy** [comment]
This should hopefully be fixed as part of https://github.com/geerlingguy/ansible-for-devops/pull/526 (changing to PHP 8.2 and Drush 11).
