### ISSUE TITLE
Long options in examples == self documenting

### ISSUE THREAD

**Issue by ElijahLynn** [geerlingguy/ansible-for-devops#53]
Love the book so far. One suggestion I would like to make is to use long options instead of short options when possible. This has the benefit of teaching me what the commands do.

An example is:
`ansible example --args="free --mega" --user=[username]`

instead of:
`ansible example -a "free -m" -u [username]`

In the long option example I can get some useful information out of the command without having to look at a man page. I can imply that `free --mega` might mean megabytes where as with `free -m` I thought it just meant memory. 

I would be happy to help contribute to overhauling the book to improve all the examples with more readable, self-documenting long options.

**Comment by geerlingguy** [comment]
I agree here—for the most part, I like to use long options in any examples, and then mention the alias in a comment, then start using the alias for the rest of the book. I usually do that for acronyms in general writing, and this is a good reminder to do the same for command examples!

**Comment by ElijahLynn** [comment]
Okay, I will take what I can get!

I will say that your improved approach relies on 2 assumptions:
1. The student has an excellent memory, with the ability to memorize something the first time they see it
1. The student will have read the book serially, not skipping ahead at all

I think an ideal approach would be to offer a long first and short example second/below.

**Comment by Silthanis** [comment]
I think there are actually several reasons to prefer short options after the first exposure (at least for shell commands):

1.  I mostly read on a small form-factor device.  Long options with every example get unreadable fairly quickly when there are several options per line.
2. Even with flag tab completion in a decent shell, realistically I'm not going to be typing long options - so becoming familiar with the short versions is actually more useful (though to be fair, long options in code and scripts should be preferred)
3. I can't rely on coworkers or other contributors consistently using long options, so not being used to reading them becomes a maintenance problem
4. Getting used to looking up flags is going to be more helpful to the student than handholding through the book that won't be available in practice

I'm just starting to read through, but what I would hope to see would be long options on the first exposure (with alias in a comment), short options only in subsequent shell examples, and long options every time in script, code, or YAML to encourage good code readability habits.

**Comment by geerlingguy** [comment]
I'm actually going to leave things as-is for the time being. Especially because of:

> I mostly read on a small form-factor device.

Looking at the formatting on Kindle and most devices (besides the print book... but even then...), any lines which break to a new line, especially for ad-hoc commands, can get a bit unwieldy.

It's also harder to maintain the examples which break lines and also to test them (since they can't be copy/pasted as easily.
