### ISSUE TITLE
CentOS 8 End-of-life - Chapter 3 error when "Making changes using Ansible modules"

### ISSUE THREAD

**Issue by paul-jewell** [geerlingguy/ansible-for-devops#534]
Following the command on page 28:
`$ ansible multi -b -m yum -a "name=chrony state=present"`

The following error occurs for each server:

`
192.168.60.5 | FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/libexec/platform-python"
    },
    "changed": false,
    "msg": "Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist",
    "rc": 1,
    "results": []
}
`

This appears to be related to the end-of-life status of CentOS, and removal of the repos from the official mirrors. Details here: 
[(https://forketyfork.medium.com/centos-8-no-urls-in-mirrorlist-error-3f87c3466faa)]

See below for how I executed these commands via ansible.

Maybe your vagrant file geerlingguy/centos8 needs updating so the book commands work as expected? If I knew how to do this, I would make it so to avoid you having to do it.

Thanks Jeff!

**Comment by paul-jewell** [comment]
I have found a way to send the commands to the servers from the command line:
First command:
`ansible multi -b -a "bash -c \"sed -i -e 's|mirrorlist=|#mirrorlist=|g' /etc/yum.repos.d/CentOS-*\""`

Second command:
`ansible multi -b -a "bash -c \"sed -i -e 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*\""`

This configures the servers to work with the yum commands in the book. I now need to see if they should be applied each time I bring the servers up (I suspect they do, and they should be in a playbook...[I'm very new to this!!).

**Comment by geerlingguy** [comment]
The Vagrantfile for that example should now read `config.vm.box = "geerlingguy/rockylinux8"`, so that would make this work properly (since it is supported).

Thanks for reporting, especially following up with a workaround! The latest editions of the book seem to be correct here.
