### ISSUE TITLE
Cosmetic issue: Wrong distro referenced

### ISSUE THREAD

**Issue by dropsignal** [geerlingguy/ansible-for-devops#539]
Taken from the Leanpub version 2022-04-15, under the section titled "Real-world playbook: Rocky Linux Node.js app server", under the heading titled "Add extra repositories", on page 57, RHEL is referenced instead of Rocky Linux.

The line reads: these examples presume you're running RHEL 8 as the root user

**Comment by geerlingguy** [comment]
Thanks! I have this fixed and a new version will be up on LeanPub shortly. I will push it up to Amazon and iBooks soon after.
