### ISSUE TITLE
`ansible up` ==     default: Warning: Connection timeout. Retrying...      

### ISSUE THREAD

**Issue by ElijahLynn** [geerlingguy/ansible-for-devops#54]
Host Ubuntu 14.04, ansible 2.2.0.0, vboxmanage 4.3.36_Ubuntur105129

When doing an `ansible up` I get a 

> Bringing machine 'default' up with 'virtualbox' provider...                      
==> default: Importing base box 'geerlingguy/centos7'...                         
==> default: Matching MAC address for NAT networking...                          
==> default: Checking if box 'geerlingguy/centos7' is up to date...              
==> default: Setting the name of the VM: vagrant_default_1488056506230_50292     
==> default: Clearing any previously set network interfaces...                   
==> default: Preparing network interfaces based on configuration...              
    default: Adapter 1: nat                                                      
==> default: Forwarding ports...                                                 
    default: 22 => 2222 (adapter 1)                                              
==> default: Booting VM...                                                       
==> default: Waiting for machine to boot. This may take a few minutes...         
    default: SSH address: 127.0.0.1:2222                                         
    default: SSH username: vagrant                                               
    default: SSH auth method: private key                                        
    default: Warning: Connection timeout. Retrying...                            
    default: Warning: Connection timeout. Retrying...                            
    default: Warning: Connection timeout. Retrying...                            
    default: Warning: Connection timeout. Retrying...                            

This answer to use the GUI prompt to choose default|safe mode does get me past that stage. http://stackoverflow.com/a/22575302/292408. 

```
config.vm.provider :virtualbox do |vb|
  vb.gui = true
end
```

In addition `vagrant ssh` doesn't appear to work, not sure if it is related or not.

**Comment by geerlingguy** [comment]
For that, I'm not sure why it would be broken currently. The latest box builds I've published on Vagrant Cloud/Atlas seem to work okay for me. Also, this issue would probably be best opened against the repo dealing with the `centos7` Packer build: https://github.com/geerlingguy/packer-centos-7/issues

One other thing... I know that if you're running Ubuntu 14.04 as your host OS, there could be some issues there. See in particular this page from the Drupal VM docs: http://docs.drupalvm.com/en/latest/getting-started/installation-linux/

I've only regularly test the box using host OSes Ubuntu 16.04, Fedora 24/25, Windows 10/8, and macOS 10.12/10.11.

**Comment by ElijahLynn** [comment]
Moved to https://github.com/geerlingguy/packer-centos-7/issues/21

**Comment by geerlingguy** [comment]
We'll continue the discussion over there.
