### ISSUE TITLE
TASK [Install Drush dependencies with Composer.] *******************************

### ISSUE THREAD

**Issue by francesd919** [geerlingguy/ansible-for-devops#540]
Stuck on the above task.... it won't go futher

**Comment by billsensei** [comment]
Same here. Tried changing php7.4* > php8.1* but didn't worked. Any suggestions?

**Comment by billsensei** [comment]
Here is the error message I get:

fatal: [default]: FAILED! => {"changed": false, "msg": "./composer.json has been updated Running composer update drush/drush Loading composer repositories with package information Cannot create cache directory /var/www/.cache/composer/repo/https---packages.drupal.org-8/, or directory is not writable. Proceeding without cache. See also cache-read-only config if your filesystem is read-only. Cannot create cache directory /var/www/.cache/composer/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache. See also cache-read-only config if your filesystem is read-only. Info from https://repo.packagist.org: #StandWithUkraine Updating dependencies Your requirements could not be resolved to an installable set of packages. Problem 1 - drupal/core 10.0.9 requires php >=8.1.0 -> your php version (7.4.33) does not satisfy that requirement. - drupal/core-recommended 10.0.9 requires drupal/core 10.0.9 -> satisfiable by drupal/core[10.0.9]. - drupal/core-recommended is locked to version 10.0.9 and an update of this package was not requested. Installation failed, reverting ./composer.json and ./composer.lock to their original content.", "stdout": "./composer.json has been updated\nRunning composer update drush/drush\nLoading composer repositories with package information\nCannot create cache directory /var/www/.cache/composer/repo/https---packages.drupal.org-8/, or directory is not writable. Proceeding without cache. See also cache-read-only config if your filesystem is read-only.\nCannot create cache directory /var/www/.cache/composer/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache. See also cache-read-only config if your filesystem is read-only.\nInfo from https://repo.packagist.org: #StandWithUkraine\nUpdating dependencies\nYour requirements could not be resolved to an installable set of packages.\n\n  Problem 1\n    - drupal/core 10.0.9 requires php >=8.1.0 -> your php version (7.4.33) does not satisfy that requirement.\n    - drupal/core-recommended 10.0.9 requires drupal/core 10.0.9 -> satisfiable by drupal/core[10.0.9].\n    - drupal/core-recommended is locked to version 10.0.9 and an update of this package was not requested.\n\n\nInstallation failed, reverting ./composer.json and ./composer.lock to their original content.\n", "stdout_lines": ["./composer.json has been updated", "Running composer update drush/drush", "Loading composer repositories with package information", "Cannot create cache directory /var/www/.cache/composer/repo/https---packages.drupal.org-8/, or directory is not writable. Proceeding without cache. See also cache-read-only config if your filesystem is read-only.", "Cannot create cache directory /var/www/.cache/composer/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache. See also cache-read-only config if your filesystem is read-only.", "Info from https://repo.packagist.org: #StandWithUkraine", "Updating dependencies", "Your requirements could not be resolved to an installable set of packages.", "", "  Problem 1", "    - drupal/core 10.0.9 requires php >=8.1.0 -> your php version (7.4.33) does not satisfy that requirement.", "    - drupal/core-recommended 10.0.9 requires drupal/core 10.0.9 -> satisfiable by drupal/core[10.0.9].", "    - drupal/core-recommended is locked to version 10.0.9 and an update of this package was not requested.", "", "", "Installation failed, reverting ./composer.json and ./composer.lock to their original content."]}

**Comment by tbohlender** [comment]
I've got the same issue. Would be nice, if anyone can help with that.

**Comment by geerlingguy** [comment]
This should hopefully be fixed as part of https://github.com/geerlingguy/ansible-for-devops/pull/526 (changing to PHP 8.2 and Drush 11).
