### ISSUE TITLE
"includes" example fails provisioning

### ISSUE THREAD

**Issue by cwardgar** [geerlingguy/ansible-for-devops#57]
```
TASK [Add ondrej repository for later versions of PHP.] ************************
fatal: [default]: FAILED! => {"changed": false, "failed": true, "msg": "failed to fetch PPA information, error was: HTTP Error 404: Not Found"}
```

**Comment by geerlingguy** [comment]
@cwardgar - Thanks for letting me know! I'm working through a bugfix pass in the book examples for https://github.com/geerlingguy/ansible-for-devops/issues/61, so I'm going to close this issue and move it over there—this particular example needs a few different updates to work correctly.

**Comment by geerlingguy** [comment]
See commit 96de03e above for the changes required to get it working. And thanks again for reporting!
