### ISSUE TITLE
Icons washed out in dark mode (epub)

### ISSUE THREAD

**Issue by AndrewO** [geerlingguy/ansible-for-devops#587]
In the Preface when the aside icons are defined (right before the link to these issues funny enough), they're pretty washed out if you use dark mode on iOS. I don't know epub, but I'd assume there's a way to substitute light versions like you can on the web?

![image](https://github.com/geerlingguy/ansible-for-devops/assets/550/d727b785-5cf6-446f-9e35-3a7a19f6edf6)

My Books theme: ![image](https://github.com/geerlingguy/ansible-for-devops/assets/550/b5e58d15-3cd5-4e90-ac3d-7578b1cc0bb5)

**Comment by geerlingguy** [comment]
Unfortunately I don't have much control over that—I would consider sending this report to LeanPub's support as they might have a way to tweak the published book for dark mode compatibility: https://leanpub.com/u/leanpub-support

**Comment by AndrewO** [comment]
Got it. I'll follow up with them.
