### ISSUE TITLE
python 3.11

### ISSUE THREAD

**Issue by typ-ex** [geerlingguy/ansible-for-devops#588]
I'm trying to read the book again to help some friends out who are reading it.  When I last attempted it python3.11 was the latest version and opening up a vagrant instance running on the centos container and python 3.6 stuff was broken.  Hoping to attempt installing python3.6 venv will cause it all to work.

**Comment by geerlingguy** [comment]
See related: https://github.com/geerlingguy/ansible-for-devops/issues/589
