### ISSUE TITLE
Incorrect `image_id` for `provisioners/digital_ocean.yml` in Chapter 8

### ISSUE THREAD

**Issue by mattjmcnaughton** [geerlingguy/ansible-for-devops#59]
First off, love the book! Have really enjoyed working my way through it.

One small note, I'm getting the error `Failure talking to yum: Cannot retrieve repository metadata (repomd.xml) for repository: varnish-4.1. Please verify its path and try again"` when trying to run `provision.yml` in the Chapter 8 Lamp Infrastructure Digital Ocean example. I believe the issue is that the digital ocean `image_id` in `provisioners/digital_ocean.yml` is `'centos-6-5-x32'`. However, there is no x32 image for Varnish (based on my understanding of https://repo.varnish-cache.org/redhat/varnish-4.1/el6/). There is however an `x64` image. 

This error can be fixed by updating the `image_id` to `centos-6-5-x64`.

Thanks again for a fantastic book!

**Comment by geerlingguy** [comment]
I'm going to take a look at this during the weekend and hopefully get it updated. Thanks!
