### ISSUE TITLE
Potential License Compliance Issues

### ISSUE THREAD

**Issue by LicViolationchecker** [geerlingguy/ansible-for-devops#592]
Hi there,

I hope you’re doing well. I wanted to bring to your attention a couple of potential license compliance issues related to the third-party libraries in your project.

For example:

    Library: ConfigParser - License: MIT
    Potential Issue: The MIT license requires that the original copyright notice be included with any distribution of the software, and that the source code is made available. Additionally, any derivative works must be distributed under the same license.

    Library: Requests - License: Apache-2.0
    Potential Issue: The Apache-2.0 license mandates that the original copyright notice be included with any distribution of the software, along with making the source code available. Derivative works should also be distributed under the same license.

Here’s a quick summary of the typical requirements for these licenses:

    MIT License:
        Include the original copyright notice in any distribution.
        Make the source code available.
        Distribute derivative works under the same license.
        Include the license itself with any distribution.
        Add a notice file with copyright and licensing info.

    Apache-2.0 License:
        Include the original copyright notice in any distribution.
        Make the source code available.
        Distribute derivative works under the same license.
        Include the license itself with any distribution.
        Add a notice file with copyright and licensing info.

I would recommend reviewing these points to ensure everything is in compliance. It’s important to double-check, and if it turns out there’s no issue, that’s great!

Thanks for your attention to this and for all the work you put into maintaining this project.

Best regards,

**Comment by geerlingguy** [comment]
I don't embed the code for either of those projects in this repository, so I don't know what kind of licensing issues I could be running into—my code _uses_ those libraries, but it is up to the application user to install the libraries themselves.
