### ISSUE TITLE
`rolling-deploy` example relies on `nodejs_forever` which was removed from `geerlingguy.nodejs`

### ISSUE THREAD

**Issue by mattjmcnaughton** [geerlingguy/ansible-for-devops#60]
I was working my way through the `rolling-deploy` example and noticed that any commands involving `forever` failed with `'No such file or directory'`. I then noticed that [this commit](https://github.com/geerlingguy/ansible-role-nodejs/commit/d985c528d5c5392c04afad463695fb5eece8b321) to `geerlingguy.nodejs` removed the `nodejs_forever` variable. However, `rolling-deploy` still sets `nodejs_forever: true` in `provision.yml` to install `forever`.

What is the best way to install`forever` with the newest version of the `geerlingguy.nodejs` role.

Thanks for an awesome book :)

**Comment by geerlingguy** [comment]
Oops! I'll have to fix that. The best way to get it installed in the mean time is with:

```yaml
nodejs_npm_global_packages:
  - forever
```

Or with a version:

```yaml
nodejs_npm_global_packages:
  - name: forever
    version: 0.15.3
```

**Comment by mattjmcnaughton** [comment]
Thanks for the quick response! Unfortunately, I tried adding this variable to `provision.yml`, and I'm still getting the same error message. When I ssh'd to the vagrant machine with `vagrant ssh`, I noticed that `forever` was available when I was running as the `vagrant` user, but not when I was `root`. And if I'm understanding correctly, the ansible playbook runs as `root`. But I thought that installing the package globally would have also installed it for `root`?

Thanks for your help :)

**Comment by geerlingguy** [comment]
@mattjmcnaughton - I'm taking a look at this now.

**Comment by geerlingguy** [comment]
Yeah, in this case it looks like there's some extra trickery going on to get forever into the path `/usr/local/lib/npm/bin/forever`, and when I use `sudo` it's not in my path.

Two options are to:

  1. Doubly ensure that global packages are installed under the `sudo` user (in which case it goes to `/usr/bin/forever` and is accessible everywhere) (maybe there's a bug in my role?)
  2. Run the app deployment as the `ansible_ssh_user` instead of using `sudo`/become.

**Comment by geerlingguy** [comment]
@mattjmcnaughton - Aha! It looks like I had to set the following vars:

```yaml
    npm_config_prefix: "/usr"
    nodejs_npm_global_packages:
      - forever
```

Because that new config prefix is the parent directory inside which Node.js' global installs will be in the `bin`. Pushing up a fix soon, and I'll fix it in the book as well.
