### ISSUE TITLE
I want  add dynamic ipaddress at runtime   in place 192.168.28.71 I want to use like ansible -i inventory.py argument 

### ISSUE THREAD

**Issue by mvvpavan** [geerlingguy/ansible-for-devops#64]
It is not bug, I want to pass argument at run time is it possible. 

```python
#!/usr/bin/env python

'''
Example custom dynamic inventory script for Ansible, in Python.
'''

import os
import sys
import argparse

try:
    import json
except ImportError:
    import simplejson as json

class ExampleInventory(object):

    def __init__(self):
        self.inventory = {}
        self.read_cli_args()

        # Called with `--list`.
        if self.args.list:
            self.inventory = self.example_inventory()
        # Called with `--host [hostname]`.
        elif self.args.host:
            # Not implemented, since we return _meta info `--list`.
            self.inventory = self.empty_inventory()
        # If no groups or vars are present, return empty inventory.
        else:
            self.inventory = self.empty_inventory()

        print json.dumps(self.inventory);

    # Example inventory for testing.
    def example_inventory(self):
        return {
            'group': {
                'hosts': ['192.168.28.71', '192.168.28.72'],
                'vars': {
                    'ansible_ssh_user': 'vagrant',
                    'ansible_ssh_private_key_file':
                        '~/.vagrant.d/insecure_private_key',
                    'example_variable': 'value'
                }
            },
            '_meta': {
                'hostvars': {
                    '192.168.28.71': {
                        'host_specific_var': 'foo'
                    },
                    '192.168.28.72': {
                        'host_specific_var': 'bar'
                    }
                }
            }
        }

    # Empty inventory for testing.
    def empty_inventory(self):
        return {'_meta': {'hostvars': {}}}

    # Read the command line args passed to the script.
    def read_cli_args(self):
        parser = argparse.ArgumentParser()
        parser.add_argument('--list', action = 'store_true')
        parser.add_argument('--host', action = 'store')
        self.args = parser.parse_args()
```

Get the inventory.

```
ExampleInventory()****
```

**Comment by geerlingguy** [comment]
I'm trying to figure out exactly what the question is here—in this particular script, I'm just hardcoding a couple addresses (in the `example_inventory()` function), and then printing them out.

If you want to adapt this particular Python script to your own infrastructure, and print out a dynamic list of hosts/variables, then you'd need to modify the script to do that—either grab data from a database, get data from something like AWS or DigitalOcean, etc.

This particular script is just meant as a super-basic example to show how inventory scripts are made.

**Comment by mvvpavan** [comment]
Thanks for response, As you suggested I send the hosts/variables to the database. How I has to call the particular host and group for that inventory file. example:
main.yml
- hosts: group
   roles:
    - java_installation

ansible-playbook inventory main.yml

I don't want to add the host inside the main.yml
host and group should decided at run time 
How to pass the input to this  example_inventory() is it possible to pass inventory when i am running the 
ansible-playbook inventory main.yml
Ex: In database for group have 5 server. but I want to pick single server form the group and ran the roles 

[group]
10.2.3.4. 
10.2.3.5
I want to run  the role in 10.2.3.5 
Can you please help me on that. Sorry if there is problem on my communication.

**Comment by dglinder** [comment]
@mvvpavan I believe you will get more assistance if you join an Ansible specific group (e.g. the Ansible Project on Google Groups), or post your question on StackOverflow.com and tag it with "Ansible".  Jeff is a great guy and good writer, but this specific GitHub location is really best suited for working through bugs in the code.
When you find your answer, come back here and update with the response to help Jeff clarify his examples in a future release of the book.

**Comment by mvvpavan** [comment]
Thanks Daniel, As you suggest I will post in stack and google group. Once if I got the information,  Definitely  I will add in comment.

**Comment by geerlingguy** [comment]
Closing out this issue since hopefully the Google Group discussion may be able to get a little further.
