### ISSUE TITLE
Ansible's service module failing for Ubuntu

### ISSUE THREAD

**Issue by philipobrien** [geerlingguy/ansible-for-devops#67]
I'm working through the book and currently setting up the three VMs in Chapter 3 (except I'm using Ubuntu on them as opposed to CentOS). 

Installing the NTP daemon works

![image](https://user-images.githubusercontent.com/1763813/29176986-6423a860-7de5-11e7-874a-dd3daded04a7.png)

but the command to check the daemon is running fails

![image](https://user-images.githubusercontent.com/1763813/29177017-7ea59ba8-7de5-11e7-9d22-eb5f6b0d8f8f.png)

Possibly related to https://github.com/ansible/ansible-modules-core/issues/915?

**Comment by AnderEnder** [comment]
Package is ntp, so the service is "ntp", instead of "ntpd".

**Comment by philipobrien** [comment]
How did I miss that. Thanks. Typo in the book I think as the code given is

```
$ ansible multi -b -m yum -a "name=ntp state=present"
$ ansible multi -b -m service -a "name=ntpd state=started enabled=yes"
```

**Comment by geerlingguy** [comment]
I'll take a look at this, thanks for opening the issue!

**Comment by geerlingguy** [comment]
@philipobrien - so, this is one of the many little cases where the difference between RHEL-derivatives and Debian-derivatives can trip you up...

On Debian/Ubuntu:

  - Package is `ntp`
  - Service is `ntp`

On RHEL/Fedora/CentOS:

  - Package is `ntp`
  - Service is `ntpd`

See how I set the `ntp_daemon` OS-specific here: https://github.com/geerlingguy/ansible-role-ntp/tree/master/vars
