### ISSUE TITLE
http-parse is necessary when installing nodejs

### ISSUE THREAD

**Issue by ythalorossy** [geerlingguy/ansible-for-devops#69]
The problem is that **http-parser** is not provider by epel:

Check this thread:
https://bugs.centos.org/view.php?id=13669&nbn=7

`fatal: [192.168.60.5]: FAILED! => {"changed": true, "failed": true, "msg": "Error: Package: 1:nodejs-6.11.1-1.el7.x86_64 (epel)\n           Requires: libhttp_parser.so.2()(64bit)\nError: Package: 1:nodejs-6.11.1-1.el7.x86_64 (epel)\n           Requires: http-parser >= 2.7.0\n", "rc": 1, "results": ["Loaded plugins: fastestmirror\nLoading mirror speeds from cached hostfile\n * base: mirrors.centos.webair.com\n * epel: mirror.cogentco.com\n * extras: mirror.math.princeton.edu\n * remi-safe: repo1.ash.innoscale.net\n * updates: mirror.wdc1.us.leaseweb.net\nResolving Dependencies\n--> Running transaction check\n---> Package npm.x86_64 1:3.10.10-1.6.11.1.1.el7 will be installed\n--> Processing Dependency: nodejs = 1:6.11.1-1.el7 for package: 1:npm-3.10.10-1.6.11.1.1.el7.x86_64\n--> Running transaction check\n---> Package nodejs.x86_64 1:6.11.1-1.el7 will be installed\n--> Processing Dependency: libuv >= 1:1.9.1 for package: 1:nodejs-6.11.1-1.el7.x86_64\n--> Processing Dependency: http-parser >= 2.7.0 for package: 1:nodejs-6.11.1-1.el7.x86_64\n--> Processing Dependency: libuv.so.1()(64bit) for package: 1:nodejs-6.11.1-1.el7.x86_64\n--> Processing Dependency: libicuuc.so.50()(64bit) for package: 1:nodejs-6.11.1-1.el7.x86_64\n--> Processing Dependency: libicui18n.so.50()(64bit) for package: 1:nodejs-6.11.1-1.el7.x86_64\n--> Processing Dependency: libicudata.so.50()(64bit) for package: 1:nodejs-6.11.1-1.el7.x86_64\n--> Processing Dependency: libhttp_parser.so.2()(64bit) for package: 1:nodejs-6.11.1-1.el7.x86_64\n--> Running transaction check\n---> Package libicu.x86_64 0:50.1.2-15.el7 will be installed\n---> Package libuv.x86_64 1:1.10.2-1.el7 will be installed\n---> Package nodejs.x86_64 1:6.11.1-1.el7 will be installed\n--> Processing Dependency: http-parser >= 2.7.0 for package: 1:nodejs-6.11.1-1.el7.x86_64\n--> Processing Dependency: libhttp_parser.so.2()(64bit) for package: 1:nodejs-6.11.1-1.el7.x86_64\n--> Finished Dependency Resolution\n You could try using --skip-broken to work around the problem\n You could try running: rpm -Va --nofiles --nodigest\n"]}
`

**Comment by ythalorossy** [comment]
I fixed this updating the playbook.yml

`
    - name: Install http-parser from a remote repo
      yum: name={{ item }} state=present
      with_items:
        - https://kojipkgs.fedoraproject.org//packages/http-parser/2.7.1/3.el7/x86_64/http-parser-2.7.1-3.el7.x86_64.rpm
        - https://kojipkgs.fedoraproject.org//packages/http-parser/2.7.1/3.el7/x86_64/http-parser-debuginfo-2.7.1-3.el7.x86_64.rpm
        - https://kojipkgs.fedoraproject.org//packages/http-parser/2.7.1/3.el7/x86_64/http-parser-devel-2.7.1-3.el7.x86_64.rpm


`

**Comment by gkipkorir** [comment]
Had the same issue. Thanks for the suggestoin @ythalorossy! Just as a headsup for others, make sure you put the patch before the `-name: Install Node.js and npm` line.

**Comment by geerlingguy** [comment]
Yeah, annoyingly EPEL changes for an upstream RHEL release have basically broken half the CentOS world's Node.js installations; this project's automated tests have sent me a nice FAIL email once per day since that bug was opened: https://travis-ci.org/geerlingguy/ansible-for-devops

I'm kinda crossing my fingers and hoping the `7.4.1708` repo appears on http://mirror.centos.org/centos-7/ soon... if so, then this problem should basically fix itself with no changes required :(

**Comment by geerlingguy** [comment]
Note from https://seven.centos.org/2017/08/centos-linux-7-1708-based-on-rhel-7-4-source-code/

> Historically, the final release becomes available 3 to 6 weeks after the release of the source code by Red Hat.  So, we would expect our full release to happen sometime between August 22nd and  September 12th, 2017.

**Comment by geerlingguy** [comment]
Note that this issue fixed itself as there are now 7.4.1708 and 7.5.1804 directories available in the official mirrors.
