### ISSUE TITLE
Typo on page 62 (version 1.13)

### ISSUE THREAD

**Issue by jdavid5815** [geerlingguy/ansible-for-devops#70]
In the last sentence of the second paragraph, there is a typo:

.. only when the app's path in not in the forever list output.

Should be:

.. only when the app's path is not in the forever list output.

This typo is present in the hardcopy version (1.13).

**Comment by geerlingguy** [comment]
Thanks for reporting this, and sorry I didn't respond sooner; apparently I had fixed that typo sometime between version 1.13 and 1.16. I definitely need to get the updated version out to CreateSpace soon so new print editions have the fix in addition to the ebook editions!
