### ISSUE TITLE
Page 86: .bash_login instead of .bash_profile

### ISSUE THREAD

**Issue by jdavid5815** [geerlingguy/ansible-for-devops#71]
On the second line of page 86, alternatives to .bash_profile are listed: ".bashrc, .profile and .bash_profile". The last one ".bash_profile" should probably be replaced by ".bash_login", as ".bash_profile" is obviously not an alternative, but ".bash_login" is.

**Comment by geerlingguy** [comment]
@jdavid5815 - haha, you're quite right. I've updated that listing, and will add you to the credits in the errata/changelog. Thanks!
