### ISSUE TITLE
Cobbler has a different URL (page viii)

### ISSUE THREAD

**Issue by codeyy** [geerlingguy/ansible-for-devops#76]
Cobbler is said to be on http://www.cobblerd.org, but that should be http://cobbler.github.io/

**Comment by geerlingguy** [comment]
Yikes, good catch! I'll update it in the next release of the book, and credit @codeyy for finding the fix; thanks!

**Comment by geerlingguy** [comment]
This is in the current/newest release of the book on LeanPub, thanks!
