### ISSUE TITLE
Solr playbook issue: 404 on solr-4.7.1.tgz

### ISSUE THREAD

**Issue by jonathanhle** [geerlingguy/ansible-for-devops#8]
Looks like this was archived: http://apache.osuosl.org/lucene/solr/4.7.1/solr-4.7.1.tgz

Closest release I see available is http://apache.osuosl.org/lucene/solr/4.7.2/solr-4.7.2.tgz

**Comment by geerlingguy** [comment]
Thanks for reporting this! I didn't realize OSUOSL would be removing releases, but I've made a note to either find a more stable mirror or abstract the version in the example a little better so it's more maintainable :)

**Comment by jonathanhle** [comment]
NP - I ended up going with 4.7.2, putting the solr version and sha256sum into the vars template.
