### ISSUE TITLE
Django 2 requires Python 3 which breaks a Chapter 3 example

### ISSUE THREAD

**Issue by everett-toews** [geerlingguy/ansible-for-devops#81]
In Chapter 3, section "Configure the Application servers" when you go to install Django

```bash
$ ansible app -b -m easy_install -a "name=django state=present"
192.168.60.5 | FAILED! => {
    "changed": false,
    "msg": "Traceback (most recent call last):
    ...
    AttributeError: 'module' object has no attribute 'lru_cache'\n"
}
```

This is because Django 2 requires Python 3. 

The easy fix is to pin to a version of Django (1.11) that can use Python 2.

```bash
$ ansible app -b -m easy_install -a "name=django==1.11 state=present"
192.168.60.4 | SUCCESS => {
    "binary": "/bin/easy_install",
    "changed": true,
    "name": "django==1.11",
    "virtualenv": null
}
192.168.60.5 | SUCCESS => {
    "binary": "/bin/easy_install",
    "changed": true,
    "name": "django==1.11",
    "virtualenv": null
}
```

**Comment by mjoscelyne** [comment]
I also just encountered this error and confirm fix from @everett-toews is good.  Thanks.

**Comment by tuckr** [comment]
Same here. Thanks.

**Comment by codarrenvelvindron** [comment]
Another Workaround (what I did) - though everett-toews solution is simpler:
1. Download latest version of pip
ansible app -b -a "curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py""

2. Install latest pip 
ansible app -b -a "python get-pip.py"

3. Upgrade setuptools
ansible app -b -a "python -m pip install --upgrade pip setuptools wheel"

4. Install Django
ansible app -b -a "python -m pip install django"

**Comment by txynidakis** [comment]
Thanks heaps! Worked for me!

**Comment by geerlingguy** [comment]
The best way to get around this issue for now (without trying to get Python 3 on CentOS 7, which is another task for another day :) is to use the version modifier to tell `easy_install` to install a version <2:

```
ansible app -b -m easy_install -a "name=django<2 state=present"
```

I'm updating the book text now and will have an updated version on LeanPub shortly. Thanks for the bug report and all the feedback here!

**Comment by frankgerhardt** [comment]
I have this error too. Aha, closed an hour ago. WOW! <2 works. What a great reader experience!
