### ISSUE TITLE
page 59: app.js cannot listen on port 80

### ISSUE THREAD

**Issue by ofsoundmined** [geerlingguy/ansible-for-devops#89]
Before typing this I also tried using the files up github instead of the ones I typed/pasted and nothing worked until I used an unprivileged port.

**Comment by geerlingguy** [comment]
@ofsoundmined - When you had this problem, were you running the playbook against one of your own servers, or against a VM that you built locally, e.g. with the Vagrantfile as shown in the book?

The examples seem to work fine if I run them using the Vagrant-built VM, so maybe it's a privilege escalation error? Could be related to the fix I posted to #77.

**Comment by geerlingguy** [comment]
To be able to run on port 80, the node.js app has to be run with elevated privileges (e.g. `sudo node app.js` vs `node app.js` — or the equivalent for `forever`).

Note that this example runs the `forever` commands using `become`/`sudo`, to make sure it can listen on port 80. If you are building a more secure app that should not run under root privileges, you should probably opt for a higher port (e.g. `8080`) and then proxy it using Nginx or some other web server that can proxy traffic to the backend.
