### ISSUE TITLE
/includes/provisioning/vars.yml ==> 8.x or 8.0.x?

### ISSUE THREAD

**Issue by jonathanhle** [geerlingguy/ansible-for-devops#9]
In /includes/provisioning/vars.yml: 

This doesn't seem to work: 
drupal_core_version: "8.x"

This works fine:
drupal_core_version: "8.0.x"

The "drupal" project has "8.0.x" in it, so I'm guessing there was a typo transposing.

**Comment by geerlingguy** [comment]
Thanks for finding this!
