### ISSUE TITLE
page 3

### ISSUE THREAD

**Issue by vtraida** [geerlingguy/ansible-for-devops#90]
"If you’re on a Mac, installing Ansible is a piece of cake:
1. Install Homebrew26 (get the installation command from the Homebrew website).
2. Install Python 2.7.x (brew install python).
3. Install Ansible (pip install ansible)."

on ma os 10.13.4 is issue with Homebrew
better install according with official docs for ansible 2.5
sudo easy_install pip
sudo pip install ansible
ansible --version
ansible 2.5.0

**Comment by geerlingguy** [comment]
True; the pip install didn't always play as nice with macOS, but it does now, and the Homebrew situation can be a little more tricky since it defaults to Python 3. I'll update the instructions in the book.

**Comment by geerlingguy** [comment]
This has been fixed in the latest version of the book; I'll release an update once I have a few other changes to batch together with it. Thanks!
