### ISSUE TITLE
Strict Host Key Checking

### ISSUE THREAD

**Issue by i-zu** [geerlingguy/ansible-for-devops#94]
Hi!
First things first: thank you for the book! :)
Now about the issue. I encountered it in chapter 3 page 22 while running `ansible multi -a "hostname"` command. As SSH strict host key checking is "on" by default it causes 3 messages (one per each server: app1, app2 and db) asking whether you want to add the host to the list of known hosts. Although this behavior can be bypassed via changing either SSH or Ansible options (through config file or env variable) and it is not an 'issue' per se as such behavior is expected it would be nice to have it mentioned in the book.

Regards,
i-zu

**Comment by geerlingguy** [comment]
I've added the following tip:

> If you get an error like `The authenticity of host '192.168.60.5' can't be established.`, this is because SSH has a security feature which requires you to confirm the server's 'host key' the first time you connect. You can type `yes` on the command line (in this case multiple times) to dismiss the warning and accept the hostkey, or you can also set the environment variable `ANSIBLE_HOST_KEY_CHECKING=False`. The behavior for host key acceptance can also be configured in your SSH configuration file.
