### ISSUE TITLE
ELK playbook example error in nginx.conf

### ISSUE THREAD

**Issue by soulawaker** [geerlingguy/ansible-for-devops#96]
### Try and errors
Tried same 'ELK Playbook' example in the 'ELK Logging with Ansible' of the chapter 8 with some supplements.
#### supplements and run
1. Make the `provisioning/requirements.yml` file. 
   ```
   ---
   - src: geerlingguy.java
   - src: geerlingguy.nginx
   - src: geerlingguy.elasticsearch
   - src: geerlingguy.elasticsearch-curator
   - src: geerlingguy.kibana
   - src: geerlingguy.logstash
   - src: geerlingguy.logstash-forwarder
   ```
2. `ansible-galaxy install -r requirements.yml` 
3. Place the Vagrantfile in the `provisioning` folder.
4. Modify two lines in the Vagranfile.
   ```
   ansible.playbook = "elk/playbook.yml"      # origin: "provisioning/elk/playbook.yml"
   ansible.inventory_path = "elk/inventory"   # origin: "provisioning/elk/inventory"
   ```
5. `vagrant up`
#### errors
```
TASK [geerlingguy.nginx : Ensure nginx is started and enabled to start at boot.] ***
fatal: [logs]: FAILED! => {"changed": false, "msg": "nginx: [emerg] invalid number of arguments in \"access_log\" directive in /etc/nginx/nginx.conf:27\nnginx: configuration file /etc/nginx/nginx.conf test failed\n"}
```
I've jumped with `vagrant ssh` and checked `/etc/nginx/nginx.conf` below. But I can't find any weird points.
```
user  www-data;

error_log  /var/log/nginx/error.log warn;
pid        /run/nginx.pid;

worker_processes  2;


events {
    worker_connections  1024;
    multi_accept off;
}

http {

    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server_names_hash_bucket_size 64;

    client_max_body_size 64m;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                       '$status $body_bytes_sent "$http_referer" '
                       '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log main buffer=16k flush=2m;

    sendfile        on;
    tcp_nopush      on;
    tcp_nodelay     on;

    keepalive_timeout  65;
    keepalive_requests 100;

    server_tokens on;

    # gzip on;



    include /etc/nginx/conf.d/*.conf;
    include /etc/nginx/sites-enabled/*;

    }
```
### Environments and dependencies
OS: Elementary OS Loki (based on Ubuntu 16.04)
```
ansible 2.5.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/<username>/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

**Comment by soulawaker** [comment]
After I modified Vagrantfile's original line, `config.vm.box = "geerlingguy/ubuntu1204"`, to 1404, error messages disappeared. But just `192.168.9.90` couldn't take me the Kibana default pages unlike the book's descriptions. I've started digging into some roles specified in `playbook.yml` and found the Kibana port 5601. Then trying `192.168.9.90:5601` takes me the Kibana default pages. But I don't know this process can be workaround, in other words, whether just '192.168.9.90' should show the right result or not.

**Comment by geerlingguy** [comment]
Thanks for the report; I'll try to get to updating the ELK example soon. It's one of the few that I haven't had the time to update in a while (and a LOT has changed in the ELK ecosystem in the past year or so...)

**Comment by i-zu** [comment]
I believe this is because of too old Nginx on Ubuntu 12.04. 'flush' option in 'access_log' directive appeared later.

**Comment by geerlingguy** [comment]
Also, just for reference, I think this example is actually in the ansible-vagrant-examples repo: https://github.com/geerlingguy/ansible-vagrant-examples/tree/master/elk

**Comment by geerlingguy** [comment]
Closing this issue in favor of https://github.com/geerlingguy/ansible-for-devops/issues/196, as I will be reworking the example in its entirety.
