### ISSUE TITLE
Ubuntu LAMP with Drupal issue

### ISSUE THREAD

**Issue by alexakarpov** [geerlingguy/ansible-for-devops#97]
Hello,

I'm really enjoying both Ansible and the book, I must say. But here's a problem I ran into when running the corresponding playbook:

The summary  shows that all the tasks up to "Install Drupal" went through:\

> : ok=22   changed=18   unreachable=0    failed=1

But that last one failed with a message that's pretty damn hard to read (I'm hoping later in the book there will be something on customizing the output formatting)

> TASK [Install Drupal.] *************************************************************************************************
> fatal: [35.183.54.202]: FAILED! => {"changed": true, "cmd": ["drush", "si", "-y", "--site-name=Drupal Test", "--account-name=admin", "--account-pass=admin", "--db-url=mysql://alexakarpov_drupal:1234@localhost/alexakarpov_drupal", "--root=/var/www/drupal-8.3.x-dev"], "delta": "0:00:00.267496", "end": "2018-07-02 18:16:26.440261", "msg": "non-zero return code", "rc": 1, "start": "2018-07-02 18:16:26.172765", "stderr": "Failed to create database: ERROR 1045 (28000): Access denied for user\u001b[31;40m\u001b[1m[error]\u001b[0m\n'alexakarpov_drupal'@'localhost' (using password: YES)", "stderr_lines": ["Failed to create database: ERROR 1045 (28000): Access denied for user\u001b[31;40m\u001b[1m[error]\u001b[0m", "'alexakarpov_drupal'@'localhost' (using password: YES)"], "stdout": "You are about to create a /var/www/drupal-8.3.x-dev/sites/default/settings.php file and CREATE the 'alexakarpov_drupal' database. Do you want to continue? (y/n): y", "stdout_lines": ["You are about to create a /var/www/drupal-8.3.x-dev/sites/default/settings.php file and CREATE the 'alexakarpov_drupal' database. Do you want to continue? (y/n): y"]}

Ok some "access denied" in there - but the only access I had to set up before running the playbook was to make sure I have the remote_user configured to 'ubuntu', with a private key from AWS, and instruct it to use root as become_user. All the rest is meant to be automatic, right?

**Comment by alexakarpov** [comment]
PS: re-running the playbook did allow me to complete the setup; but the question of how to interpret this kind of failure remains; likewise, the question on formatting the output

**Comment by dglinder** [comment]
The uglyness of the Ansible error output isn't something that Mr. Geerling has much control over in the examples, and he wouldn't put in code that wilfully produced and error without following it with code to address that.

I'm not a Drupal expert nor do I have Drupal system so I can only guess at the root cause, but the fact that "drush" is prompting to continue ("Do you want to continue? (y/n): y"), is this a change in newer Drupal releases have that we need to adjust the command line further (e.g. add a "-y" flag)?

**Comment by alexakarpov** [comment]
@dglinder of course, I didn't mean to imply the example is broken; also, after a quick search, I've found a very simple way of making the output more human-friendly, by adding this to the /etc/ansible/ansible.cfg:

> stdout_callback=minimal
